== Conformance

This standard defines the following requirements classes, 
grouped by their standardization target:

* Web API
** <<rc_filter,Filter>>
** <<rc_features-filter,Features Filter>>

The <<rc_filter,Filter>> requirements class defines a set of HTTP query
parameters that may be used to specify complex filter expressions on
HTTP requests.  The specific set of parameters defined in this requirements
class is:

* `filter` - The filter expression.
* `filter-lang` - The language used in the filter expression.
* `filter-crs` - The coordinate reference system used in the filter expression, if Part 2 is supported.

This requirements class also defines the Queryables resource (at path `/collections/{collectionId}/queryables`) that can be used to determine the list of property names and types that may be used to construct filter expressions.

The <<rc_features-filter,Features Filter>> requirements class defines the
binding between the <<rc_filter,Filter>> requirements class and the
<<OAFeat-1,OGC API - Features - Part 1: Core>> standard.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_filter,Filter>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter
|<<ats_features-filter,Features Filter>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter
|===

=== Roadmap

The content of this sub-clause is informative.

Because the filter parameters is not exclusively useful for features, it is anticipated that the
<<rc_filter,Filter>> requirements class will eventually become parts of the OGC API Common suite of standards thus
leaving the <<rc_features-filter,Features Filter>> requirements class as part
3 of the OGC API Features specifications.
