== Requirements Class "Filter"

[[filter-overview]]
=== Overview

include::requirements/requirements_class_filter.adoc[]

<<OAFeat-1,OGC API - Features - Part 1: Core>> defines two filtering parameters on the resource at path `/collections/{collectionId}/items`: `bbox` and `datetime`. <<OAFeat-1,OGC API - Features - Part 1: Core>> also adds support for simple equality predicates logically joined using the `AND` operator. These capabilities offer simple resource filtering for HTTP requests.

The Filter requirements class defines additional query parameters that allow more
complex filtering expressions to be specified when querying server resources.

Specifically, this clause defines the parameters, `filter`, `filter-lang` and
`filter-crs`.

[[filter-param]]
=== Parameter filter

The <<rc_filter,Filter>> requirements class defines a general parameter, `filter`, whose
value is a filter expression to be applied when retrieving resources. This
is necessary to determine which resources should be included in a result set.

include::requirements/filter/REQ_filter-param.adoc[]

include::recommendations/filter/PER_filter-default.adoc[]

[[filter-lang-param]]
=== Parameter filter-lang

Any predicate language that can be suitably expressed as the value of an
HTTP query parameter may be specified as the value of the `filter` parameter.
In order to specify that specific language that is being used, this clause
defines the `filter-lang` parameter.

include::requirements/filter/REQ_filter-lang-param.adoc[]

The enumerated value `cql2-text` is used to indicate that the value of the
<<filter-param,`filter`>> parameter is the https://docs.ogc.org/is/21-065r2/21-065r2.html#cql2-text[text encoding of CQL2].

The enumerated value `cql2-json` is used to indicate that the value of the
<<filter-param,`filter`>> parameter is the https://docs.ogc.org/is/21-065r2/21-065r2.html#cql2-json[JSON encoding of CQL2].

Servers that support other filtering languages can extend this list of values
as necessary although the meanings of any additional values are not described
in this Standard.

[[filter-crs-param]]
=== Parameter filter-crs

For reasons discussed in the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practices document>>, spatial coordinates by default are in the coordinate reference system WGS 84 longitude and latitude for 2D coordinates and WGS 84 longitude, latitude and ellipsoidal height in meters for 3D coordinates. For servers that support geometries in other coordinate reference systems, the `filter-crs` parameter defined in this clause allows clients to assert which CRS is being used to encode geometric values in a filter expression.  Otherwise, the `filter-crs` parameter has no use.

include::requirements/filter/REQ_filter-crs-wgs84.adoc[]

include::requirements/filter/REQ_filter-crs-param.adoc[]

NOTE: Discovery of the list of supported coordinate reference systems for use with the `filter-crs` parameter depends on the filterable resource.

include::recommendations/filter/REC_filter-crs-list.adoc[]

=== Interaction with other predicates

Servers can and often will support additional filtering parameters on filterable resources.  This clause defines how the `filter` parameter and other filtering parameters should interact if specified in a single request.

include::requirements/filter/REQ_mixing-expressions.adoc[]

=== CQL2 functions

If the server supports CQL2 and the requirements class "Functions", a resource, `/functions` is published that allows clients to discover the
list of functions that a server offers.

include::requirements/filter/REQ_get-functions-operation.adoc[]

include::requirements/filter/REQ_get-functions-response-json.adoc[]

[[example_9_10]]
.Get functions JSON response example
====
[source,JSON]
----
{
   "functions": [
      {
         "name": "min",
         "arguments": [
            {
               "type": ["string","number","datetime"]
            },
            {
               "type": ["string","number","datetime"]
            }
         ],
         "returns": ["string","number","datetime"]
      },
      {
         "name": "max",
         "arguments": [
            {
               "type": ["string","number","datetime"]
            },
            {
               "type": ["string","number","datetime"]
            }
         ],
         "returns": ["string","number","datetime"]
      },
      {
         "name": "geometryType",
         "arguments": [
            {
               "type": ["geometry"]
            }
         ],
         "returns": ["string"]
      }
   ]
}
----
====

=== Filter expression languages

This Standard only specifies `filter-lang` values for the <<CQL2,Common Query Language (CQL2)>>. However, support for
this filter expression language is not mandatory and other languages 
can be used as the value of the <<filter-param,filter parameter>>, too.  

[[filter-response]]
=== Response

A filter expression defines a subset of items from a collection that should be presented in a query response.

include::requirements/filter/REQ_response.adoc[]
