== Requirements Class "Features Filter"

[[features-filter-overview]]
=== Overview

include::requirements/requirements_class_features-filter.adoc[]

This clause defines the binding between the <<OAFeat-1,OGC API - Features - Part 1: Core>> Standard and the filter parameters defined in the <<rc_filter,Filter conformance class>> as well as the Queryables resource defined in the <<rc_queryables,Queryables conformance class>>.

=== Queryables

==== Operation

include::requirements/features-filter/REQ_get-queryables-op.adoc[]

=== Feature Collection

==== Response

include::requirements/features-filter/REQ_queryables-link.adoc[]

=== Features

==== Operation

As per the <<OAFeat-1,OGC API - Features - Part 1: Core>> Standard, features are accessed using the HTTP GET method via the `/collections/{collectionId}/items` path (see http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_items[Features]).  The following additional requirements bind the parameters <<filter-param,filter>>, <<filter-lang-param,filter-lang>> and <<filter-crs-param,filter-crs>> to the GET operation on this path.

include::requirements/features-filter/REQ_filter-param.adoc[]

include::requirements/features-filter/REQ_filter-lang-param.adoc[]

include::recommendations/features-filter/REC_text-encoding.adoc[]

// TODO include::requirements/features-filter/REQ_cql2-text.adoc[]

include::recommendations/features-filter/REC_json-encoding.adoc[]

// TODO include::requirements/features-filter/REQ_cql2-json.adoc[]

include::requirements/features-filter/REQ_filter-crs-param.adoc[]

Discovery of the list of supported coordinate reference systems for use with the filter-crs parameter is fully described in <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>.  Briefly, the list of supported CRSs can be found in the global list of CRS identifiers (path: `/collections/crs`) and/or the list of collection-specific CRS identifiers (path: `/collections/{collectionsId}/crs`).

==== Response

include::requirements/features-filter/REQ_response.adoc[]
