[[req_filter_get-queryables-op-global]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/filter/get-queryables-op-global*
^|A |A server that implements this requirements class SHALL support the HTTP GET operation at the path `/queryables` and the media type `application/schema+json`.
^|B |The queryables accessed at this path SHALL be valid for all collections identified in the Collections resource (path `/collections`).
^|C |The Queryables resource SHALL be referenced from the Landing Page resource
with a link with the link relation type `\http://www.opengis.net/def/rel/ogc/1.0/queryables`.
|===


[[filter-param-multiple-collections]]
=== Cross-collection queries

The only filterable resource defined in <<OAFeat-1,OGC API - Features - Part 1: Core>>
is the Features resource at `/collections/{collectionId}/items` which operates 
on a single collection.  However an API can provide other, higher level, resources that potentially operate on multiple collections. 

The simplest approach for handling such cross-collection queries is one that is 
consistent with one-collection queries.  Specifically, the `filter` parameter, if
provided, applies to all referenced collections.  Of course this implies that all 
properties referenced in the filter expression are valid for all referenced collections 
and should be taken from the <<filter-queryables,global queryables list>>.

[[req_filter_filter-param-multiple-collections]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/filter/filter-param-multiple-collections*
^|A |A server that implements this extension and also supports queries across multiple collections SHALL only allow properties from the <<req_filter_get-queryables-op-global,global list of queryables>> to be referenced in a filter expression.
^|B |If a cross-collection filter expression references properties that are not listed in the <<req_filter_get-queryables-op-global,global list of queryables>>,
then the server SHALL respond with an HTTP status code of `400`.
|===

The following example illustrates a notional query on a hypothetical Query resource
that uses a CQL filter and references multiple collections:

[[example_2]]
.Multi-collection filter example
----
http://www.someserver.com/ogcapi/search?
  collections=collection1,collection3&
  filter-lang=cql-text&
  filter=prop1=10 AND prop2>45
----

NOTE: Arrays of filter expressions that operate on each collection specified in a query (or subsets thereof) are out of scope for this extension and  would be the subject of a different part of the "OGC API - Features" suite of specifications.
