== Requirements Class "Coordinate Reference Systems (by reference)"

[[crs]]
=== Overview

[[crs-format]]
=== Format model

include::requirements/REQ_crs-format-model.adoc[]

Other formats may be supported as well but they are not described in this
standard.

=== Feature collections metadata (Discovery)

==== Response

The WFS core defines, but does not use, the `crs` property (see X.X) on the
collection metadata (i.e. /collections/{collectionId}). This extension makes
this property mandatory for spatial collections (i.e coolections with geometry
values properties).

include::requirements/REQ_fc-md-crs-list.adoc[]

include::requirements/REQ_fc-md-crs-list-storageCrs.adoc[]

include::requirements/REQ_fc-md-crs-list-defaultCrs.adoc[]

The list of supported coordinate reference systems may also include the default
CRS but this is not a requirement.

This examples illustrates a list of supported coordinate reference systems.

[source,JSON]
----
  "collections": [
    {
      "id": "buildings",
      "title": "Buildings",
      "description": "Buildings in the city of Bonn.",
      "links": [
        { "href": "http://data.example.org/collections/buildings/items",
          "rel": "items", "type": "application/geo+json",
          "title": "Buildings" },
        { "href": "http://example.org/concepts/building.html",
          "rel": "describedBy", "type": "text/html",
          "title": "Feature catalogue for buildings" }
      ],
      "extent": {
        "spatial": [ 7.01, 50.63, 7.22, 50.78 ],
        "temporal": [ "2010-02-15T12:34:56Z", "2018-03-18T12:11:00Z" ]
      },
      "crs": [
        "http://www.opengis.net/def/crs/EPSG/0/4326",
        "http://www.opengis.net/def/crs/EPSG/0/4269",
        "http://www.opengis.net/def/crs/EPSG/0/3857",
        "http://www.opengis.net/def/crs/EPSG/0/3395",
        "http://www.opengis.net/def/crs/EPSG/0/4267",
        "http://www.opengis.net/def/crs/EPSG/0/26703",
        "http://www.opengis.net/def/crs/EPSG/0/26704",
        "http://www.opengis.net/def/crs/EPSG/0/26705",
        "http://www.opengis.net/def/crs/EPSG/0/26706",
        "http://www.opengis.net/def/crs/EPSG/0/26707",
        "http://www.opengis.net/def/crs/EPSG/0/26708"
      ]
    }
  ]
----

To prevent unnecessary duplication of lists of supported coordinate reference
systems, a global list of supported coordinate reference systems may be
provided as part of the feature collections metadata.

include::requirements/REQ_fc-md-crs-list-global.adoc[]

include::requirements/REQ_fc-md-crs-list-global-default.adoc[]

=== Feature collections (Query)

==== Parameter bbox-crs

Part 1, WFS Core mentions the `bbox-crs` parameter.  Thie extension defines
this parameter as a means of asserting the CRS of the values used in the `bbox`
(see X.X) parameter.

include::requirements/REQ_fc-bbox-crs-definition.adoc[]

include::requirements/REQ_fc-bbox-crs-valid-values.adoc[]

include::requirements/REQ_fc-bbox-crs-default-value.adoc[]

include::requirements/REQ_fc-bbox-crs-action.adoc[]

include::requirements/REQ_bbox-crs-exception.adoc[]

The following fragment illustrates the use of the `bbox-crs` parmeter:

[source]
----
   ...&bbox=160.6,-155.95,-170,-25.89&bbox-crs=http://www.opengis.net/...
----

==== Parameter crs

This extension defines a parameter on the `/collection/{collectionId}/items`
resource that may be used to assert a specific WFS-supported CRS transformation
to be applied to the compatible (see X.X) geometries of the features returned
in a response document.

include::requirements/REQ_fc-crs-definition.adoc[]

include::requirements/REQ_fc-crs-valid-value.adoc[]

include::requirements/REQ_fc-crs-default-value.adoc[]

include::requirements/REQ_fc-crs-action.adoc[]

include::requirements/REQ_fc-crs-action-exception.adoc[]

include::requirements/REQ_crs-exception.adoc[]

The following fragement illustrated the use of the `crs` parameter:

[source]
----
.../collections/buildings/items?crs=http://www.opengis.net/def/crs/epsg/0/26703&...
----

==== Output format considerations (TBD)

Part 1, WFS Core defines three conformance classes related to output formats:

   - GML
   - GeomJSON
   - HTML

GML has full CRS support and no further requirements are imposed by this
standard.

GeoJSON normatively supports WGS84 (lon,lat) but the "prior arrangment"
provision allows other coordinate systems to be used.

include::requirements/REQ_geojson.adoc[]

NOTE: Need to do more work on HTML!

HTML only supports WGS84 based on schema.org dependency; not sure if this is
an issue but schema.org annotations seem to require WGS84 (lat,lon) yet WFS
core requires lon,lat by default.

==== Compatibility of coordinate reference systems (TBD)

Coordinate reference systems that differ in dimensionality or that have no
defined datum transformation between them may be incompatible for the purposes
of geometry coordinate conversion. Where the request srsName references a CRS
that is incompatible with the storage CRS of a geometry property, the service
shall encode that geometry property using some other CRS identified with an
srsName attribute on that property; there is no requirement that this srsName
attribute be wfs:DefaultCRS or one of those listed in wfs:OtherCRS.

If a filter predicate compares two geometries with incompatible CRS, the server
shall generate a 400 exception with an appropriate message.

EXAMPLE: A feature with both 2D and 3D geometry properties is requested with
srsName set to a 2D CRS; the 2D property is encoded in the requested CRS, and
the 3D property is encoded with some 3D CRS identified in the srsName of the
geometry.

EXAMPLE: A 1D geometry property whose coordinate is the path length along a
LineString (itself defined in 3D with some CRS) with gml:id="geom.123" in the
same response is encoded with srsName="#geom.123".

EXAMPLE: A 1D geometry property whose coordinate is defined in an external
resource is encoded with srsName set to an HTTP URI for that external resource.

==== Coordinate system and axis order (experimental)

Because of the inconsistent provision of coordinate reference system metadata
in geospatial encodings and the continued confusion caused by the axis order
of coordinates, this standard defines a mechanism for a server to clearly and
unambiguously assert the coordinate reference system and axis order being used
in a response document independent of the requested output format.

include::requirements/REQ_ogc-crs-header.adoc[]

include::requirements/REQ_ogc-crs-header-value.adoc[]

include::requirements/REQ_ogc-crs-header-axis-order-value.adoc[]

include::requirements/REQ_ogc-crs-header-axis-names.adoc[]

include::requirements/REQ_ogc-crs-header-axis-order-action.adoc[]

The following example illustrates the use of the `OGC-CRS` header.

[source]
----
   OGC-CRS: http://www.opengis.net/def/crs/OGC/1.3/CRS84; axisOrder=lon,lat
----
