[[sc_transactions]]
== Requirements Class "Transactions"

=== Overview

include::requirements/requirements_class_transactions.adoc[]

A server that implements this requirements class provides the ability to execute transactions on one or more collections.

Transactions can have atomic semantics which means that every action in the require must complete successfully otherwise the entire operation should fail and the server should report an exception.

Transactions can also have batch semantics which means that every action is the requrest is independent of every other action in the request.  If a single action should fail, processing of the transaction continues and the failed action(s) is(are) reported in the transaction response.

In either case, the transaction response should indicate the number of resource inserted, updated, replaced or deleted.  In the case of newly created resources the transaction response should also report the identifiers of the newly created resources.

NOTE: In order to promote interoperability, each OGC Standard that extends this Standard should make recommendations concerning the representation of a transaction and the representation of resources contained therein.  See <<json,JSON encoding for Transactions>> for a discussion on the representation of a transactions and <<features,Features>> for a discussion on the representions of features.

[[http_status_codes]]
==== HTTP status codes

API clients should be prepared to handle any registered HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of relevance to implementors of this Standard. Status codes 200, 201, 202, 204 and 404 are called out in this Standard's requirements. Therefore, support for some of these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory but are important for the implementation of a well-functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`201` |The server has been fulfilled the operation and a new resource has been created. 
|`202` |The request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing happens.
|`204` |A successful request with no additional content to send in the response.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`412` |The status code indicates that one or more conditions given in the request header fields evaluated to false when tested by the server.
|`413` |The server is refusing to process the request because the request content is larger than the server is willing or able to process.
|`415` |The server is refusing to service the request because the content is in a format not supported by this method on the target resource.
|`422` |The server understands the content type of the request content and the syntax of the request content is correct but was unable to process the contained instructions. For example, the submitted resource does not meet a semantic constraint, e.g. a mandatory property is missing.
|`428` |The server requires the request to be conditional.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/PER_additional-status-codes.adoc[]

The https://docs.ogc.org/is/17-069r4/17-069r4.html#_api_definition_2[API Description Document] describes the HTTP status codes generated by an API. This should not be an exhaustive list of all possible status codes. Expecting an API designer to control the use of HTTP status codes which are not generated by their software is not reasonable. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[cross_origin]]
==== Cross-origin requests

See <<OAFeat-1,OGC API - Features - Part 1: Core>>, section link:http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#cross_origin[Support for cross-origin requests], about the importance of supporting cross-origin requests, typically via link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)].

==== Schemas

This Standard makes no assumptions about any schema constraints that a server may impose upon resource data encoded in a transaction.  The intent is to support both "schema-less" servers (such as those back-ended by document data stores) as well as servers that have underlying schema constraints (such as those back-ended by an RDBMS).

In the "schema-less" case, as long as the resources in the incoming transaction meet the requirements of the declared media type (e.g. valid GeoJSON features in a JSON-encoded transaction) then, if the operation is successfully processed, the server should respond with a 20x status response.

In the case where the server imposes schema constraints, the server should publish schemas to help clients create requests that are not rejected.  In the case where the resource is a feature, see <<xxx,OGC API - Features - Part 5: Schema>>.

=== Executing transactions

==== Sequence diagram

The following diagram illustrates the sequence diagram for executing a transaction.

....
   Client                                                          Server
     |                                                               |
     |   POST /transactions   HTTP/1.1                               |
     |   Content-Type: <media type of transaction representation>    |
     |                                                               |
     |   ... Body contains representation of the transaction ...     |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             |
     |                                                               |
     |   ... Body contains a report of the number of resources       |
     |       created, updated, replaced or deleted.  In the case     |
     |       of newly created resources, the report all includes     |
     |       the identifiers of those resources ...                  |
     |<--------------------------------------------------------------|
....

==== Operation

include::requirements/transactions/REQ_post-op.adoc[]

==== Request body

include::requirements/transactions/REQ_body.adoc[]

include::recommendations/transactions/PER_body.adoc[]

include::requirements/transactions/REQ_content-type.adoc[]

include::recommendations/transactions/REC_json.adoc[]

See https://www.rfc-editor.org/rfc/rfc9110#field.content-type[section 8.3 of RFC 9110] for details.

==== Response

include::requirements/transactions/REQ_response-rid.adoc[]

include::recommendations/transactions/PER_rid.adoc[]

include::requirements/transactions/REQ_response.adoc[]

include::recommendations/transactions/REC_honor-return-preference.adoc[]

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

[[sc_atomic]]
== Requirements Class "Atomic Semantics"

=== Overview

include::requirements/requirements_class_atomic.adoc[]

If atomic semantics are being applied to the execution of a transaction then all actions contained within the transaction must complete successfully.  If any action contained within the transaction fails then the entire transaction fails and the state of all affected collections must be restored to what it was before the transaction was executed.

=== Declaring support of atomic semantics

include::requirements/atomic/REQ_atomic.adoc[]

[[sc_batch]]
== Requirements Class "Batch Semantics"

=== Overview

include::requirements/requirements_class_batch.adoc[]

If batch semantics are being applied then each action contained within a transaction is independent of any other action.  Should one or more actions fail, the transaction proceeds to completion anyway and the failed actions are reported in the response.

=== Declaring support of batch semantics

include::requirements/batch/REQ_batch.adoc[]
