-- Schema for the OGC API Features Part 4 ATS test dataset (buildings).
-- The "updated" column drives the Last-Modified header (optimistic locking
-- using timestamps); the trigger maintains it on every change and assigns
-- an identifier on INSERT when the client/server did not provide one
-- (ldproxy CRUD inserts without the id column and reads it via RETURNING).

CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS buildings;
DROP SEQUENCE IF EXISTS buildings_id_seq;

CREATE SEQUENCE buildings_id_seq START 100;

CREATE TABLE buildings (
  id text PRIMARY KEY,
  name text,
  function text,
  height double precision,
  owner text,
  updated timestamptz NOT NULL DEFAULT now(),
  geom geometry(Polygon, 25832)
);

CREATE OR REPLACE FUNCTION buildings_before() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := 'B.' || nextval('buildings_id_seq');
  END IF;
  IF TG_OP = 'UPDATE' OR NEW.updated IS NULL THEN
    NEW.updated := now();
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_buildings_before
  BEFORE INSERT OR UPDATE ON buildings
  FOR EACH ROW EXECUTE FUNCTION buildings_before();

-- Second collection with the same buildings, but with client-assigned feature
-- identifiers (the "upsert" case): the id column is not generated on insert, so
-- new features are created with PUT on the resource endpoint and the collection
-- advertises "supportsNonAutogeneratedResourceIds": true. A separate table keeps
-- the two collections independent, so that mutations in one do not show up in
-- the other.

DROP TABLE IF EXISTS buildings_upsert;

CREATE TABLE buildings_upsert (
  id text PRIMARY KEY,
  name text,
  function text,
  height double precision,
  owner text,
  updated timestamptz NOT NULL DEFAULT now(),
  geom geometry(Polygon, 25832)
);

CREATE OR REPLACE FUNCTION buildings_upsert_before() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'UPDATE' OR NEW.updated IS NULL THEN
    NEW.updated := now();
  END IF;
  RETURN NEW;
END $$;

CREATE TRIGGER trg_buildings_upsert_before
  BEFORE INSERT OR UPDATE ON buildings_upsert
  FOR EACH ROW EXECUTE FUNCTION buildings_upsert_before();
