[appendix]
:appendix-caption: Annex
== Abstract Test Suite (Normative)

=== Introduction

OGC API-Features is not a Web Service in the traditional sense. Rather, it defines the behavior and content of a set of Resources exposed through an RESTful Application Programing Interface (API). Compliance testing for API-Features and similar standards must answer three questions:

.  Are the capabilities advertised through the API Description compliant with the standard?

.  Does the API implement those capabilities as advertised?

.  Do the resources returned by the micro-services meet the structure and content requirements of the standard?

Further complicating the issue, an API may expose resources in addition to those defined by the standard. A test engine must be able to traverse the API description document, identify test points, and ignore resource paths which are not to be tested. 

=== Approach to Testing

The Test Approach used in the API-Features Abstract Test Suite includes four steps:

TBD

=== Conformance Class Core

include::abstract_tests/ATS_class_core.adoc[]

=== Conformance Class GeoJSON

include::abstract_tests/ATS_class_geojson.adoc[]

=== Conformance Class GML Simple Features Level 0

include::abstract_tests/ATS_class_gmlsf0.adoc[]

=== Conformance Class GML Simple Features Level 2

include::abstract_tests/ATS_class_gmlsf2.adoc[]

=== Conformance Class HTML

include::abstract_tests/ATS_class_html.adoc[]

=== Conformance Class OpenAPI 3.0

include::abstract_tests/ATS_class_oas30.adoc[]
