[[xml_examples]]
[appendix]
:appendix-caption: Annex
== XML examples (Informative)

=== Overview

This annex includes examples of XML/GML responses to illustrate how the
OpenAPI fragments used to define the requirements for the
<<rc_core,Core requirements class>> are expressed in XML using the
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/xml/wfs.xsd[WFS 3.0 Core XML Schema].

=== A Landing page

[source,XML]
----
include::../xml/examples/LandingPage.xml[]
----

=== Conformance statements

This server conforms to the recommended requirements classes, plus the GML Simple Features Profile, Level 0.

[source,XML]
----
include::../xml/examples/ConformsTo.xml[]
----

=== Feature collections metadata

This service offers three feature collections (airport facilities, roads, inland water areas).

[source,XML]
----
include::../xml/examples/Collections.xml[]
----

=== Feature collection metadata

Only the information for the selected feature collection (roads) is included in the response.

[source,XML]
----
include::../xml/examples/Collection.xml[]
----

=== A feature collection

This response contains 2 features of the airport facilities collection and has a link to the next features.

[source,XML]
----
include::../xml/examples/FeatureCollection.xml[]
----
