[appendix]
:appendix-caption: Annex
== Abstract Test Suite (Normative)

CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/112[ISSUE 112] +
Currently, only the Core and OpenAPI 3.0 conformance classes are addressed by the Abstract Test Suite. The other four conformance classes (HTML, GeoJSON, GML-SF0, GML-SF2) are not yet covered. How they will be addressed is the subject of on-going discussions within the WFS 3.0 SWG.

=== A.1 Overview

WFS 3.0 is not a Web Service in the traditional sense.  Rather, it defines the behavior and content of a set of Resources exposed through an RESTful Application Programing Interface (API). Compliance testing for WFS 3.0 and similar standards must answer three questions:

.  Are the capabilities advertised through the API Description compliant with the standard?

.  Does the API implement those capabilities as advertised?

.  Do the resources returned by the micro-services meet the structure and content requirements of the standard?

Further complicating the issue, an API may expose resources in addition to those defined by the standard.  A test engine must be able to traverse the API description document, identify test points, and ignore resource paths which are not to be tested.  The process for identifying test points is provided in Section A.4.3.

=== A.2 Conventions

The following conventions apply to this Abstract Test Suite:

==== A.2.1 Path Templates

Path templates are used throughout these test suites.  Path templating refers to the usage of curly braces “{}” to mark a section of a URL path that can be replaced using path parameters.  The terms used to describe portions of these templates are based on the URL syntax described in RFC 3986.

*  scheme: http | https

*  authority: DNS name of the server with optional port number

*  path: The slash delimited identifier for a resource on the server

*  query: query parameters following the "?" character

*  fragment: identifies an element within the resource. Preceded by the "#" character

==== A.2.2 API Description Document

The WFS 3.0 standard does not mandate a standard format for the API Description Document.  However, some form of standard is needed if tests are to be accurately described and implemented.  Therefore, this Abstract Test Suite asserts that the API Description document is compliant with OpenAPI 3.0.  This Test Suite will be updated if and when an alternative is commonly adopted.

==== A.2.3 Resource Encodings

The WFS 3.0 standard does not mandate a standard encoding for resources returned by the API. Yet a compliance test requires some minimal level of expected behavior. Therefore, this Abstract Test Suite asserts that the API returns resources encoded in HTML and GeoJSON. Since no compliance test suite exists for these encodings at this time, the resources shall be presented to the test operator for human inspection.  

==== A.2.4 Processing Security Objects

OpenAPI does not provide a standard way to associate a security requirement with a single server URI.  Therefore, WFS 3.0 compliance tests will have to make that association through the runtime challenge-response transaction.  At this time the role of the Security Objects should be considered advisory.

Security Requirements can be defined at both the OpanAPI root level and at the Operation Object level. The following rules should be followed to understand the scope of a Security Requirement:

* The Security Requirements defined at the root level are the default requirements for all operations and servers.

* If Security Requirements are defined at the Operation level, then those Requirements, and not the ones defined at the OpenAPI level, shall be used with that operation.

* An empty set of Security Requirements at the Operation level indicates that there are no security requirements for that operation.

Note: this allows operations to opt-out of security requirements defined at the OpenAPI level.

==== A.2.4 Parameters

The following observations apply for WFS 3.0 parameters:

. WFS 3.0 does not use cookies.

. Query parameters follow common Web practice

. Header parameters are restricted to custom headers

. For path parameters, the name of the parameter must match the name of the variable in the path template in the path object

Parameters are defined at the Path Item and Operation level.  Parameters defined at the Path Item level must apply to all operations under that Path item. These parameters may be modified at the Operation level but they may not be removed.

==== A.2.5 Testable Paths

A testable path is a path which corresponds to one of the paths defined in the WFS 3.0 specification. There are three alternatives for making this determination:

. The path URI matches – this is the simplest approach but may be subject to error

. Use mandatory tags in the tags field of the Operation Object

. Use standardized operation ids for the operationId field of the Operation Object

A testable path is validated against the rules for that path.  At a minimum that includes:

. Building a list of all parameters which are defined in the standard

. Validate that the mandatory parameters are present and required

. Validate type, format, etc. for each parameter in the list.

. Validate that there are no mandatory parameters which are not on the list.

=== A.3 Requirements Trace Matrix

[width="100%"]
|====================
| *Requirement 1:* API Landing Page Operation +
  The server SHALL support the HTTP GET operation at the path /. +
  Tests: A.4.2.1
| *Requirement 2:* API Landing Page Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema root.yaml and include at least links to the following resources: +
 - /api (relation type 'service') +
 - /conformance (relation type 'conformance') +
 - /collections (relation type 'data') +
Tests: A.4.2.2 +
| *Requirement 3:* API Definition Operation +
The server SHALL support the HTTP GET operation at the path /api. +
Tests: A.4.2.3 +
| *Requirement 4:* API Definition Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The server SHALL return an API definition document. +
Tests: A.4.2.3, A.4.2.4, A.4.4.1 +
| *Requirement 5:* Conformance Class Operation +
The server SHALL support the HTTP GET operation at the path /conformance. +
Tests: A.4.4.2 +
| *Requirement 6:* Conformance Class Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema req-classes.yaml and list all WFS 3.0 requirements classes that the server conforms to. +
Tests: A.4.4.3 +
| *Requirement 7:* HTTP 1.1 +
The server SHALL conform to HTTP 1.1. +
If the server supports HTTPS, the server SHALL also conform to HTTP over TLS. +
Tests: A.4.1.1 +
| *Requirement 8:* Coordinate Reference Systems +
Unless the client explicitly requests a different coordinate reference system, all spatial geometries SHALL be in the coordinate reference system http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS84 longitude/latitude) +
Tests: A.4.1.2 +
| *Requirement 9:* Feature Collections Metadata Operation +
The server SHALL support the HTTP GET operation at the path /collections. +
Tests: A.4.4.4 +
| *Requirement 10:* Feature Collections Metadata Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.  The content of that response SHALL be based upon the OpenAPI 3.0 schema content.yaml. +
Tests: A.4.4.5 +
| *Requirement 11:* Feature Collections Metadata Links +
A 200-response SHALL include the following links in the links property of the response: +
 - a link to this response document (relation: self), +
 - a link to the response document in every other media type supported by the server (relation: alternate). +
All links SHALL include the rel and type link parameters. +
Tests: A.4.4.5 +
| *Requirement 12:* Feature Collections Metadata Items +
For each feature collection in this distribution of the dataset, an item SHALL be provided in the property collections. +
Tests: A.4.4.5, A.4.4.6 +
| *Requirement 13:* Feature Collections Metadata Items Links +
For each feature collection in this distribution of the dataset, the links property of the collection SHALL include an item for each supported encoding with a link to the collection resource (relation: item). +
All links SHALL include the rel and type properties. +
Tests: A.4.4.6 +
| *Requirement 14:* Feature Collections Metadata Extent +
For each feature collection, the extent property, if provided, SHALL be a bounding box that includes all spatial and temporal geometries in this collection. +
If a feature has multiple properties with spatial or temporal information, it is the decision of the server whether only a single spatial or temporal geometry property is used to determine the extent or all relevant geometries. +
Tests: A.4.4.6 +
| *Requirement 15:* Feature Collection Metadta Operation +
The server SHALL support the HTTP GET operation at the path /collections/{collectionId}. collectionId is the `id` property in the feature collections metadata (JSONPath: $.collections[*].id). +
Tests: A.4.4.7 +
| *Requirement 16:* Feature Collection Metadata Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be the same as the content for this feature collection in the /collections response. +
Tests: A.4.4.8 +
| *Requirement 17:* Feature Collection Operation +
For every feature collection identified in the metadata about the feature collection (path /), the server SHALL support the HTTP GET operation at the path /collections/{collectionId}/items where {collectionId} is the `id` property in the feature collections metadata (JSONPath: $.collections[*].id). +
Tests: A.4.4.9 +
| *Requirement 18:* Feature Collection Operation Limit Parameter +
Each feature collection operation SHALL support a parameter limit with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
Tests: A.4.4.11 +
| *Requirement 19:* Feature Collection Operation Limit Parameter Response +
The response SHALL not contain more features than specified by the optional limit parameter. If the API definition specifies a maximum value for limit parameter, the response SHALL not contain more features than this maximum value. +
Only items are counted that are on the first level of the collection. Any nested objects contained within the explicitly requested items SHALL not be counted. +
Tests: A.4.4.11 +
| *Requirement 20:* Feature Collection Operation BoundingBox Parameter +
Each feature collection operation SHALL support a parameter bbox with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
Tests: A.4.4.12 +
| *Requirement 21:* Feature Collection Operation BoundingBox Parameter Response +
Only features that have a spatial geometry that intersects the bounding box SHALL be part of the result set, if the bbox parameter is provided. +
The bounding box is provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth): +
 - Lower left corner, coordinate axis 1 +
 - Lower left corner, coordinate axis 2 +
 - Lower left corner, coordinate axis 3 (optional) +
 - Upper right corner, coordinate axis 1 +
 - Upper right corner, coordinate axis 2 +
 - Upper right corner, coordinate axis 3 (optional) +
The coordinate reference system of the values SHALL be interpreted as WGS84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter bbox-crs. +
Tests: A.4.4.12 +
| *Requirement 22:* Feature Collection Operation Time Parameter +
Each feature collection operation SHALL support a parameter time with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
Tests: A.4.4.13 +
| *Requirement 23:* Feature Collection Operation Time Parameter Response +
Only features that have a temporal geometry that intersects the timestamp or time period SHALL be part of the result set, if the time parameter is provided. +
The temporal information is either a date-time or a period string that adheres to RFC3339. +
If a feature has multiple temporal properties, it is the decision of the server whether only a single temporal property is used to determine the extent or all relevant temporal properties. +
Tests: A.4.4.13 +
| *Requirement 24:* Feature Collection Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. +
Tests: A.4.4.10 +
The response SHALL only include features selected by the request. +
| *Requirement 25:* Feature Collection Response Links +
A 200-response SHALL include the following links: +
 - a link to this response document (relation: self), +
 - a link to the response document in every other media type supported by the service (relation: alternate). +
Tests: A.4.4.10 +
| *Requirement 26:* Feature Collection Response Links Parameters +
All links SHALL include the rel and type link parameters. +
Tests: A.4.4.10 +
| *Requirement 27:* Feature Collection Response timeStamp +
If a property timeStamp is included in the response, the value SHALL be set to the time stamp when the response was generated. +
Tests: A.4.4.10 +
| *Requirement 28:* Feature Collection Response numberMatched +
If a property numberMatched is included in the response, the value SHALL be identical to the number of features in the feature collections that match the selection parameters like bbox, time or additional filter parameters. +
A server MAY omit this information in a response, if the information about the number of matching features is not known or difficult to compute. +
Tests: A.4.4.10 +
| *Requirement 29:* Feature Collection Response numberReturned +
If a property numberReturned is included in the response, the value SHALL be identical to the number of features in the response. +
A server MAY omit this information in a response, if the information about the number of features in the response is not known or difficult to compute. +
Tests: A.4.4.10 +
| *Requirement 30:* Feature Operation +
For every feature in a feature collection (path /collections/{collectionId}/items), the service SHALL support the HTTP GET operation at the path /collections/{collectionId}/items/{featureId}. The parameter {collectionId} is each `id` property in the feature collection metadata (JSONPath: $.collections[*].id). {featureId} is a local identifier of the feature. +
Tests: A.4.4.14 +
| *Requirement 31:* Feature Opearation Response +
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. +
Tests: A.4.4.15 +
| *Requirement 32:* Feature Operation Response Links +
A 200-response SHALL include the following links in the response: +
 - a link to the response document (relation: self), +
 - a link to the response document in every other media type supported by the service (relation: alternate), and +
 - a link to the feature collection that contains this feature (relation: collection). +
All links SHALL include the rel and type link parameters. +
Tests: A.4.4.15 +
|====================

=== A.4 Abstract Test

The Test Approach used in the WFS 3.0 Abstract Test Suite includes four steps:

. Identify the test points

. Verify that API descriptions of the test points comply with the WFS 3.0 standard

. Verify that the micro-services at each test point behave in accordance with the WFS 3.0 standard.

. Verify that the resources returned at each test point are in accordance with the WFS 3.0 standard and any referenced content standard.

Identification of test points is a new requirement with WFS 3.0.  Since an API is not a Web Service, there may be RESTful endpoints advertised which are not intended to be targets of the compliance testing.  Section A.4.2 describes the process for crawling the API Description document and extracting those URLs which should be tested as well as the path(s) they should be tested with.  The concatenation of a Server URL with a path forms a test point.

Section A.4.3 describes how the test points are exercised to determine compliance with the WFS 3.0 standard.

==== A.4.1 General Tests

===== A.4.1.1 HTTP 1.1

====== a) Test Purpose:
Validate that the WFS services advertised through the API conform with HTTP 1.1.

====== b) Pre-conditions:
none

====== c) Test Method:

. All compliance tests shall be configured to use the HTTP 1.1 protocol exclusively.  

====== d) References:
Requirement 7

===== A.4.1.2 Coordinate Reference Systems

====== a) Test Purpose:
Validate that all spatial geometries provided through a WFS service are in the CRS84 spatial reference system unless otherwise requested by the client.

====== b) Pre-conditions:
none

====== c) Test Method:

. Do not specify a coordinate reference system in any request.  All spatial data should be in the CRS84 reference system.

. Validate retrieved spatial data using the CRS84 reference system.

====== d) References:
Requirement 8

==== A.4.2 Retrieve the API Description

===== A.4.2.1 Landing Page Retrieval

====== a) Test Purpose:
Validate that a landing page can be retrieved from the expected location.

====== b) Pre-conditions:

* A URL to the server hosting the landing page is known.

* The test client can authenticate to the server.

* The test client has sufficient privileges to access the landing page.

====== c) Test Method:

. Issue an HTTP GET request to the URL {root}/

. Validate that a document was returned with a status code 200

. Validate the contents of the returned document using test A.4.2.2

====== d) References:
Requirement 1

===== A.4.2.2 Landing Page Validation

====== a) Test Purpose:
Validate that the landing page complies with the require structure and contents.

====== b) Pre-conditions:

* The landing page has been retrieved from the server

====== c) Test Method:

. Validate the landing page against the root.yaml schema

. Validate that the landing page includes a “service” link to API Definition

. Validate that the landing page includes a “conformance” link to the conformance class document

. Validate that the landing page includes a “data” link to the WFS contents.

====== d) References:
Requirement 2

===== A.4.2.3 OpenAPI Document Retrieval

Note: The URI for the API definition is provided through the landing page.  However, that does not mean that the API definition resides on the same server as the landing page.  Test clients should be prepared for a WFS 3.0 implementation which is distributed across multiple servers.

====== a) Test Purpose:
Validate that the API Definition document can be retrieved from the expected location.

====== b) Pre-conditions:

* A URL to the server hosting the API Definition document is known.

* The test client can authenticate to the server.

* The test client has sufficient privileges to assess the API Definition document.

====== c) Test Method:

. Issue an HTTP GET request to the URL {server}/api

. Validate that a document was returned with a status code 200

. Validate the contents of the returned document using test A.4.2.4

====== d) References:
Requirements 3 and 4

===== A.4.2.4 API Definition Validation

====== a) Test Purpose:
Validate that the API Definition page complies with the require structure and contents.

====== b) Pre-conditions:

* The API Definition document has been retrieved from the server

====== c) Test Method:

. Validate the API Definition document against the OpenAPI 3.0 schema

. Identify the Test Points as described in test A.4.3

. Process the API Definition document as described in test A.4.4

====== d) References:
Requirement 4

==== A.4.3 Identify the Test Points

Identification of the test points is a pre-condition to performing a compliance test.  Thisprocess starts with A.4.3.1.

===== A.4.3.1 Identify Test Points:

====== a) Purpose:
To identify the test points associated with each Path in the OpenAPI document

====== b) Pre-conditions:

*   An OpenAPI document has been obtained
*   A list of URLs for the servers to be included in the compliance test has been provided
*   A list of the paths specified in the WFS 3.0 specification

====== c) Method:

FOR EACH paths property in the OpenAPI document
    If the path name is one of those specified in the WFS 3.0 specification
        Retrieve the Server URIs using A.4.3.2.
        FOR EACH Server URI
            Concatenate the Server URI with the path name to form a test point.
            Add that test point to the list.

====== d) References:
None

===== A.4.3.2 Identify Server URIs:

====== a) Purpose:
To identify all server URIs applicable to an OpenAPI Operation Object

====== b) Pre-conditions:

*   Server Objects from the root level of the OpenAPI document have been obtained
*   A Path Item Object has been retrieved
*   An Operation Object has been retrieved
*   The Operation Object is associated with the Path Item Object
*   A list of URLs for the servers to be included in the compliance test has been provided

====== c) Method:

1) Identify the Server Objects which are in-scope for this operation

 - IF Server Objects are defined at the Operation level, then those and only those Server Objects apply to that Operation.

 - IF Server Objects are defined at the Path Item level, then those and only those Server Objects apply to that Path Item.

 - IF Server Objects are not defined at the Operation level, then the Server Objects defined for the parent Path Item apply to that Operation.

 - IF Server Objects are not defined at the Path Item level, then the Server Objects defined for the root level apply to that Path.

 - IF no Server Objects are defined at the root level, then the default server object is assumed as described in the OpenAPI specification.

2) Process each Server Object using A.4.3.3.

3) Delete any Server URI which does not reference a server on the list of servers to test.

====== d) References:
None

===== A.4.3.3 Process Server Object:

====== a) Purpose:
To expand the contents of a Server Object into a set of absolute URIs.

====== b) Pre-conditions:

*   A Server Object has been retrieved

====== c) Method:

Processing the Server Object results in a set of absolute URIs.  This set contains all of the URIs that can be created given the URI template and variables defined in that Server Object.

. If there are no variables in the URI template, then add the URI to the return set.

. For each variable in the URI template which does not have an enumerated set of valid values:
    - generate a URI using the default value,
    - add this URI to the return set,
    - flag this URI as non-exhaustive
. For each variable in the URI template which has an enumerated set of valid values:
    - generate a URI for each value in the enumerated set,
    - add each generated URI to the return set.

. Perform this processing in an iterative manner so that there is a unique URI for all possible combinations of enumerated and default values.

. Convert all relative URIs to absolute URIs by rooting them on the URI to the server hosting the OpenAPI document.

====== d) References:
None

==== A.4.4 Processing the OpenAPI Document

===== A.4.4.1 Validate /api path

====== a) Test Purpose:
Validate API definition provided through the /api path it the athoritative definition of this API.  Validate that this resource exists at the expected location and that it complies with the appropirate schema. 

====== b) Pre-conditions:
* A URL to the server hosting the API definition document is known

====== c) Test Method:

. Issue an HTTP GET request to the URL {server}/api
 
. Validate that a document was returned with a status code of 200
 
. Validate the returned document against the OpenAPI 3.0 schema

====== d) References:
Requirement 4

===== A.4.4.2 Validate Conformance Operation

====== a) Test Purpose:
Validate that Conformance Operation behaves as required.

====== b) Pre-conditions:

* Path = /conformance

====== c) Test Method:

DO FOR each /conformance test point

. Issue an HTTP GET request using the test point URI

. Go to test A.4.4.3.

====== d) References:
Requirement 5

===== A.4.4.3 Validate Conformance Operation Response

====== a) Test Purpose:
Validate the Response to the Conformance Operation.

====== b) Pre-conditions:

* Path = /conformance

* A Conformance document has been retrieved

====== c) Test Method:

. Validate the retrieved document against the classes.yaml schema.

. Record all reported compliance classes and associate that list with the test point. This information will be used in latter tests.

====== d) References:
Requirement 6

===== A.4.4.4 Validate the Feature Collections Metadata Operation

====== a) Test Purpose:
Validate that the Feature Collections Metadata Operation behaves as required

====== b) Pre-conditions:

* Path = /collections

====== c) Test Method:

DO FOR each /collections test point

 - Issue an HTTP GET request using the test point
URI

 - Go to test A.4.4.5

====== d) References:
Requirement 9

===== A.4.4.5 Validate the Feature Collections Metadata Operation Response

====== a) Test Purpose:
Validate that response to the Feature Collection Metadata Operation.

====== b) Pre-conditions:

* A Feature Collection Metadata document has been
retrieved

====== c) Test Method:

. Validate the retrieved document against the content.yaml schema.

. Validate that the retrieved document includes links for:

 - Itself

 - Alternate encodings of this document in every other media type as identified by the compliance classes for this server.

. Validate that each link includes a rel and type parameter

. Validate that the returned document includes a collections property for each collection in the dataset.

. For each collections property, validate the metadata for that collection using test A.4.4.6

====== d) References:
Requirements 10, 11, and 12

===== A.4.4.6 Validate a Collections Metadata document

====== a) Test Purpose:
Validate a Collections Metadata document.

====== b) Pre-conditions:

* A Collection metadata document has been retrieved.

====== c) Test Method:

. Validate the collection metadata against the collectionInfo.yaml schema

. Validate that the collection metadata document includes links to the collection for each supported media type as identified by the compliance classes for this server.

. Validate that each link includes a rel and type parameter

. Validate the extent property if it is provided

. Retrieve the collection using the id property and test A.4.4.7.

====== d) References:
Requirement 12, 13, 14

===== A.4.4.7 Validate the Feature Collection Metadata Operation

====== a) Test Purpose:
Validate that the Feature Collection Metadata Operation behaves as required

====== b) Pre-conditions:

* A feature collection name is provided by test A.4.4.6

* Path = /collections/{collectionId}

====== c) Test Method:

DO FOR each /collections{collectionId} test point

 - Issue an HTTP GET request using the test point URI

 - Go to test A.4.4.8

====== d) References:
Requirement 15

===== A.4.4.8 Validate the Feature Collection Metadata Operation Response

====== a) Test Purpose:
Validate that response to the Feature Collection Metadata Operation.

====== b) Pre-conditions:

* A Feature Collection Metadata document has been
retrieved

====== c) Test Method:

. Validate the retrieved document against the collectionInfo.yaml schema.

. Validate that this is the same document as that processed in Test A.4.4.6

====== d) References:
Requirement 16

===== A.4.4.9 Validate the Get Features Operation

====== a) Test Purpose:
Validate that the Get Features Operation behaves as required.

====== b) Pre-conditions:

* A feature collection name is provided by test A.4.4.6

* Path = /collections/{collectionId}/items

====== c) Test Method:

DO FOR each /collections{collectionId}/items test point

 - Issue an HTTP GET request using the test point URI

 - Go to test A.4.4.10

====== d) References:
Requirement 17

===== A.4.4.10 Validate the Get Features Operation Response

====== a) Test Purpose:
Validate the Get Feature Operation Response.

====== b) Pre-conditions:

* A collection of Features has been retrieved

====== c) Test Method:

. Validate the structure of the response as follows:

    - For HTML use Human inspection

    - For GeoJSON use featureCollectionGeoJSON.yaml

    - For GML use featureCollectionGML.yaml

. Validate that the following links are included in the response document:

    - To itself

    - Alternate encodings of this document in every other media type as identified by the compliance classes for this server.

. Validate that each link includes a rel and type parameter.

. If a property timeStamp is included in the response, validate that it is close to the current time.

. If a property numberReturned is included in the response, validate that the number is equal to the number of features in the response.

. If a property numberMatched is included in the response, iteratively follow the next links until no next link is included and count the aggregated number of features returned in all responses during the iteration. Validate that the value is identical to the numberMatched stated in the initial response.

====== d) References:
Requirements 24, 25, 26, 27, 28 and 29

===== A.4.4.11 Limit Parameter

====== a) Test Purpose:
Validate the proper handling of the limit parameter.

====== b) Pre-conditions:

* Tests A.4.4.9 and A.4.4.10 have completed successfully.

====== c) Test Method:

. Verify that the OpenAPI document correctly describes the limit parameter for the Get Features operation.

. Repeat Test A.4.4.9 using different values for the limit parameter.

. For each execution of Test A.4.4.9, repeat Test A.4.4.10 to validate the results.

====== d) References:
Requirements 18 and 19

===== A.4.4.12 Bounding Box Parameter

====== a) Test Purpose:
Validate the proper handling of the bbox parameter.

====== b) Pre-conditions:

* Tests A.4.4.9 and A.4.4.10 have completed successfully.

====== c) Test Method:

. Verify that the OpenAPI document correctly describes the bbox parameter for the Get Features operation.

. Repeat Test A.4.4.9 using different values for the bbox parameter.  These should include test cases which cross the meridian, equator, 180^O^ longitude, and polar regions.

. For each execution of Test A.4.4.9, repeat Test A.4.4.10 to validate the results.

====== d) References:
Requirements 20 and 21

===== A.4.4.13 Time Parameter

====== a) Test Purpose:
Validate the proper handling of the time parameter.

====== b) Pre-conditions:

* Tests A.4.4.9 and A.4.4.10 have completed
successfully.

====== c) Test Method:

. Verify that the OpenAPI document correctly describes the time parameter for the Get Features operation.

. Repeat Test A.4.4.9 using different values for the time parameter.

. For each execution of Test A.4.4.9, repeat Test A.4.4.10 to validate the results.

====== d) References:
Requirements 22 and 23

===== A.4.4.14 Get Feature Operation

====== a) Test Purpose:
Validate that the Get Feature Operation behaves as required.

====== b) Pre-conditions:

* A feature collection name is provided by test A.4.4.6

* A feature identifier is provided by test A.4.4.10

* Path = /collections/{collectionId}/items/(featureId} where {featureId} = the feature identifier

====== c) Test Method:

DO FOR each /collections{collectionId}/items/{featureId} test point

    - Issue an HTTP GET request using the test point URI

    - Go to test A.4.4.15

====== d) References:
Requirement 30

===== A.4.4.15 Validate the Get Feature Operation Response

====== a) Test Purpose:
Validate the Get Feature Operation Response.

====== b) Pre-conditions:

*   The Feature has been retrieved from the server.

====== c) Test Method:

. Validate the structure of the response as follows:

    - For HTML use Human Inspection

    - For GeoJSON use featureGeoJSON.yaml

    - For GML use featureGML.yaml

. Validate that the following links are included in the response document:

    - To itself

    - To the Feature Collection which contains this Feature

    - Alternate encodings of this document in every other media type as identified by the compliance classes for this server.
    
. Validate that all links include the rel and type link parameters.

====== d) References:
Requirements 31 and 32
