[[xml_examples]]
[appendix]
:appendix-caption: Annex
== XML examples (Informative)

=== Overview

This annex includes examples of XML/GML responses to illustrate how the
OpenAPI fragments used to define the requirements for the
<<rc_core,Core requirements class>> are expressed in XML using the
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/xml/core.xsd[OGC API Features Core XML Schema].

=== A landing page

[source,XML]
----
include::../xml/examples/LandingPage.xml[]
----

=== Conformance declaration

This server conforms to the recommended requirements classes, plus the GML Simple Features Profile, Level 0.

[source,XML]
----
include::../xml/examples/ConformsTo.xml[]
----

=== Feature collections

This service offers three feature collections (airport facilities, roads, inland water areas).

[source,XML]
----
include::../xml/examples/Collections.xml[]
----

=== Feature collection

Only the information for the selected feature collection (roads) is included in the response.

[source,XML]
----
include::../xml/examples/Collection.xml[]
----

=== Features

This response contains 2 features of the airport facilities collection and has a link to the next features.

[source,XML]
----
include::../xml/examples/FeatureCollection.xml[]
----
