[appendix]
= Annex A: Abstract Test Suite (Normative) +

CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/46[ISSUE 46] +
OpenAPI Validation

== A.1: Overview +
WFS 3.0 is a highly modular standard.  One result of this is that almost everything is optional. +
 1) Are the advertised capabilities compliant with the WFS 3.0 standard? +
 2) Does the service implement those capabilities as advertised? +

This abstract Test Suite takes a follow-your-nose approach to testing compliance.  Starting with a landing page, the entire resource suite is explored by following URLs.  No capabilities are tested unless they are first identified by another resource. +
 +
*Conventions:* +
Path templates are used throughout these test suites.  Path templating refers to the usage of curly braces ({}) to mark a section of a URL path as replaceable using path parameters.  The terms used to describe portions of these templates are based on the URL syntax described in RFC 3986. +
 - scheme: http | https +
 - authority: DNS name of the server with optional port number +
 - path: The slash delimited identifier for a resource on the server +
 - query: query parameters following the "?" character +
 - fragment: identifies an element within the resource. Preceded by the "\#" character +

== A.2: Requirements Trace Matrix +
----
Requirement 1: API Landing Page Operation
The server SHALL support the HTTP GET operation at the path /.
Tests: A.1.n
----
----
Requirement 2: API Landing Page Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
The content of that response SHALL be based upon the OpenAPI 3.0 schema root.yaml and include at least links to the following resources:
    /api (relation type 'service')
    /conformance (relation type 'conformance')
    /collections (relation type 'data')
Tests: A.1.n
----
----
Requirement n: API Definition Operation (derived)
The server SHALL support the HTTP GET operation at the path /api.
Tests: A.1.n
----
----
Requirement 3: API Definition Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
The server SHALL return an API definition document.
Tests: A.1.n
----
----
Requirement 4: Conformance Class Operation
The server SHALL support the HTTP GET operation at the path /conformance.
Tests: A.1.n
----
----
Requirement 5: Conformance Class Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
The content of that response SHALL be based upon the OpenAPI 3.0 schema req-classes.yaml and list all WFS 3.0 requirements classes that the server conforms to.
Tests: A.1.n
----
----
Requirement 6: HTTP 1.1
The server SHALL conform to HTTP 1.1.
Tests: A.1.n
----
----
Requirement 7: Coordinate Reference Systems
Unless the client explicitly requests a different coordinate reference system, all spatial geometries SHALL be in the coordinate reference system http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS84 longitude/latitude).l.adoc[]
Tests: A.1.n
----
----
Requirement n: Feature Collections Metadata Operation (derived)
The server SHALL support the HTTP GET operation at the path /collections.
Tests: A.1.n
----
----
Requirement 8: Feature Collections Metadata Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
The content of that response SHALL be based upon the OpenAPI 3.0 schema content.yaml.
Tests: A.1.n
----
----
Requirement 9: Feature Collections Metadata Links
A 200-response SHALL include the following links in the links property of the response:
    a link to this response document (relation: self),
    a link to the response document in every other media type supported by the server (relation: alternate).
All links SHALL include the rel and type link parameters.
Tests: A.1.n
----
----
Requirement 10: Feature Collections Metadata Items
For each feature collection in this distribution of the dataset, an item SHALL be provided in the property collections.
Tests: A.1.n
----
----
Requirement 11: Feature Collections Metadata Items Links
For each feature collection in this distribution of the dataset, the links property of the collection SHALL include an item for each supported encoding with a link to the collection resource (relation: item).
All links SHALL include the rel and type properties.
Tests: A.1.n
----
----
Requirement 12: Feature Collections Metadata Extent
For each feature collection, the extent property, if provided, SHALL be a bounding box that includes all spatial and temporal geometries in this collection.
If a feature has multiple properties with spatial or temporal information, it is the decision of the server whether only a single spatial or temporal geometry property is used to determine the extent or all relevant geometries.
Tests: A.1.n
----
----
Requirement 13: Feature Collection Metadta Operation
The server SHALL support the HTTP GET operation at the path /collections/{name}.
name is the property of the same name in the feature collections metadata.
Tests: A.1.n
----
----
Requirement 14: Feature Collection Metadta Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
The content of that response SHALL be the same as the content for this feature collection in the /collections response.
Tests: A.1.n
----
----
Requirement 15: Feature Collection Operation
For every feature collection identified in the metadata about the feature collection (path /), the server SHALL support the HTTP GET operation at the path /collections/{name}/items.
name is the property of the same name in the feature collections metadata.
Tests: A.1.n
----
----
Requirement 16: Feature Collection Operation Limit Parameter
Each feature collection operation SHALL support a parameter limit with the following characteristics (using an OpenAPI Specification 3.0 fragment):
Tests: A.1.n
----
----
Requirement 17: Feature Collection Operation Limit Parameter Response
The response SHALL not contain more features than specified by the optional limit parameter. If the API definition specifies a maximum value for limit parameter, the response SHALL not contain more features than this maximum value.
Only items are counted that are on the first level of the collection. Any nested objects contained within the explicitly requested items SHALL not be counted.
Tests: A.1.n
----
----
Requirement 18: Feature Collection Operation BoundingBox Parameter
Each feature collection operation SHALL support a parameter bbox with the following characteristics (using an OpenAPI Specification 3.0 fragment):
Tests: A.1.n
----
----
Requirement 19: Feature Collection Operation BoundingBox Parameter Response
Only features that have a spatial geometry that intersects the bounding box SHALL be part of the result set, if the bbox parameter is provided.
The bounding box is provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (elevation or depth):
    Lower left corner, coordinate axis 1
    Lower left corner, coordinate axis 2
    Lower left corner, coordinate axis 3 (optional)
    Upper right corner, coordinate axis 1
    Upper right corner, coordinate axis 2
    Upper right corner, coordinate axis 3 (optional)
The coordinate reference system of the values SHALL be interpreted as WGS84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter bbox-crs.
Tests: A.1.n
----
----
Requirement 20: Feature Collection Operation Time Parameter 
Each feature collection operation SHALL support a parameter time with the following characteristics (using an OpenAPI Specification 3.0 fragment):
Tests: A.1.n
----
----
Requirement 21: Feature Collection Operation Time Parameter Response
Only features that have a temporal geometry that intersects the timestamp or time period SHALL be part of the result set, if the time parameter is provided.
The temporal information is either a date-time or a period string that adheres to RFC3339.
If a feature has multiple temporal properties, it is the decision of the server whether only a single temporal property is used to determine the extent or all relevant temporal properties.
Tests: A.1.n
----
----
Requirement 22: Feature Collection Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
Tests: A.1.n
----
----
Requirement 23: Feature Collection Response Links
A 200-response SHALL include the following links:
    a link to this response document (relation: self),
    a link to the response document in every other media type supported by the service (relation: alternate).
Tests: A.1.n
----
----
Requirement 24: Feature Collection Response Links Parameters
All links SHALL include the rel and type link parameters.
Tests: A.1.n
----
----
Requirement 25: Feature Operation
For every feature in a feature collection (path /collections/{name}/items), the service SHALL support the HTTP GET operation at the path /collections/{name}/items/{id}.
name is the property of the same name in the feature collection metadata. id is a local identifier of the feature.
Tests: A.1.n
----
----
Requirement 26: Feature Opearation Response
A successful execution of the operation SHALL be reported as a response with a HTTP status code 200.
Tests: A.1.n
----
----
Requirement 27: Feature Operation Response Links
A 200-response SHALL include the following links in the response:
    a link to the response document (relation: self),
    a link to the response document in every other media type supported by the service (relation: alternate), and
    a link to the feature collection that contains this feature (relation: collection).
All links SHALL include the rel and type link parameters.
Tests: A.1.n
----
----
Requirement 9: HTML Extension
include::requirements/requirements_class_html.adoc[]
Tests: A.1.n
----
----
Requirement 10: OpenAPI 3.0
Description:
include::requirements/requirements_class_oas30.adoc[]
Tests: A.1.n
----

== Conformance Classes:
Core - These are the requirements that all implementations must meet
HTML
GeoJSON
Geography Markup Language (GML) Simple Features Profile, Level 0
Geography Markup Language (GML) Simple Features Profile, Level 2
OpenAPI specification 3.0

== Paths
/ - Landing Page
/api - location of the API definition (GET only)
/conformance - Conformance statements (GET only) - returns a list of the URIs for conformance classes
/collections - Dataset distribution Metadata (GET only)
/collections/{collection-name} - returns the metadata for the feature collection where the name property == collection-nqme.
/collections/{collection-name}/items - the features in the collection (GET only)
/collections/{collection-name}/items/{feature-id} - a specific feature (GET only)

Parameters:
bbox
time
limit
Feature Properties filtering

== A.3: Abstract Tests +
WFS 3.0 is a highly modular standard.  One result of this is that almost everything is optional. +
 1) You are testing an API, not a service. +
 2) There may be a large number of servers exposed through the API. +
 3) Specific testable capabilities are defined in terms of a server URI and a path. +
 4) Every possible server URI / path combination must be evaluated. +

The WFS 3.0 Compliance test is performed in three phases:
 1) Crawl the OpenAPI document to identify all testable capabilities. +
 2) Validate that the advertised capabilities are compliant with the WFS 3.0 standard. +
 3) Validate that the servers implement those capabilities as advertised. +

=== A.3.1: Core Test +
*Test Purpose:* The core test which drives all other testing +
*Pre-conditions:* Tester is is aware of the root path to the API +
*References:* +
*Discussion:* +
*Variables:* +
  {Root_URL} the root URL for the service +
*Test Method:* +
  1) Retrieve the API Description document from {Root_URL}/api +
  2) Process the API Description document based on the API standard used +
     a) For OpenAPI Version 3.x use test A.3.2 +
  3) Report results of the tests. +

=== A.3.2: OpenAPI Core Test +
Test Purpose: Validate WFS 3.0 compliance based on the OpenAPI description of the Service. +
Pre-conditions: Tester has retrieved an API Description document. +
References: +
Discussion: +
Variables:  +
  {Root_URL} the root URL for the service +
  {API_Description} the API Description document +
  {Server_Object} metadata which describes a service +
Test Method: +
 1) Validate that the API Description document complies with the OpenAPI standard. +
 2) Retrieve each of the security controls from {API_Description}/security +
 3) IF there are security controls which were not used to retrieve the API Description, retrieve the API Description using the most restrictive controls specified.  All further access to the service will be preformed using these controls. +
 4) Count the number of entries in {API_Description}/servers +
    (ISSUE: What do we do if there is more than one?) +
 5) Retrieve the first Server Object from {API_Description}/servers +
     a) Retrieve the /{Server_Object}/url value.  +
     b) Set {Root_URL} to this value +
     (ISSUE: what do we do with multiple server URLs?) +
 6) Retrieve all Components Objects from {API_Description}/components and save for latter use. +
 7) Retrieve all Tag Objects from {API_Description}/tags and save for latter use. +
 8) Process each element in {API_Description}/paths using test A.3.3. +

=== A.3.3: OpenAPI Paths +
Test Purpose: Validate WFS 3.0 compliance based on the OpenAPI description of the service operations. +
Pre-conditions: Tester has retrieved and processed the top level of an OpenAPI document. +
References: +
Discussion: The /paths element in the OpenAPI document contains a sequence of Paths Objects.  Each Paths Object associates a path name with its' metadata, a Path Item Object.  The URL for a path is formed by concatenating the root URL for the server (from the Server Object) and the path name. +
Variables:  +
  {API_Description} the API Description document +
  {path} a URL path identifying a resource +
Test Method: +
  1) Retrieve the entry for {API_Description}/paths/Conformance +
  2) Validate the Conformance Entry using test A.*.* +
  3) Extract the conformance classes from the Conformance Entry and save for latter use. +
  4) FOR EACH entry in {API_Description}/paths +
     If {API_Description}/paths/{path} is addressed by the WFS 3.0 standard +
        THEN Validate the Path Item Object using test A.3.4 +
        ELSE ignore this path +
  5) Verify that all paths required by WFS 3.0 were included +

=== A.3.4: OpenAPI Path Items  +   
Test Purpose: Validate WFS 3.0 compliance for a single resource path based on the OpenAPI description of that path. +
Pre-conditions: Tester has extracted a Path Item Object from an OpenAPI document. +
References: +
Discussion: This test validates the metadata associated with a single resource path. +
Variables: +
  {path} the resource path corresponding to this Path Item (passed from A.3.3) +
  {Path_Item} the Path Item Object +
  {Server_Object} metadata which describes a service +
  {Root_URL} the root URL for the service +
Test Method: +
  1) Count the number of entries in {Path_Item}/servers +
     (ISSUE: What do we do if there is more than one?) +
  2) Retrieve the first Server Object from {Path_Item}/servers +
     a) Retrieve the /{Server_Object}/url value.  +
     b) Set {Root_URL} to this value +
     (Note: The url may contain variables (using the {var} construct).  The variable values are defined in the {Server_Object}/variables element.) +
     (ISSUE: what do we do with multiple server URLs?) +
  3) Retrieve the parameters from {Path_Item}/parameters.  Save for latter use. +
  5) Validate the operations described by this Path Item: +
      DO CASE OF {path} equals: +
      "/api" +
          Retrieve Operation Object from {Path_Item}/get +
          Perform Test A.3.5 using {Operation_Object} +
      "/conformance" +
          Retrieve Operation Object from {Path_Item}/get +
          Perform Test A.3.6 using {Operation_Object} +
      "/collections" +
          Retrieve Operation Object from {Path_Item}/get +
          Perform test A.3.7 using {Operaton_Object} +
      "other"  +
          Ignore +

=== A.3.5 OpenAPI Description +
Test Purpose: Validate that the service provides an API definition page on the required path +
Pre-conditions: Tester is is aware of the root path to the Service +
References: +
  Requirement R1 +
Discussion: +
    This operation is usually where the client and server initially authenticate their identities to each other.  Intermediate challenges and responses in support of authentication do not invalidate the results of this test. +
Variables: +
  {Root_URL} the root URL for the service +
Test Method: +
  1) Issue a get request on {Root_URL}/api +
     i) Accept header is set to ????? +
  2) Receive an API definition document in response to the get request +
  3) Validates that the API definition document complies with OpenAPI (should reference the OpenAPI test) +

=== A.3.6 Conformance Report
Test Purpose: Validate that the service provides a conformance report on the required path +
Pre-conditions: Tester is is aware of the root path to the Service +
References: +
  Requirement R5 +
Discussion: +
Variables: +
  {Root_URL} the root URL for the service +
Test Method: +
  1) Issue a get request on {scheme}://{authority}/conformance +
    i) Accept header is set to ????? +
  2) Receive an API Conformance Report document in response to the get request +
  3) Validates the Conformance Report document against the schema defined in the WFS 3.0 standard +
  4) Save the list of conformance classes from the conformsTo element for use latter. +
 +
=== A.3.7: OpenAPI Get Collections Test +
Test Purpose: Validate that the service provides valid Feature Collections metadata on the required path +
Pre-conditions: Tester is is aware of the root path to the Service +
References: +
  Requirement +
Discussion: +
Variables: +
  {Root_URL} the root URL for the service +
Test Method: +
  1) Issue a get request on {Root_URL}/collections +
     i) Accept header is set to ????? +
  2) Receive a Feature Collection Metadata document in response to the get request +
  3) Validate the Feature Collection Metadata document schema through test A.3.7.1 +
  4) Validate the contents of the Feature Collection Metadata document through test A.3.7.2 +
  5) Save a list of all of the Feature Collections for use latter. +
  6) Validate the resources described by the Feature Collection Metadata using Test A.3.8. +
 +
==== A.3.7.1: Feature Collection Metadata Schema Validation +
Test Purpose: Validate the structure of the Feature Collection metadata + 
Pre-conditions: A Feature Collection Metadata resouce has been received +
References: +
  Requirement +
Discussion: +
Variables:  +
  {Collection_Metadata} the Feature Collection Metadata resource +
Test Method: +
  1) Validate the Feature Collection Metadata document against the schema defined in content.yaml +
 +
==== A.3.7.2: Feature Collection Metadata Content Validation +
Test Purpose: Validate that the Feature Collection Metadata content is correct and complete +
Pre-conditions: A Feature Collection Metadata document has been received +
References: +
  Requirement +
Discussion: +
Variables: +
  {Collection_Metadata} the Feature Collection Metadata resource +
Test Method: +
  1) Validate the links property of the Feature Collection Metadata through test A.3.7.2.1 +
  2) Validate the collections property of the Feature Collection Metadata through test A.3.7.2.2 +
 +
===== A.3.7.2.1: Feature Collection Metadata Links Property Validation +
Test Purpose: Validate that the Links property of the Feature Collection Metadata content is correct and complete +
Pre-conditions: A Feature Collection Metadata document has been received +
References: +
  Requirement +
Discussion: +
Variables: +
  {Collection_Metadata} the Feature Collection Metadata resource +
Test Method: +
  1) Validate the links property includes a valid link to the Feature Collection Metadata document on the server +
  2) Validate the links property includes valid links to Feature Collection Metadata documents in every media type offered by the server +
  3) For each Feature Collection and each media type offered by the server, validate that the links property includes a valid link to that resource. +
  4) Validate the links property includes valid links to API Definition documents in every media type offered by the server. +
 +
===== A.3.7.2.2 Feature Collection Metadata Collections Property Validation +
Test Purpose: Validate that the Collections property of the Feature Collection Metadata content is correct and complete +
Pre-conditions: A Feature Collection Metadata document has been received +
References: +
  Requirement +
Discussion: +
Variables:  +
  {Collection_Metadata} the Feature Collection Metadata resource +
Test Method: +
  1) Validate that there is a collections property for every Feature Collection hosted on the server. Use the list of Feature Collections saved in Test A.3.7. +
  2) Validate that each Collections property includes a links property +
  3) For each Collections property; validate that the links property includes entries for each encoding supported by the server. The list of encodings can be build from the list of conformance classes saved in Test A.3.6. +
  4) For each links property of each Collections property; validate that each entry in the links property resolves to the proper Feature Collection and encoding. (Validate by matching Feature names) +
  5) Validate that each collections property includes a valid extent property +
  6) For each Feature Collection, validate that all Features contained in that collection fall within the bounding box defined by the extent property. +
  + 
=== A.3.8 Feature Collections
* Test Purpose: Validate that the service provides Feature Collections on the mandated paths
* Pre-conditions: Tester possesses Feature Collection metadata which provides paths to each Feature Collection
* References:
* Discussion:
* Variables: 
  {Collection_Metadata} the Feature Collection Metadata resource
  {CollectionId} the collection identifier from {Collection_Metadata}/name
* Test Method:
  For each Feature Collection identified in the Feature Collection metadata
    1) Issue a get request on {RootURL}/collections/{CollectionId}/items
       i) Accept header is set to ?????
    2) Receive an Feature Collection in response to the get request
    3) Validate the expected Features were returned given the default values of the query parameters.
    4) Re-issue the get request with non-default values for the query parameters.
    5) Validate the expected Features were returned given the non-default values of the query parameters.
    6) Client validates the content of the returned feature set using test A.3.8.1
 e) Notes:
    Query parameters are:
    1) count: the maximum number of Features returned at one time (R12 & R13).
    2) bbox: only Features which fall within or intersect the boundaries of this box should be returned (R14 & R15)  

==== A.3.8.1: Feature Result Set
* Test Purpose: Validate that the returned Features are complete and correct.
* Pre-conditions: A Feature Collection has been received
* References:
* Discussion:
* Variables: 
  {Collection_Metadata} the Feature Collection Metadata resource
  {CollectionId} the collection identifier from {Collection_Metadata}/name
* Test Method:
  For each Feature in the Feature Collection
  1) Validate that the links property is present
  2) Validate that the links property includes an entry for each media type supported by the service.
  3) Validate that each entry in the links property includes the rel and type parameters
  4) Validate that all of the entries in the links property resolve to representations of the Feature in the appropriate media type.

=== A.3.9: Features
* Test Purpose:  Validate that individual Features can be retrieved
* Pre-conditions: A Feature Collection has been received
* References:
* Discussion:
* Variables: 
  {Collection_Metadata} the Feature Collection Metadata resource
  {CollectionId} the collection identifier from {Collection_Metadata}/name
  {id} 
* Test Method:
  For each Feature in the Feature Collection:
    1) Issue a get request on {RootURL}/collections/{collectionId}/{id}
       a) Accept header is set to ?????
    2) Validate that a Feature document is returned.
    3) Validate that the name property of the Feature matches the {id} 
    4) Validate the Feature using test A.3.9.1

=== A.3.9.1: Feature Validation
* Test Purpose: Validate the contents of a Feature
* Pre-conditions: A Feature has been retrieved
* References:
* Discussion:
* Variables: 
  {Collection_Metadata} the Feature Collection Metadata resource
  {CollectionId} the collection identifier from {Collection_Metadata}/name
* Test Method:
  1) Validate that the links property is present
  2) Validate that each entry in the links property includes the rel and type parameters
  3) For every media type supported by the server:
     a) Validate that there is a link entry for the Feature (self) 
     b) Validate that the entry resolves to representations of the Feature in the appropriate media type.
  4) Validate that the links property includes an entry for the Feature Collection.

=== A.3.8: OpenAPI Parameter Test
Parameter Metadata:
1) Retrieve the parameter name from {Parameter_Object}/name
2) If the parameter is not defined in the WFS 3.0 standard (ISSUE: do we continue validation or skip this parameter)
3) IF the parameter is required by the WFS 3.0 standard, verify that {Parameter_Object}/required == TRUE
4) IF {Parameter_Object}/required == TRUE, verify that the parameter is present
5) IF the parameter is present, verify that the parameter is in the correct location as specified in {Parameter_Object}/in (valid values are query, header, path, or cookie).
6) IF the parameter has an empty value, verify that {Parmeter_Object}/allowEmptyValue is TRUE.

== A.2.3 HTTP 1.1
 a) Test Purpose: Validate that the service supports and conforms to HTTP 1.1
 b) Pre-conditions: Client is aware of the root path to the service
 c) Test Method: TBD - it is unknown if a conformance test for HTTP 1.1 exists.
 d) References: 
     Requirements: R4
----
----
A.2.7 HTML Extension
 a) Test Purpose: Validate that HTML encoding is supported property
 b) Pre-conditions: 
    1) A request has been issued with the Accepts header set to "text/html"
    2) A "200" response has been received with the Content-Type header set to "text/html"
 c) Test Method:
    1) Client validates that HTML is one of the advertised media types supported by the server.
    2) Client validates that the received payload includes <needs clarification in the spec>
 d) References: 
     Requirements: R22, R23
----
----
A.2.8 GeoJSON Extension
 a) Test Purpose: Validate that the GeoJSON extension is supported property
 b) Pre-conditions: Client has determined that the server supports GeoJSON
 c) Test Method:
     1) Validate handling of Features and Feature Collections using test A.2.8.1
     2) Validate handling of all other "200" responses using test A.2.8.2 
 d) References: 
     Requirements: R24, R25
     Tests: A.2.8.1, A.2.8.2
----
----
A.2.8.1 GeoJSON Response Validation
 a) Test Purpose: Validate that GeoJSON responses are supported property
 b) Pre-conditions: A Feature or Feature Collection response has been received
 c) Test Method:
     1) Validate that the request had the accepts header set to "application/geo+json"
     2) Validate that the content-type header of the response is set to "application/geo+json"
     3) Validate that the response complies with the GeoJSON standard.
 d) References: 
     Requirements: R24, R25
----
----
A.2.8.2 JSON Response Validation
 a) Test Purpose: Validate that JSON responses are supported property
 b) Pre-conditions: A response has been received which is not a Feature or Feature Collection
 c) Test Method:
     1) Validate that the request had the accepts header set to "application/json" or "application/geo+json"
     2) Validate that the content-type header of the response is set to "application/json"
     3) Validate that the response complies with the JSON standard.
 d) References: 
     Requirements: R24, R25
----
----
A.2.9 GML Simple Features Level 0 Extension
 a) Test Purpose: Validate that the GML Simple Features Level 0 extension is supported property
 b) Pre-conditions: Client has determined that the server supports GML SF Level 0
 c) Test Method:
     1) Validate handling of Features and Feature Collections using test A.2.9.1
     2) Validate handling of all other "200" responses using test A.2.9.2 
 d) References: 
     Requirements: R26, R27
     Tests: A.2.9.1, A.2.9.2
----
----
A.2.8.1 GeoJSON Response Validation
 a) Test Purpose: Validate that GeoJSON responses are supported property
 b) Pre-conditions: A Feature or Feature Collection response has been received
 c) Test Method:
     1) Validate that the request had the accepts header set to "application/geo+json"
     2) Validate that the content-type header of the response is set to "application/geo+json"
     3) Validate that the response complies with the GeoJSON standard.
 d) References: 
     Requirements: R24, R25
----
----
A.2.8.2 JSON Response Validation
 a) Test Purpose: Validate that JSON responses are supported property
 b) Pre-conditions: A response has been received which is not a Feature or Feature Collection
 c) Test Method:
     1) Validate that the request had the accepts header set to "application/json" or "application/geo+json"
     2) Validate that the content-type header of the response is set to "application/json"
     3) Validate that the response complies with the JSON standard.
 d) References: 
     Requirements: R24, R25
--------
A.2.8 GML Simple Features Level 2 Extension
 a) Test Purpose:
 b) Pre-conditions:
 c) Test Method:
 d) References: Requirement R8
----

----
A.2.10 OpenAPI 3.0 
 a) Test Purpose:
 b) Pre-conditions:
 c) Test Method:
 d) References: Requirement R10
----

