[[changes]]
[appendix]
:appendix-caption: Annex
== Changes to the previous versions of WFS (Informative)

CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/3[ISSUE 3] +
Annex B is meant as a discussion / explanation to the community that uses
WFS today. Maybe we should remove this from the document and make it a
separate document (e.g., part of the release notes)?

=== Overview

The previous versions of the WFS standard used a Remote-Procedure-Call-over-HTTP architectural style using XML for any payloads as it was state-of-the-art in the late 1990s and early 2000s, when WFS was originally designed.

This version 3.0 specifies a modernized service, that is better alignment with the current architecture of the Web. Key changes are:

* *Architecture*: WFS now supports and is consistent with HTTP and HTTPS. In previous versions, HTTP has been used mainly as a tunnel for WFS messages. In addition, the resources provided by the service include hypermedia controls in their representations to guide the user of a WFS.
* *Encodings*: Previous versions were strongly tied to XML (Capabilities documents, XML schemas, Filter Encoding expressions, GML encoding). This version has been written with HTML, JSON and XML as encodings in mind, because these are common encodings today, but no encoding is mandatory and other encodings may be used as well.
* *Reuse*: The use of WFS-specific resources or components has been minimized and, where available, existing industry-standards that are commonly used by developers are used instead. An example is the use of OpenAPI (the successor of Swagger) instead of OGC-specific "Capabilities" documents.
* *Schemas*: Previous versions required XML schemas for all feature types and valid XML documents. While the capability to support application schemas has been maintained, it is no longer mandatory that rigid schemas are provided and used for validation of feature data.
* *Modularization*: The WFS 2.0 standard, together with the Filter Encoding 2.0 standard, specifies a powerful, but complex service interface. In order to better support implementations that only need a relatively simple service or client, this version is modularized into multiple parts. This first part represents a simple interface to access spatial data that is sufficient for cases that do not require support for transactions, complex data structures, rich queries, custom coordinate reference systems, etc. Additional parts will specify extensions to this part to meet the needs of use cases that require such capabilities.
* *Security*: Built-in support for secured services using common security schemes

These changes align WFS with the <<SDWBP,W3C/OGC best practices for sharing Spatial Data on the Web>> and the general <<DWBP,W3C best practices for sharing Data on the Web>>.

As a result of this modernization, WFS 3.0 implementations are not backwards compatible with WFS 2.0 implementations per se. However, it has been a design goal to define WFS 3.0 in a way so that the WFS 3.0 interface can be mapped to an WFS 2.0 implementation - at least for the capabilities that were already in scope in WFS 2.0. WFS 3.0 is intended to be simpler and more modern, but still an evolution from the previous versions and their implementations.

The next sub-clauses in this Annex describe the following aspects:

* WFS as a RESTful service - the architectural design principles,
* how elements of a WFS 2.0 Capabilities document map to an OpenAPI definition, and
* how WFS 2.0 operations map to WFS 3.0 and vice versa.

=== WFS as a RESTful service

This version of WFS uses the REST architectural style that is that basis of many current Web APIs. Key characteristics include:

1. *URIs*:  Every URI designates exactly one resource.
2. *Addressability*:  All the interesting aspects of a service (e.g. features) are exposed as resources.
3. *Statelessness*:  Every HTTP request includes all necessary information for the server to fulfil the request without relying on previous requests.
4. *Representation*:  Each resource offered by the service has a representation that encodes useful information about the state of a resource.  For example, typical representations for feature resources, as defined in this standard, are GML, GeoJSON or HTML.
5. *Connectedness* : Resources will link to each other and alternate representations.
6. *Uniform interface*:  The server offers a uniform interface, using the HTTP verbs, for accessing and manipulating resources.
** *GET* to retrieve resources
** *POST* to create resources
** *PUT* to modify existing resources
** *DELETE* to remove resources
** *HEAD* to test for the existence of resources
** *OPTIONS* to get available options for a resource (e.g. which HTTP methods can be used)
+
NOTE: This part of WFS only specifies operations using GET.

7. *Safety and idempotence*:  HTTP methods are characterized as safe and/or idempotent and servers should be mindful when processing HTTP requests to not violate the safety and/or idempotence of the requested method.  Safe methods are methods that do not modify the representation of a resource and so their results can be safely cached.  Idempotent methods are methods that can be repeatedly processed but their effect will always be the same.  For example, whether a resource is deleted once or a dozen times the effect is still the same – the resource remains removed from the system.  The following table provides an overview of the safety and /or idempotence of each HTTP method used in the REST binding:

+
.Safety and Idempotence of HTTP methods
[width="90%", options="header"]
|===
|HTTP Method |Safe |Idempotent
|GET |YES |YES
|PUT |NO |YES
|POST |NO |NO
|DELETE |NO |YES
|HEAD |YES |YES
|OPTIONS |YES |YES
|===

+
.An unsafe implementation of GET
=====================================================================
An unsafe implementation of the GET method would be to use the GET method to delete resource from the server using a URL such as " GET /buildings/1013/delete".
=====================================================================

=== Mapping between OGC Capabilities and OpenAPI

NOTE: TODO

=== Mapping between WFS 2.0 operations and WFS 3.0

NOTE: TODO
