== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

NOTE: TODO +
Add link to the informative WFS Guide, once it is available.

=== dataset
selection of data, published or curated by a single agent, and available for access or download in one or more formats <<DCAT>>

=== distribution
represents an accessible form of a *dataset* <<DCAT>>

EXAMPLE: a downloadable file, an RSS feed or a web service that provides the data.

=== feature
abstraction of real world phenomena [ISO 19101-1:2014]

NOTE: If you are unfamiliar with the term 'feature', the explanations in
the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practice document>> may help,
in particular the section on
link:https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry[Spatial Things, Features and Geometry].

=== feature collection
a set of *features* from a *dataset*
