== Conformance
This standard defines a six requirements and conformance classes.

The standardization targets of all conformance classes are "web services".

The main requirements class is:

* <<rc_core,Core>>.

It specifies requirements that all WFS have to meet.

The "Core" does not mandate any encoding or format for representing features or
feature collections. Four requirements classes depend on the "Core"
and specify representations for these resources in commonly used encodings
for spatial data on the web:

* <<rc_html,HTML>>,
* <<rc_geojson,GeoJSON>>,
* <<rc_gmlsf0,Geography Markup Language (GML), Simple Features Profile, Level 0>>, and
* <<rc_gmlsf2,Geography Markup Language (GML), Simple Features Profile, Level 2>>.

None of these encodings is mandatory and an implementation of the "Core"
requirements class may also decide to use none of them, but to use another encoding
instead.

The "Core" does not mandate any encoding or format for the formal definition of
the API either. One option is the OpenAPI 3.0 specification and a requirements
class has been defined for this, which depends on the "Core":

* <<rc_oas30,OpenAPI specification 3.0>>.

Like with the feature encodings, an implementation of the "Core" requirements
class may also decide to use other representations of the API definition in
addition or instead of an OpenAPI 3.0 definition. Examples for alternative
API definitions: OpenAPI 2.0 (Swagger), future versions of the OpenAPI
specification or an OWS Common 2.0 capabilities document.

The "Core" is intended to be the minimal useful service interface for fine-grained
access to a spatial dataset.

Additional capabilities, for example, support for transactions, complex data
structures, rich queries, other coordinate reference systems,
subscription/notification, returning aggregated results, etc., may be
specified in future parts of WFS or as vendor-specific extensions.

NOTE: The general idea is that it should be possible to implement a single API
(e.g., have a single OpenAPI definition) that at the same time conforms to conformance classes from WFS 3.0 and from other OGC Web Service standards following a similar approach. In other words, the idea is not
to define standalone services, but more to define "building blocks" for
data APIs that supports spatial aspects.

Conformance with this standard shall be checked using all the relevant tests
specified in Annex A (normative) of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/9[ISSUE 9] +
Include a list of conformance classes met by the server somewhere? In the
OpenAPI document or in the root resource?
