== Requirements classes for encodings

////
for now, normative statements are often included inline. This will be re-factored later.
////

=== Overview

This clause specifies four pre-defined requirements classes for encodings to be
used in a WFS. These encodings are commonly used encodings for spatial data on
the web:

* <<rc_html,HTML>>
* <<rc_geojson,GeoJSON>>
* <<rc_gmlsf0,Geography Markup Language (GML), Simple Features Profile, Level 0>>
* <<rc_gmlsf2,Geography Markup Language (GML), Simple Features Profile, Level 2>>

None of these encodings is mandatory and an implementation of the <<rc_core,Core>>
requirements class may also decide to use none of them, but to use another encoding
instead.

The <<rc_core,Core>> requirements class includes recommendations to support
<<rec_html,HTML>> and <<rec_geojson,GeoJSON>> as encodings, where practical.
<<overview,Clause 6 (Overview)>> includes a discussion about recommended
encodings.

=== Requirement Class "HTML"

Geographic information that is only accessible in formats like GeoJSON or GML
has two issues:

* it is not discoverable using the most common mechanism for discovering information,
that is the search engines of the Web;
* it can not be viewed directly in a browser - additional tools are required to
view the data.

Therefore, sharing data on the Web should include publication in HTML. To be consistent
with the Web, it should be done in a way that enables users and search engines to
access all data.

This is discussed in detail in
link:https://www.w3.org/TR/sdw-bp/#indexable-by-search-engines[Best Practice 2: Make your spatial data indexable by search engines]
<<SDWBP>>. This standard therefore <<rec_html,recommends to support HTML as an encoding>>.

include::requirements/requirements_class_html.adoc[]

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/html/definition +

Every `200`-response of an operation of the server
SHALL support the media type `text/html`.
|===

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/html/content +

Every `200`-response of the server with the media type "text/html" SHALL be a
link:https://www.w3.org/TR/html5/[HTML 5 document] that includes the following
information in the HTML body:

* all information identified in the schemas of the
link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responseObject[Response Object]
in the HTML `<body/>`, and
* all links in HTML `<a/>` elements in the HTML `<body/>`.
|===

[width="90%",cols="2,6a"]
|===
|Recommendation {counter:rec-id} |/rec/html/schema-org +

In a `200`-response with the media type `text/html`, SHOULD include
<<schema.org,Schema.org>> annotations.
|===

=== Requirement Class "GeoJSON"

GeoJSON is a commonly used format that is simple to understand and well
supported by tools and software libraries. Since most Web developers are
comfortable with using a JSON-based format, supporting GeoJSON is recommended,
if the feature data can be represented in GeoJSON for the intended use.

include::requirements/requirements_class_geojson.adoc[]

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/geojson/definition +

`200`-responses of the server SHALL support the following media types:

* `application/geo+json` for feature collections and features, and
* `application/json` for all other resources.
|===

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/geojson/content +

Every `200`-response with the media type `application/geo+json` SHALL be

* a link:https://tools.ietf.org/html/rfc7946#section-3.3[GeoJSON FeatureCollection Object] for feature collections, and
* a link:https://tools.ietf.org/html/rfc7946#section-3.2[GeoJSON Feature Object] for features.

The links specified in the requirements `/req/core/fc-links` and
`/req/core/f-links` SHALL be added in a extension property
(foreign member) with the name `links`.
|===

Templates for the definition of the schemas for the GeoJSON responses in
OpenAPI definitions are available at
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/featureCollectionGeoJSON.yaml[featureCollectionGeoJSON.yaml] and
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/featureGeoJSON.yaml[featureGeoJSON.yaml].
These are generic schemas that do not include any application schema information about
specific feature types or their properties.

.A GeoJSON FeatureCollection Object response
=================
In the example below, only the first and tenth feature is shown. Coordinates are not shown.

[source,JSON]
----
{
  "type" : "FeatureCollection",
  "links" : [ {
    "href" : "http://data.example.com/collections/buildings/items/?f=json",
    "rel" : "self",
    "type" : "application/geo+json",
    "title" : "this document"
  }, {
    "href" : "http://data.example.com/collections/buildings/items/?f=html",
    "rel" : "alternate",
    "type" : "text/html",
    "title" : "this document as HTML"
  }, {
    "href" : "http://data.example.com/collections/buildings/items/?f=json&startIndex=10&limit=10",
    "rel" : "next",
    "type" : "application/geo+json",
    "title" : "next page"
  } ],
  "features" : [ {
    "type" : "Feature",
    "id" : "123",
    "geometry" : {
      "type" : "Polygon",
      "coordinates" : [ ... ]
    },
    "properties" : {
      "function" : "residential",
      "floors" : "2",
      "lastUpdate" : "2015-08-01T12:34:56Z"
    }
  }, { ...
  }, {
    "type" : "Feature",
    "id" : "132",
    "geometry" : {
      "type" : "Polygon",
      "coordinates" : [ ... ]
    },
    "properties" : {
      "function" : "public use",
      "floors" : "10",
      "lastUpdate" : "2013-12-03T10:15:37Z"
    }
  } ]
}
----
=================

.A GeoJSON Feature Object response
=================
In the example below, coordinates are not shown.

[source,JSON]
----
{
  "type" : "Feature",
  "links" : [ {
    "href" : "http://data.example.com/collections/buildings/items/123/?f=json",
    "rel" : "self",
    "type" : "application/geo+json",
    "title" : "this document"
  }, {
    "href" : "http://data.example.com/collections/buildings/items/123/?f=html",
    "rel" : "alternate",
    "type" : "text/html",
    "title" : "this document as HTML"
  }, {
    "href" : "http://data.example.com/collections/buildings/items",
    "rel" : "collection",
    "type" : "application/geo+json",
    "title" : "the collection document"
  } ],
  "id" : "123",
  "geometry" : {
    "type" : "Polygon",
    "coordinates" : [ ... ]
  },
  "properties" : {
    "function" : "residential",
    "floors" : "2",
    "lastUpdate" : "2015-08-01T12:34:56Z"
  }
}
----
=================

=== Requirement Class "Geography Markup Language (GML), Simple Features Profile, Level 0"

In addition to HTML and GeoJSON, a significant amount of feature data is
available in XML-based formats, notably GML. Therefore, this standard
specifies requirement classes for GML. The Simple Features Profile, Level 0, is
the simplest profile of GML and is typically supported by tools. It is restricted
to data with 2D geometries supported by most tools. In addition, the profile
is limited to features that can be stored in a tabular data structure.

include::requirements/requirements_class_gmlsf0.adoc[]

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/gmlsf0/definition +

`200`-responses of the server
SHALL support the following media types:

* `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` for feature collections and features,
* `application/xml` for all other resources.
|===

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/gmlsf0/content +

Every `200`-response with the media type `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` SHALL be

* a link:http://schemas.opengis.net/wfs/3.0/wfs-core.xsd[WFS 3.0 Core FeatureCollection Object] for feature collections, and
* a link:http://schemas.opengis.net/gml/3.2.1/feature.xsd[GML 3.2 Feature] for features.

Every feature SHALL conform to the <<GMLSF,GML Simple Features Profile, Level 0>>.
|===

NOTE: TODO +
The WFS 3.0 Core FeatureCollection Object has to be an XML schema element defined according to 8.4.2 Defining feature collections. +
Add statements how links are represented.

Templates for the definition of the schemas for the GML responses in OpenAPI
definitions are available at
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/featureCollectionGML.yaml[featureCollectionGML.yaml] and
link:https://raw.githubusercontent.com/opengeospatial/WFS_FES/master/core/openapi/schemas/featureGML.yaml[featureGML.yaml].
These are generic schemas that do not include any application schema information about
specific feature types or their properties.

=== Requirement Class "Geography Markup Language (GML), Simple Features Profile, Level 2"

The difference between this requirement class and the <<rc_gmlsf0,Level 0>>
requirements class is that non-spatial feature properties are not restricted to
atomic values (strings, numbers, etc.).

include::requirements/requirements_class_gmlsf2.adoc[]

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/gmlsf2/definition +

`200`-responses of the server
SHALL support the following media types:

* `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` for feature collections and features,
* `application/xml` for all other resources.
|===

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/gmlsf2/content +

Every `200`-response with the media type `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` SHALL be

* a link:http://schemas.opengis.net/wfs/3.0/wfs-core.xsd[WFS 3.0 Core FeatureCollection Object] for feature collections, and
* a link:http://schemas.opengis.net/gml/3.2.1/feature.xsd[GML 3.2 Feature] for features.

Every feature SHALL conform to the <<GMLSF,GML Simple Features Profile, Level 2>>.
|===
