== Terms, definitions and abbreviated terms

=== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

==== dataset
collection of data

NOTE: Published or curated by a single agent, and available for access or download in one or more serializations or formats. <<DCAT>>

NOTE: The use of 'collection' in the definition is broader than the use of the term collection in this specification. See the definition of <<_feature_collection,'feature collection'>>.

==== distribution
specific representation of a **dataset** <<DCAT>>

EXAMPLE: a downloadable file, an RSS feed or an API.

==== feature
abstraction of real world phenomena [ISO 19101-1:2014]

NOTE: More details about the term 'feature' may be found in the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practice>> in the section link:https://www.w3.org/TR/sdw-bp/#spatial-things-features-and-geometry['Spatial Things, Features and Geometry'].

[[_feature_collection]]
==== feature collection; collection
a set of **features** from a **dataset**

[[landing_page]]
==== landing page
**web resource** whose primary purpose is to contain a description of something else (<<urls-in-data,URLs in Data Primer>>)

NOTE: Landing pages often provide summaries or additional information about the thing that they describe. 

NOTE: The landing page of an OGC Web API serves as the root node of the API resource tree and provides the information needed to navigate all the resources exposed through the API.

[[ogc-webapi]]
==== OGC Web API
A **Web API** that implements one or more Conformance Classes from an OGC API Standard

[[resource-def]]
==== resource
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>)

NOTE: The term "resource", when used in the context of an OGC API standard, should be understood to mean a <<web-resource-def,web resource>> unless otherwise indicated.

[[webapi]]
==== Web API
API using an architectural style that is founded on the technologies of the Web <<DWBP>>

NOTE: link:https://www.w3.org/TR/dwbp/#APIHttpVerbs[Best Practice 24: Use Web Standards as the foundation of APIs] in the <<DWBP,W3C Data on the Web Best Practices>> provides more detail.

[[web-resource-def]]
==== web resource
a **resource** that is identified by a HTTP URI.

=== Abbreviated terms

API::
  Application Programming Interface
CORS::
  Cross-Origin Resource Sharing
CRS::
  Coordinate Reference System
HTTP::
  Hypertext Transfer Protocol
HTTPS::
  Hypertext Transfer Protocol Secure
IANA::
  Internet Assigned Numbers Authority
OGC::
  Open Geospatial Consortium
TRS::
    Temporal Coordinate Reference System
URI::
  Uniform Resource Identifier
YAML::
  YAML Ain't Markup Language
