== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== dataset
collection of data, published or curated by a single agent, and available for access or download in one or more formats [DCAT]

=== distribution
represents an accessible form of a *dataset* [DCAT]

EXAMPLE: a downloadable file, an RSS feed or a web service that provides the data.

=== feature
abstraction of real world phenomena [ISO 19101:2002, definition 4.11]

=== feature collection
a set of *features* from a *dataset*


CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/4[ISSUE 4] +
We need to make the document understandable to the developers that have no
geo/OGC background, too. What do we need to explain in this section and what
terms should we use in general?
