== Requirements Class "Core"

[[core-overview]]
=== Overview

include::requirements/requirements_class_core.adoc[]

A server that implements this requirements class provides access to the features in a link:https://www.w3.org/TR/vocab-dcat/#class-dataset[dataset].

NOTE: Other parts of this standard may define API extensions that support multiple datasets. The statement that the features are from "a dataset" is not meant to preclude such extensions. It just reflects that this document does not specify how the API publishes features or other spatial data from multiple datasets.

The entry point is a `Landing page` (path `/`).

NOTE: All paths (e.g., `/`) are relative. If the API covers other resources beyond those specified in this document, the landing page can also be, for example, a sub-resource of the base URL of the API.

The `Landing page` provides links to:

* the `API definition` (link relations `service-desc` and `service-doc`),

* the `Conformance declaration` (path `/conformance`, link relation `conformance`), and

* the `Collections` (path `/collections`, link relation `data`).

The `API definition` describes the capabilities of the server that can be used by clients to connect to the server or by development tools to support the implementation of servers and clients. Accessing the `API definition` using HTTP GET returns a description of the API. The API definition can be hosted on the API server(s) or a separate server.

The `Conformance declaration` states the conformance classes from standards or community specifications, identified by a URI, that the API conforms to. Clients can but are not required to use this information. Accessing the `Conformance declaration` using HTTP GET returns the list of URIs of conformance classes implemented by the server.

The data is organized into one or more collections. `Collections` provides information about and access to the collections.

This document specifies requirements only for collections consisting of features. That is, each collection considered by this document is a feature collection. Other OGC API standards may add requirements for other types of collections.

NOTE: To support the future use of datasets with items that are not features, the term "feature" has not been added in the names of the resource types or their paths.

This standard does not include any requirements about how the features in the dataset have to be aggregated into collections. A typical approach is to aggregate by feature type but any other approach that fits the dataset or the applications using this distribution may also be used.

Accessing `Collections` using HTTP GET returns a response that contains at least the list of collections. For each `Collection`, a link to the items in the collection (`Features`, path `/collections/{collectionId}/items`, link relation `items`) as well as key information about the collection. This information includes:

* A local identifier for the collection that is unique for the dataset;

* A list of coordinate reference systems in which geometries may be returned by the server: the first CRS is the default CRS (in the _Core_, the default is always WGS 84 with axis order longitude/latitude);

* An optional title and description for the collection;

* An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;

* An optional indicator about the type of the items in the collection (the default value, if the indicator is not provided, is 'feature').

The `Collection` resource is available at path `/collections/{collectionId}`, too, often with more details than included in the `Collections` response.

Each `Collection` that is a feature collection consists of features. This document only discusses the behavior of feature collections.

Each feature in a dataset is part of exactly one collection.

Accessing the `Features` using HTTP GET returns a document consisting of features in the collection. The features included in the response are determined by the server based on the query parameters of the request. To support access to larger collections without overloading the client, the API supports paged access with links to the next page, if more features are selected than the page size.

A `bbox` or `datetime` parameter may be used to select only a subset of the features in the collection (the features that are in the bounding box or time interval). The `bbox` parameter matches all features in the collection that are not associated with a location, too. The `datetime` parameter matches all features in the collection that are not associated with a time stamp or interval, too.

The `limit` parameter may be used to control the subset of the selected features that should be returned in the response, the page size.

Each page may include information about the number of selected and returned features (`numberMatched` and `numberReturned`) as well as links to support paging (link relation `next`).

Each `Feature` (path `/collections/{collectionId}/items/{featureId}`) is also a separate resource and may be requested individually using HTTP GET.

In addition to the simple path structures described above, where all features are organized in a one-level collection hierarchy, additional parts of the OGC API Feature series are expected to provide alternate access to the features served by the API via additional, deeper collection hierarchies.

=== API landing page

==== Operation

include::requirements/core/REQ_root-op.adoc[]

==== Response

include::requirements/core/REQ_root-success.adoc[]

include::recomendations/core/REC_root-links.adoc[]

NOTE: Version 1.0.0 of this specification did not include `self` and `alternate` links for the landing page while the links are required in other resources. The recommendation above has been added to encourage implementations to add these links on the landing page, too.

[[schema_landingPage]]
.link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/landingPage.yaml[Schema for the landing page]
[source,YAML]
----
type: object
required:
  - links
properties:
  title:
    type: string
  description:
    type: string
  links:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
----

[[example_2]]
.Landing page response document
=================
[source,JSON]
----
{
  "title": "Buildings in Bonn",
  "description": "Access to data about buildings in the city of Bonn via a Web API that conforms to the OGC API Features specification.",
  "links": [
    { "href": "http://data.example.org/",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/?f=html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://data.example.org/api",
      "rel": "service-desc", "type": "application/vnd.oai.openapi+json;version=3.0", "title": "the API definition" },
    { "href": "http://data.example.org/api.html",
      "rel": "service-doc", "type": "text/html", "title": "the API documentation" },
    { "href": "http://data.example.org/conformance",
      "rel": "conformance", "type": "application/json", "title": "OGC API conformance classes implemented by this server" },
    { "href": "http://data.example.org/collections",
      "rel": "data", "type": "application/json", "title": "Information about the feature collections" }
  ]
}
----
=================

==== Error situations

See <<http_status_codes>> for general guidance.

=== API definition

==== Operation

Every API is expected to provide a definition that describes the capabilities of the server and which can be used by developers to understand the API, by software clients to connect to the server, or by development tools to support the implementation of servers and clients.

include::requirements/core/REQ_api-definition-op.adoc[]

include::recomendations/core/PER_api-definition-uri.adoc[]

Note that multiple API definition formats can be supported.

==== Response

include::requirements/core/REQ_api-definition-success.adoc[]

include::recomendations/core/REC_api-definition-oas.adoc[]

If the server hosts the API definition under the base path of the API (for example, at path `/api`, see above), there is no need to include the path of the API definition in the API definition itself.

The idea is that any OGC API Features implementation can be used by developers that are familiar with the API definition language(s) supported by the server. For example, if an OpenAPI definition is used, it should be possible to create a working client using the OpenAPI definition. The developer may need to learn a little bit about geometry data types, etc., but it should not be required to read this standard to access the data via the API.

In case the API definition is based on OpenAPI 3.0, consider the <<two_appraoches_oas,two approaches>> discussed in OpenAPI requirements class.

==== Error situations

See <<http_status_codes>> for general guidance.

=== Declaration of conformance classes

==== Operation

To support "generic" clients that want to access multiple OGC API Features implementations - and not "just" a specific API / server, the server has to declare the conformance classes it implements and conforms to.

include::requirements/core/REQ_conformance-op.adoc[]

==== Response

include::requirements/core/REQ_conformance-success.adoc[]

[[schema_confClasses]]
.link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/confClasses.yaml[Schema for the list of conformance classes]
[source,YAML]
----
type: object
required:
  - conformsTo
properties:
  conformsTo:
    type: array
    items:
      type: string
----

[[example_3]]
.Conformance declaration response document
=================
This example response in JSON is for a server that supports OpenAPI 3.0 for the API definition and HTML and GeoJSON as encodings for features.

[source,JSON]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson"
  ]
}
----
=================

==== Error situations

See <<http_status_codes>> for general guidance.

=== HTTP 1.1

include::requirements/core/REQ_http.adoc[]

This includes the correct use of status codes, headers, etc.

include::recomendations/core/REC_head.adoc[]

Supporting the method HEAD in addition to GET can be useful for clients and is simple to implement.

Servers implementing <<cross_origin,CORS>> will implement the method OPTIONS, too.

[[http_status_codes]]
==== HTTP status codes

This API standard does not impose any restrictions on which features of the HTTP and HTTPS protocols may be used. API clients should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 400, and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`304` |An <<web_caching,entity tag was provided in the request>> and the resource has not been changed since the previous request.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfil it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recomendations/core/PER_additional-status-codes.adoc[]

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[query_parameters]]
=== Unknown or invalid query parameters

include::requirements/core/REQ_query-param-unknown.adoc[]

If a server wants to support vendor specific parameters, these have to be explicitly declared in the API definition.

If OpenAPI is used to represent the API definition, a capability exists to allow additional parameters without explicitly declaring them. That is, parameters that have not been explicitly specified in the API definition for the operation will be ignored.

[[schema_free-form]]
.OpenAPI schema for additional "free-form" query parameters
[source,YAML]
----
in: query
name: vendorSpecificParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of `vendorSpecificParameters` is this object:

[source,JSON]
----
{
  "my_first_parameter": "some value",
  "my_other_parameter": 42
}
----

In the request URI this would be expressed as `&my_first_parameter=some%20value&my_other_parameter=42`.

include::requirements/core/REQ_query-param-invalid.adoc[]

This is a general rule that applies to all parameters, whether they are specified in this document or in additional parts. A value is invalid if it violates the API definition or any other constraint for that parameter stated in a requirement.

[[web_caching]]
=== Web caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by <<rfc723x,RFC 7232 (HTTP 1.1)>>.

include::recomendations/core/REC_etag.adoc[]

[[cross_origin]]
=== Support for cross-origin requests

Access to data from a HTML page is by default prohibited for security reasons, if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.

include::recomendations/core/REC_cross-origin.adoc[]

Two common mechanisms to support cross-origin requests are:

* link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]; and

* link:https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)].

[[encodings]]
=== Encodings

While OGC API Features does not specify any mandatory encoding, support for the following encodings is recommended. See <<overview,Clause 6 (Overview)>> for a discussion.

include::recomendations/core/REC_html.adoc[]

include::recomendations/core/REC_geojson.adoc[]

<<_http_1_1,Requirement `/req/core/http`>> implies that the encoding of a server response is determined using content negotiation as specified by the HTTP RFC.

The section <<mediatypes,Media Types>> includes guidance on media types for <<encodings,encodings>> that are specified in this document.

Note that any server that supports multiple encodings will have to support a mechanism to mint encoding-specific URIs for resources in order to express links, for example, to alternate representations of the same resource. This document does not mandate any particular approach how this is supported by the server.

As clients simply need to dereference the URI of the link, the implementation details and the mechanism how the encoding is included in the URI of the link are not important. Developers interested in the approach of a particular implementation, for example, to manipulate ("hack") URIs in the browser address bar, can study the API definition.

[NOTE]
=====================================================================
Two common approaches are:

* an additional path for each encoding of each resource (this can be expressed,
for example, using format specific suffixes like ".html");

* an additional query parameter (for example, "accept" or "f") that overrides
the Accept header of the HTTP request.
=====================================================================

[[string_i18n]]
=== String internationalization

If the server supports representing resources in multiple languages, the usual HTTP content negotiation mechanisms apply. The client states its language preferences in the `Accept-Language` header of a request and the server responds with responses that have linguistic text in the language that best matches the requested languages and the capabilities of the server.

include::recomendations/core/REC_string_i18n.adoc[]

For example, if JSON-LD is used as an encoding, the built-in capabilities to link:https://www.w3.org/TR/json-ld/#string-internationalization[annotate a string with its language] should be used.

The link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml[link object] based on <<rfc8228,RFC 8288 (Web Linking)>> includes a `hreflang` attribute that can be used to state the language of the referenced resource. This can be used to include links to the same data in, for example, English or French. Just like with <<encodings,multiple encodings>> a server that wants to use language-specific links will have to support a mechanism to mint language-specific URIs for resources in order to express links to, for example, the same resource in another language. Again, this document does not mandate any particular approach how such a capability is supported by the server.

=== Coordinate reference systems

As discussed in Chapter 9 of the <<SDWBP,W3C/OGC Spatial Data on the Web Best Practices document>>, how to express and share the location of features in a consistent way is one of the most fundamental aspects of publishing geographic data and it is important to be clear about the coordinate reference system that coordinates are in.

For the reasons discussed in the Best Practices, OGC API Features uses WGS 84 longitude and latitude as the default coordinate reference system for spatial geometries.

include::requirements/core/REQ_crs84.adoc[]

Implementations compliant with the Core are not required to support publishing feature geometries in coordinate reference systems other than http://www.opengis.net/def/crs/OGC/1.3/CRS84 (for coordinates without height) or http://www.opengis.net/def/crs/OGC/0/CRS84h (for coordinates with ellipsoidal height); i.e., the (optional) third coordinate number is always the ellipsoidal height.

The Core also does not specify a capability to request feature geometries in a different coordinate reference system. Such a capability will be specified in another part of the OGC API Features series.

The same principles apply for temporal geometries, which are measured relative to a temporal coordinate reference system. OGC API Features uses the Gregorian calendar and all dates or timestamps discussed in this document are in the Gregorian calendar and conform to <<rfc3339,RFC 3339>>.

include::recomendations/core/REC_rfc3339.adoc[]

=== Link headers

include::recomendations/core/REC_link-header.adoc[]

[[_collections_]]
=== Feature collections

==== Operation

include::requirements/core/REQ_fc-md-op.adoc[]

==== Response

include::requirements/core/REQ_fc-md-success.adoc[]

[[schema_collections]]
.link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collections.yaml[Schema for the collections resource]
[source,YAML]
----
type: object
required:
  - links
  - collections
properties:
  links:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
  collections:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml
----

include::requirements/core/REQ_fc-md-links.adoc[]

include::recomendations/core/REC_fc-md-descriptions.adoc[]

include::recomendations/core/REC_fc-md-license.adoc[]

include::requirements/core/REQ_fc-md-items.adoc[]

include::recomendations/core/PER_fc-md-items.adoc[]

This document does not specify mechanisms how clients may access all collections from servers with many collections. Such mechanisms may be specified in additional parts of OGC API Features. Options include support for paging and/or filtering.

include::recomendations/core/REC_fc-md-self-links.adoc[]

NOTE: Including the `self` link in each collection is strongly recommended. It is an oversight that no requirement has been included in the original release of the standard. To avoid a breaking change, this statement is only a recommendation in this document version. Note that the URI can be inferred by clients using the member `id` of the feature collection, if it is missing, but this should not be necessary.

include::requirements/core/REQ_fc-md-items-links.adoc[]

include::requirements/core/REQ_fc-md-extent.adoc[]

The member `spatial` only needs to be provided in the `extent` object, if features in the feature collection have spatial properties. The same applies to `temporal` and features with temporal properties. For example, a feature collection where features have a spatial, but no temporal property will only provide the `spatial` member.

The spatial and temporal extents support multiple bounding boxes (`bbox` array) and time intervals (`interval` array).

The first bounding box/time interval describes the overall spatial/temporal extent of the data. All subsequent bounding boxes and time intervals describe more precise extents, e.g., to identify clusters of data. Clients only interested in the overall extent will only access the first item in each array.

The `bbox` and `interval` properties will typically be derived automatically from the feature data and be the exact minimal bounding box / time interval containing the features in the collection (or cluster).

include::requirements/core/REQ_fc-md-extent-multi.adoc[]

include::recomendations/core/REC_fc-md-extent-single.adoc[]

The last requirement and recommendation reflect that most clients will only be interested in a single extent, for example, to set the map view or a time slider. They will only have to look at the first item in each array. 

At the same time, for some data and for some use cases, a more fine-grained description of the extent will be useful. In that case the first bounding box / time interval is a union of all the other bounding boxes / time intervals. Clients can then choose, if they want to use the simpler or the more detailed extent information.

[[example_4a]]
.Spatial extent with multiple bounding boxes
=================
The following extent can describe feature data in the United States of America (excluding Territories). The first bounding box of the four bounding boxes is the union of the three other bounding boxes representing the 48 contiguous states, Alaska and Hawaii respectively - from the west-bound longitude of Alaska to the east-bound longitude of the 48 contiguous states.

Note that the overall bounding box as well as the bounding box of Alaska crosses the anti-meridian.

[source,JSON]
----
{
  "spatial": {
    "bbox": [ 
      [172.461667, 18.910361, -66.9513812, 71.365162], 
      [-124.7844079, 24.7433195, -66.9513812, 49.3457868], 
      [172.461667, 51.214183, -129.979511, 71.365162], 
      [-178.334698, 18.910361, -154.806773, 28.402123] 
    ]
  }
}
----
=================

As can be seen in the example, there can be multiple ways to construct the overall bounding box from its component bounding boxes since longitudes are cyclic (that is, -180° is equal to 180°). Another union of the component bounding boxes for the 48 contiguous states, Alaska and Hawaii would be `[-124.7844079, 18.910361, -129.979511, 71.365162]` - from the west-bound longitude of the 48 contiguous states to the east-bound longitude of Alaska. The typical approach in such cases is to select the option with the smallest area, as was done in the example.

include::recomendations/core/PER_fc-md-extent-extensions.adoc[]

[[schema_collection]]
.link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml[Schema for a feature collection]
[source,YAML]
----
type: object
required:
  - id
  - links
properties:
  id:
    description: identifier of the collection used, for example, in URIs
    type: string
  title:
    description: human readable title of the collection
    type: string
  description:
    description: a description of the features in the collection
    type: string
  links:
    type: array
    items:
      $ref: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
  extent:
    description: >-
      The extent of the features in the collection. In the Core only spatial and temporal
      extents are specified. Extensions may add additional members to represent other
      extents, for example, thermal or pressure ranges.
    type: object
    properties:
      spatial:
        description: >-
          The spatial extent of the features in the collection.
        type: object
        properties:
          bbox:
            description: >-
              One or more bounding boxes that describe the spatial extent of the dataset.
              In the Core only a single bounding box is supported. Extensions may support
              additional areas. If multiple areas are provided, the union of the bounding
              boxes describes the spatial extent.
            type: array
            minItems: 1
            items:
              description: >-
                Each bounding box is provided as four or six numbers, depending on
                whether the coordinate reference system includes a vertical axis
                (height or depth):

                * Lower left corner, coordinate axis 1
                * Lower left corner, coordinate axis 2
                * Minimum value, coordinate axis 3 (optional)
                * Upper right corner, coordinate axis 1
                * Upper right corner, coordinate axis 2
                * Maximum value, coordinate axis 3 (optional)

                If the value consists of four numbers, the coordinate reference system is
                WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84)
                unless a different coordinate reference system is specified in `crs`.

                If the value consists of six numbers, the coordinate reference system is WGS 84
                longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h)
                unless a different coordinate reference system is specified in `crs`.

                For WGS 84 longitude/latitude the values are in most cases the sequence of
                minimum longitude, minimum latitude, maximum longitude and maximum latitude.
                However, in cases where the box spans the antimeridian the first value
                (west-most box edge) is larger than the third value (east-most box edge).

                If the vertical axis is included, the third and the sixth number are
                the bottom and the top of the 3-dimensional bounding box.

                If a feature has multiple spatial geometry properties, it is the decision of the
                server whether only a single spatial geometry property is used to determine
                the extent or all relevant geometries.
              type: array
              oneOf:
              - minItems: 4
                maxItems: 4
              - minItems: 6
                maxItems: 6
              items:
                type: number
              example:
                - -180
                - -90
                - 180
                - 90
          crs:
            description: >-
              Coordinate reference system of the coordinates in the spatial extent
              (property `bbox`). The default reference system is WGS 84 longitude/latitude.
              In the Core the only other supported coordinate reference system is
              WGS 84 longitude/latitude/ellipsoidal height for coordinates with height.
              Extensions may support additional coordinate reference systems and add
              additional enum values.
            type: string
            enum:
              - 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
              - 'http://www.opengis.net/def/crs/OGC/0/CRS84h'
            default: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
      temporal:
        description: >-
          The temporal extent of the features in the collection.
        type: object
        properties:
          interval:
            description: >-
              One or more time intervals that describe the temporal extent of the dataset.
              The value `null` is supported and indicates an unbounded interval end.
              In the Core only a single time interval is supported. Extensions may support
              multiple intervals. If multiple intervals are provided, the union of the
              intervals describes the temporal extent.
            type: array
            minItems: 1
            items:
              description: >-
                Begin and end times of the time interval. The timestamps are in the
                temporal coordinate reference system specified in `trs`. By default
                this is the Gregorian calendar.
              type: array
              minItems: 2
              maxItems: 2
              items:
                type: string
                format: date-time
                nullable: true
              example:
                - '2011-11-11T12:22:11Z'
                - null
          trs:
            description: >-
              Coordinate reference system of the coordinates in the temporal extent
              (property `interval`). The default reference system is the Gregorian calendar.
              In the Core this is the only supported temporal coordinate reference system.
              Extensions may support additional temporal coordinate reference systems and add
              additional enum values.
            type: string
            enum:
              - 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian'
            default: 'http://www.opengis.net/def/uom/ISO-8601/0/Gregorian'
  itemType:
    description: indicator about the type of the items in the collection (the default value is 'feature').
    type: string
    default: feature
  crs:
    description: the list of coordinate reference systems supported by the service
    type: array
    items:
      type: string
    default:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
----

NOTE: The `itemType` property is optional with a default value "feature" to be compatible with implementations that existed before the property was introduced. It is recommended that all implementations explicitly state the `itemType` in the collection object. Other standards that specify other types of data items have to require that the `itemType` is included so there is no ambiguity.

NOTE: The `crs` property of the `collection` object is not used by this requirements class, but reserved for future use.

[[example_4]]
.Feature collections response document
=================
This feature collections example response in JSON is for a dataset with a single collection "buildings". It includes links to the features resource in all formats that are supported by the service (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "items").

There is a link to the feature collections response itself (link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type]: "self"). Representations of this resource in other formats are referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "alternate".

An additional link is to a GML application schema for the dataset - using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "describedby".

A bulk download of all the features in the dataset is referenced using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "enclosure".

Finally there are also links to the license information for the building data (using link:https://www.iana.org/assignments/link-relations/link-relations.xhtml[link relation type] "license").

Reference system information is not provided as the service provides geometries only in the default systems (spatial: WGS 84 longitude/latitude; temporal: Gregorian calendar).

[source,JSON]
----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/buildings.xsd",
      "rel": "describedby", "type": "application/xml", "title": "GML application schema for Acme Corporation building data" },
    { "href": "http://download.example.org/buildings.gpkg",
      "rel": "enclosure", "type": "application/geopackage+sqlite3", "title": "Bulk download (GeoPackage)", "length": 472546 }
  ],
  "collections": [
    {
      "id": "buildings",
      "title": "Buildings",
      "description": "Buildings in the city of Bonn.",
      "extent": {
        "spatial": {
          "bbox": [ [ 7.01, 50.63, 7.22, 50.78 ] ]
        },
        "temporal": {
          "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
        }
      },
      "itemType": "feature",
      "links": [
        { "href": "http://data.example.org/collections/buildings",
          "rel": "self", "title": "This collection" },
        { "href": "http://data.example.org/collections/buildings/items",
          "rel": "items", "type": "application/geo+json",
          "title": "Buildings" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
          "rel": "license", "type": "text/html",
          "title": "CC0-1.0" },
        { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
          "rel": "license", "type": "application/rdf+xml",
          "title": "CC0-1.0" }
      ]
    }
  ]
}
----
=================

==== Error situations

See <<http_status_codes>> for general guidance.

[[_collection_]]
=== Feature collection

==== Operation

include::requirements/core/REQ_sfc-md-op.adoc[]

==== Response

include::requirements/core/REQ_sfc-md-success.adoc[]

include::recomendations/core/REC_sfc-md-links.adoc[]

NOTE: Including the `self` and `alternates` links in each collection is strongly recommended. It is an oversight that no requirement has been included in the original release of the standard. To avoid a breaking change, this statement is only a recommendation in this document version.

==== Error situations

See <<http_status_codes>> for general guidance.

If the parameter `collectionId` does not exist on the server, the status code of the response will be `404` (see <<status_codes>>).

[[_items_]]
=== Features

==== Operation

include::requirements/core/REQ_fc-op.adoc[]

==== Parameter limit

include::requirements/core/REQ_fc-limit-definition.adoc[]

include::recomendations/core/PER_fc-limit-default-minimum-maximum.adoc[]

include::requirements/core/REQ_fc-limit-response-1.adoc[]

include::recomendations/core/PER_fc-limit-response-2.adoc[]

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/parameters/limit.yaml[limit.yaml].

==== Parameter bbox

include::requirements/core/REQ_fc-bbox-definition.adoc[]

include::requirements/core/REQ_fc-bbox-response.adoc[]

"Intersects" means that the rectangular area specified in the parameter `bbox` includes a coordinate that is part of the (spatial) geometry of the feature. This includes the boundaries of the geometries (e.g., for curves the start and end position and for surfaces the outer and inner rings).

In case of a degenerated bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all features match where the geometry intersects with this point.

This standard does not specify requirements for the parameter `bbox-crs`, which adds support for other coordinate reference systems that can be used in the `bbox` parameter. See OGC API - Features - Part 2: Coordinate Reference Systems by Reference for the specification of the [parameter `bbox-crs`](http://www.opengis.net/doc/IS/ogcapi-features-2/1.0#_parameter_bbox_crs).

For WGS 84 longitude/latitude the bounding box is in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the anti-meridian the first value (west-most box edge) is larger than the third value (east-most box edge).

[[example_5]]
.The bounding box of the New Zealand Exclusive Economic Zone
=================
The bounding box of the New Zealand Exclusive Economic Zone in WGS 84 (from 160.6°E to 170°W and from 55.95°S to 25.89°S) would be represented in JSON as `[ 160.6, -55.95, -170, -25.89 ]` and in a query as `bbox=160.6,-55.95,-170,-25.89.`
=================

Note that according to the requirement to <<query-param-invalid,return an error for an invalid parameter value>>, the server will return an error, if a latitude value of `160.0` is used.

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/parameters/bbox.yaml[bbox.yaml].

==== Parameter datetime

include::requirements/core/REQ_fc-time-definition.adoc[]

include::requirements/core/REQ_fc-time-response.adoc[]

"Intersects" means that the time (instant or interval) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the feature (again, a time instant or interval). For time intervals this includes the start and end time.

NOTE: The interval notation is taken from <<iso8601-2,ISO 8601-2:2019>>. ISO 8601-2 distinguishes between bounded start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an unbounded start/end.

[[example_6]]
.A date-time
=================
February 12, 2018, 23:20:52 UTC:

`datetime=2018-02-12T23%3A20%3A52Z`
=================

For features with a temporal property that is a timestamp (like `lastUpdate` in the building features), a date-time value would match all features where the temporal property is identical.

For features with a temporal property that is a date or a time interval, a date-time value would match all features where the timestamp is on that day or within the time interval.

[[example_7]]
.Intervals
=================
February 12, 2018, 00:00:00 UTC to March 18, 2018, 12:31:12 UTC:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..` or `datetime=2018-02-12T00%3A00%3A00Z%2F`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z` or `datetime=%2F2018-03-18T12%3A31%3A12Z`
=================

For features with a temporal property that is a timestamp (like `lastUpdate` in the building features), a time interval would match all features where the temporal property is within the interval.

For features with a temporal property that is a date or a time interval, a time interval would match all features where the values overlap.

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/parameters/datetime.yaml[datetime.yaml].

==== Parameters for filtering on feature properties

include::recomendations/core/REC_fc-filters.adoc[]

[[example_8]]
.An additional parameter to filter buildings based on their function
=================
[source,YAML]
----
name: function
in: query
description: >-
  Only return buildings of a particular function.\

  Default = return all buildings.
required: false
schema:
  type: string
  enum:
    - residential
    - commercial
    - public use
style: form
explode: false
example: 'function=public+use'
----
=================

[[example_9]]
.An additional parameter to filter buildings based on their name
=================
[source,YAML]
----
name: name
in: query
description: >-
  Only return buildings with a particular name. Use '*' as a wildcard.\

  Default = return all buildings.
required: false
schema:
  type: string
style: form
explode: false
example: 'name=A*'
----

For string-valued properties, servers could support wildcard searches. The example included in the OpenAPI fragment would search for all buildings with a name that starts with "A."
=================

==== Combinations of filter parameters

Any combination of `bbox`, `datetime` and parameters for filtering on feature properties is allowed. Note that the requirements on these parameters imply that only features matching all the predicates are in the result set; i.e., the logical operator between the predicates is 'AND.'

[[fc-response]]
==== Response

include::requirements/core/REQ_fc-response.adoc[]

The number of features returned depends on the server and the parameter `limit.`

* The client can request a limit it is interested in.

* The server likely has a default value for the limit, and a maximum limit.

* If the server has any more results available than it returns (the number it returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

So (using the default/maximum values of 10/10000 from the OpenAPI fragment in requirement `/req/core/fc-limit-definition`):

* If you ask for 10, you will get 0 to 10 (as requested) and if there are more, a `next` link;

* If you don't specify a limit, you will get 0 to 10 (default) and if there are more, a `next` link;

* If you ask for 50000, you might get up to 10000 (server-limited) and if there are more, a `next` link;

* If you follow the next link from the previous response, you might get up to 10000 additional features and if there are more, a `next` link.

include::requirements/core/REQ_fc-links.adoc[]

include::recomendations/core/REC_fc-next-1.adoc[]

include::recomendations/core/REC_fc-next-2.adoc[]

include::recomendations/core/REC_fc-next-3.adoc[]

This document does not mandate any specific implementation approach for the `next` links.

An implementation could use opaque links that are managed by the server. It is up to the server to determine how long these links can be de-referenced. Clients should be prepared to receive a 404 response.

Another implementation approach is to use an implementation-specific parameter that specifies the index within the result set from which the server begins presenting results in the response, like the `startIndex` parameter that was used in <<WFS20,WFS 2.0>> (and which may be added again in additional parts of the OGC API Features series).

The API will return no `next` link, if it has returned all selected features, and the server knows that. However, the server may not be aware that it has already returned all selected features. For example, if the request states `limit=10` and the query to the backend datastore returns 10 features, the server may not know, if there are more features or not (in most cases there will be more features), unless the total number of matches is also computed, which may be too costly. The server will then add the next link, and if there are no more features, dereferencing the next link will return am empty feature collection and no next link. This behavior is consistent with the statements above.

Clients should not assume that paging is safe against changes to dataset while a client iterates through `next` links. If a server provides opaque links these could be safe and maintain the dataset state during the original request. Using a parameter for the start index, however, will not be safe.

NOTE: Additional requirements classes for safe paging or an index parameter
may be added in extensions to this specification.

include::recomendations/core/PER_fc-prev.adoc[]

Providing `prev` links supports navigating back and forth between pages, but depending on the implementation approach it may be too complex to implement.

include::requirements/core/REQ_fc-rel-type.adoc[]

include::requirements/core/REQ_fc-timeStamp.adoc[]

include::requirements/core/REQ_fc-numberMatched.adoc[]

include::requirements/core/REQ_fc-numberReturned.adoc[]

include::recomendations/core/REC_fc-extent.adoc[]

NOTE: The representation of the links and the other properties in the payload depends on the encoding of the feature collection.

[[example_10]]
.Links
=================
If the request is to return building features and "10" is the default `limit`, the links in the response could be (in this example represented as link headers and using an additional parameter `offset` to implement `next` links - and the optional `prev` links):

[source]
----
Link: <http://data.example.org/collections/buildings/items.json>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items.html>; rel="alternate"; type="text/html"
Link: <http://data.example.org/collections/buildings/items.json?offset=10>; rel="next"; type="application/geo+json"
----

Following the `next` link could return:

[source]
----
Link: <http://data.example.org/collections/buildings/items.json?offset=10>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items.html?offset=10>; rel="alternate"; type="text/html"
Link: <http://data.example.org/collections/buildings/items.json?offset=0>; rel="prev"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items.json?offset=20>; rel="next"; type="application/geo+json"
----

If an explicit `limit` of "50" is used, the links in the response could be:

[source]
----
Link: <http://data.example.org/collections/buildings/items.json?limit=50>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items.html?limit=50>; rel="alternate"; type="text/html"
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=50>; rel="next"; type="application/geo+json"
----

Following the `next` link could return:

[source]
----
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=50>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items.html?limit=50&offset=50>; rel="alternate"; type="text/html"
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=0>; rel="prev"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items.json?limit=50&offset=100>; rel="next"; type="application/geo+json"
----
=================

==== Error situations

See <<http_status_codes>> for general guidance.

If the path parameter `collectionId` does not exist on the server, the status code of the response will be `404.`

A `400` will be returned in the following situations:

* If query parameter `limit` is not an integer or not between minimum and maximum;

* if query parameter `bbox` does not have 4 (or 6) numbers or they do not form a bounding box;

* if parameter `datetime` is not a valid time stamp or time interval.

[[_feature_]]
=== Feature

==== Operation

include::requirements/core/REQ_f-op.adoc[]

include::recomendations/core/PER_f-id.adoc[]

==== Response

include::requirements/core/REQ_f-success.adoc[]

include::requirements/core/REQ_f-links.adoc[]

NOTE: The representation of the links in the payload will depend on the encoding
of the feature.

[[example_11]]
.Links
=================
The links in a feature could be (in this example represented as link headers):

[source]
----
Link: <http://data.example.org/collections/buildings/items/123.json>; rel="self"; type="application/geo+json"
Link: <http://data.example.org/collections/buildings/items/123.html>; rel="alternate"; type="text/html"
Link: <http://data.example.org/collections/buildings.json>; rel="collection"; type="application/json"
Link: <http://data.example.org/collections/buildings.html>; rel="collection"; type="text/html"
----
=================

==== Error situations

See <<http_status_codes>> for general guidance.

If the path parameter `collectionId` or the path parameter `featureId` do not exist on the server, the status code of the response will be `404.`
