[[mediatypes]]
== Media Types

JSON media types that would typically be used in a WFS that supports JSON are

* `application/geo+json` for feature collections and features, and
* `application/json` for all other resources.

XML media types that would typically occur in a WFS that supports XML are

* `application/gml+xml;version=3.2` for any GML 3.2 feature collections and features,
* `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` for GML 3.2 feature collections and features conforming to the GML Simple Feature Level 0 profile,
* `application/gml+xml;version=3.2;profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` for GML 3.2 feature collections and features conforming to the GML Simple Feature Level 2 profile, and
* `application/xml` for all other resources.

The typical HTML media type for all "web pages" in a WFS would be `text/html`.

The media type for an OpenAPI definition in JSON is `application/openapi+json;version=3.0`.

CAUTION: link:https://github.com/opengeospatial/WFS_FES/issues/117[ISSUE 117] +
The OpenAPI media type has not been registered yet with IANA and will likely
change. We need to update the media type after registration.
