== Section 11: Security Considerations

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/oas30/security +

For cases, where the operations of the server are access-controlled, the security scheme(s) SHALL be documented in the OpenAPI definition.
|===

OpenAPI provides two constructs to describe security controls; Security Scheme Objects, and Security Requirements. 

=== Security Schemes

A Security Scheme Object provides a detailed description of a [underline]#type# of security control. They do not identify where in the API the control should be applied. Currently the OpenAPI specification supports the following Security Schemes:

* HTTP authentication,
* API key (either as a header or as a query parameter),
* OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and
* OpenID Connect Discovery.

Support for client-side PKI certificates is planned for version 3.1.

Security Scheme Objects reside within the Components Object in the OAS document root. Each Security Scheme Object has an associated key. These keys allow a Security Scheme Object to be referenced from elsewhere in the OAS document. The keys also allow for multiple flavors of a scheme type.  For example, the keys "Bobs_API" and "Marys_API" could reference two Schemes of type API Key that have different implementations (ex. header vs. query).

=== Security Requirements

Security Requirements Objects are used to identify where in the API a Security Scheme (or schemes) should be applied. These objects consist of a set of key-value pairs. Each key should correspond to a key for a Security Scheme Object. The Security Requirement is satisfied when all of the Security Schemes (identified by the keys) are satisfied. The associated values provide additional information specific to this Security Requirement. Currently values are only defined for oauth2 and openIDConnect schemes. 

Security Requirements can be specified at two levels: 

* Root: These Security Requirements apply to the whole document unless over-ridden.

* Operations: These Security Requirements apply to a single operation.  These requirements override any requirements specified at the root level.  

Rules for Applicability:

. When more than one Security Requirement is provided, only one has to be satisfied.

. A Security Requirement may map to more than one Security Scheme. In that case, all of the Schemes must be satisfied.

. An empty Security Requirement object is valid.  This indicates that there are no security controls.

=== OpenAPI Security Issues:

The following issues have been taken to the OpenAPI Technical Steering Committee for resolution.

. There is no way to directly associate a Security Requriement with a Server Object. This can lead to problems. Consider the case where an operation contains two Server Objects. These two servers each implement a different form of access control. There are Security Requirement objects for each form of access control. How does the client know which control goes with which server?  The answer at this time is that they don't.

. The scope of a Security Requirement is ambiguous in regards to resources. If the result of an operation is a document which contains links to other documents, does the Security Requirement apply to the links as well? Under the current version of OpenAPI we cannot tell for sure.

Our recomended way forward is to be aware of security constraints when designing your API.

. If two servers have different access controls, then put them on different paths.

. Organize your resources so that if a user has access to one resource, then they can access all linked resources as well.

. Use the appropriate HTTP status codes and messages. If the client does not have access, let them know what is missing.
```

