== Terms, Definitions, Symbols and Abbreviated Terms

=== Terms and Definitions
This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

[[endpoint-def]]
endpoint::
a web address (URI) at which access can be gained to a service or resource

[[ogc-webapi-def]]
OGC Web API::
A Web API that implements one or more Conformance Classes from an OGC API Standard (<<OAFeat-1,OGC API - Features - Part 1: Core>>)

[[resource-def]]
resource::
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>)

NOTE: The term "resource", when used in the context of an OGC API standard, should be understood to mean a <<web-resource-def,web resource>> unless otherwise indicated.

[[returnable-def]]
returnable::
the name of a property of a web resource that is available in representations of the resource when fetching the resource

[[web-resource-def]]
web resource::
a **resource** that is identified by a HTTP URI (<<OAFeat-1,OGC API - Features - Part 1: Core>>)

=== Abbreviated terms

API::
  Application Programming Interface
HTTP::
  Hypertext Transfer Protocol
HTTPS::
  Hypertext Transfer Protocol Secure
JSON::
  JavaScript Object Notation
OGC::
  Open Geospatial Consortium
URI::
  Uniform Resource Identifier
