[[overview]]
== Overview

This Standard specifies two types of requirements classes.

=== Requirements and recommendations for schemas

The schemas describing geospatial data specified by this Standard are logical schemas describing the data, independent of a particular format to represent the data. 

In order to use the schema for data validation, the schema first has to be converted into a schema representation suitable for validating data in the specific data format. For example, an XML Schema that is a GML application schema or a JSON Schema for GeoJSON or JSON-FG.

While the schema is a logical schema, a machine-readable representation is needed. Instead of specifying a custom schema language for geospatial data, this Standard uses JSON Schema as the schema language with:

* Extensions for additional aspects that are common in geospatial data,
* Recommendations for restricting the use of JSON Schema capabilities to simplify parsing a schema.

That is, JSON Schema is primarily used as a data description language.

The main reasons for using JSON Schema are:

* Web developers are often familiar with JSON Schema and JSON;
* JSON data types (string, number, boolean, array, object, null) are simple and easy to understand; and
* JSON is often used for encoding geospatial data, i.e., the schema of a property can be used to validate property values without conversion.

=== Requirements and recommendations for schemas in OGC Web APIs

These requirements classes specify API building blocks related to schemas. 

In OGC Web APIs, geospatial data is shared in collections (path `/collections/{collectionId}`). The schema of items in a collection provides information about how to interact with the collection. 

Examples of interactions, where information about the schema are required, include:

* An application that wants to fetch data often needs information about the properties included in the data to process, present, or store the data properly ("returnable" properties or "Returnables").
* An application that wants to fetch data restricted to a subset of the available properties needs the list of the properties in the data (again, "returnable" properties or "Returnables").
* An application that wants to fetch a subset of the data needs information about the properties that can be used to filter the data ("queryable" properties or "Queryables").
* An application that wants to fetch data in a specific order needs information about the properties that can be used to sort the data ("sortable" properties or "Sortables").
* An application that wants to create or update data needs information about the required or acceptable properties of the data ("receivable" properties or "Receivables").

This Standard specifies the following schema resources to support these interactions.

* Returnables and Receivables at path: `/collections/{collectionId}/schema`
* Queryables at path `/collections/{collectionId}/queryables`
* Sortables at path `/collections/{collectionId}/sortables`
