== Terms, Definitions, Symbols and Abbreviated Terms

=== Terms and Definitions
This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

[[collection-def]]
collection::
a body of resources that belong or are used together; an aggregate, set, or group of related resources (http://docs.opengeospatial.org/DRAFTS/20-024.html#terms_and_definitions[OGC API - Common - Part 2: Collections]).

[[endpoint-def]]
endpoint::
a web address (URI) at which access can be gained to a service or resource

[[json-key-def]]
<JSON> key::
the name of a *member*

[[json-member-def]]
<JSON> member::
a name/value pair in a JSON object

[[logical-model-def]]
logical model::
an abstracted representation of domain knowledge that could feasibly be used in Model Driven Architecture to generate physical artifacts (https://docs.ogc.org/dp/21-041r2.html[OGC Conceptual Modeling Discussion Paper])

[[ogc-webapi-def]]
OGC Web API::
A Web API that implements one or more Conformance Classes from an OGC API Standard (<<OAFeat-1,OGC API - Features - Part 1: Core>>)

[[primary-geometry-def]]
primary geometry::
the geometry that the publisher considers as the most important spatial characteristic of a *feature*

NOTE: A feature can be described by multiple spatial properties. For example, a radio tower can have a property with a point value that describes the location of the tower and another property with a multi-polygon value that describes the area of coverage. Some feature formats can represent only a single geometry per feature. In those cases, the primary geometry will be used when the feature is encoded in such a format.

NOTE: The primary geometry of a feature can also vary depending on the zoom level. At a smaller scale, the primary geometry could be a point while a polygon could be used at a larger scale.

[[primary-temporal-information-def]]
primary temporal information::
the time instant or time interval that the publisher considers as the most important temporal characteristic of a *feature*

NOTE: A feature can be described by multiple temporal properties. For example, an event can have a property with an instant or interval when the event occurred or will occur and another property when the event was recorded in the dataset. The primary temporal information can also be built from two properties, e.g., when the feature has two properties describing the start and end instants of an interval.

[[publisher-def]]
publisher::
entity responsible for making a resource available (https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/publisher[Dublin Core Metadata Initiative - DCMI Metadata Terms])

NOTE: As content of OGC API standards, a resource is typically published at an endpoint.

[[queryable-def]]
queryable::
the name of a property of a resource that can be used in a filter expression

[[receivable-def]]
receivable::
the name of a property of a web resource that can be included in representations of the resource when creating or updating a resource

[[resource-def]]
resource::
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>)

NOTE: The term "resource", when used in the context of an OGC API standard, should be understood to mean a <<web-resource-def,web resource>> unless otherwise indicated.

[[returnable-def]]
returnable::
the name of a property of a web resource that is available in representations of the resource when fetching the resource

[[sortable-def]]
sortable::
the name of a property of a resource that can be used to sort resources of the same type

[[web-resource-def]]
web resource::
a **resource** that is identified by a HTTP URI (<<OAFeat-1,OGC API - Features - Part 1: Core>>)

=== Abbreviated terms

API::
  Application Programming Interface
HTTP::
  Hypertext Transfer Protocol
HTTPS::
  Hypertext Transfer Protocol Secure
IANA::
  Internet Assigned Numbers Authority
JSON::
  JavaScript Object Notation
OGC::
  Open Geospatial Consortium
URI::
  Uniform Resource Identifier
YAML::
  YAML Ain't Markup Language
