:req-class: references
[#rc_{req-class}]
== Requirements Class "References"

The Requirements Class "References" specifies additional provisions for properties that reference another resource.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |Schema for a collection of data
|Dependency |<<rc_schemas>>
|===

If resources have a property that represents a reference to another resource, the role "reference" can be used for this property. The property is a foreign key, e.g., the local feature identifier of a referenced feature in its collection.

:req: role-reference
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |A property with "x-ogc-role" set to "reference" SHALL be a string or integer property.
^|B |If the property is of type "integer", the property with role "id" of the referenced resource type SHALL be of type "integer", too.
^|C |If all instances of the property reference geospatial data in a fixed collection of the same server, the id of that collection SHALL be provided in "x-ogc-collectionId".
^|D |If Requirements C does not apply, the URI template SHALL be provided in "x-ogc-uriTemplate" with a template parameter `resourceId`.
|===

NOTE: The requirements stated in this Standard only cover simple cases. More complex cases, such as references to geospatial data in different collections, are not covered.

[[example_9_1]]
.Schema example 
====
This is the schema of a road accident feature type. The "roadSegment" property is a reference to the road segment on which the accident occurred, which is available in the same API.

[source,JSON]
----
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/apis/roads/collections/accidents/schema",
  "type": "object",
  "title": "Road accidents",
  "properties": {
    "id": {
      "title": "Feature identifier",
      "readOnly": true,
      "x-ogc-role": "id",
      "type": "integer"
    },
    "timeOfAccident": {
      "title": "Time of the accident",
      "x-ogc-role": "primary-instant",
      "format": "date-time",
      "type": "string"
    },
    "roadSegment": {
      "title": "Road segment",
      "description": "Road segment on which the accident occured, identified by its 16-character code (8 characters for the start and end node).",
      "x-ogc-role": "reference",
      "x-ogc-collectionId": "roadsegments",
      "type": "string"
    },
    "distanceFromStart": {
      "title": "Distance from start [m]",
      "description": "Distance from the start node of the road segment. The unit is meter.",
      "minimum": 0.0,
      "type": "number",
      "x-ogc-unit": "m"
    },
    "geometry": {
      "x-ogc-role": "primary-geometry",
      "format": "geometry-point"
    }
  }
}
----

If the road segment would be available from a different OGC Web API, the "x-ogc-uriTemplate" keyword can be used with the `resourceId` parameter. The schema of the "roadSegment" property could look like the following:

[source,JSON]
----
{
  "title": "Road segment",
  "description": "Road segment on which the accident occured, identified by its 16-character code (8 characters for the start and end node).",
  "x-ogc-role": "reference",
  "x-ogc-uriTemplate": "https://api.example.org/foo/bar/collections/roadsegments/items/{resourceId}",
  "type": "string"
}
----

A client that wants to fetch the road segment on which an accident occured would use the URI template to construct the URI of the road segment, e.g., `https://api.example.org/foo/bar/collections/roadsegments/items/5209062A5209047O`, if the value of road segment property is "5209062A5209047O". The referenced feature will include a link to its "roadsegments" collection, or a client that is OGC-API-aware can determine the collection URI ("\https://api.example.org/foo/bar/collections/roadsegments") from the URI.
====
