== Conformance

This standard defines the following requirements classes, grouped by their standardization target:

* Web Resource
** <<rc_schemas>> specifies basic provisions for schemas of items in a collection of geospatial data, for example, features, and the representation of a schema in JSON Schema.
** <<rc_core-roles-features>> specifies additional property roles for feature data.
** <<rc_feature-references>> specifies additional provisons for properties that reference another feature.
* Web API
** <<rc_returnables-and-receivables>> specifies the web resources representing the schema with the <<returnable-def,returnable>> and <<receivable-def,receivable>> properties of a collection in OGC Web APIs.
** <<rc_queryables>> specifies the web resources representing the schema with the <<queryable-def,queryable>> properties of a collection in OGC Web APIs.
** <<rc_sortables>> specifies the web resources representing the schema with the <<sortable-def,sortable>> properties of a collection in OGC Web APIs.
** <<rc_profile-parameter>> specifies additional provisons for properties that reference another resource.
** <<rc_profile-references>> specifies three profiles for representing references another resource.

Conformance with this standard shall be checked using all the relevant tests specified in <<ats,Annex A>> of this document for each conformance class. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="25,75",options="header"]
|===
|Conformance class |URI
|Schemas |`\http://www.opengis.net/spec/{standard}/{m_n}/conf/schemas`
|Core roles for features |`\http://www.opengis.net/spec/{standard}/{m_n}/conf/core-roles-features`
|Feature references |`\http://www.opengis.net/spec/{standard}/{m_n}/conf/feature-references`
|Core API building blocks |`\http://www.opengis.net/spec/{standard}/{m_n}/conf/core-api-bblocks`
|Profile query parameter |`\http://www.opengis.net/spec/{standard}/{m_n}/conf/profile-parameter`
|Profiles for references |`\http://www.opengis.net/spec/{standard}/{m_n}/conf/profile-references`
|===

////

This standard defines the following requirements classes, grouped by their standardization target:

* Web API
** <<rc_queryables,Queryables>>
** <<rc_queryables_param,Queryables as Query Parameters>>
** <<rc_filter,Filter>>
** <<rc_features-filter,Features Filter>>

The <<rc_queryables,Queryables>> requirements class defines the Queryables resource (at path `/collections/{collectionId}/queryables`) and its representation as a JSON Schema. Queryables can be used to determine the list of property names and their schemas that may be used to construct filter expressions.

The <<rc_queryables_param,Queryables as Query Parameters>> requirements class adds the requirement to provide query parameters for queryables according to recommendation in the section https://docs.ogc.org/is/17-069r4/17-069r4.html#rec_core_fc-filters[Parameters for filtering on feature properties] in OGC API - Features - Part 1: Core.

The <<rc_filter,Filter>> requirements class defines a set of HTTP query
parameters that may be used to specify complex filter expressions on
HTTP requests.  The specific set of parameters defined in this requirements
class is:

* `filter` - The filter expression.
* `filter-lang` - The language used in the filter expression.
* `filter-crs` - The coordinate reference system used in the filter expression, if Part 2 is supported.

The <<rc_features-filter,Features Filter>> requirements class defines the
binding between the <<rc_filter,Filter>> requirements class and the
<<OAFeat-1,OGC API - Features - Part 1: Core>> standard.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<conf_queryables,Queryables>> |`\http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables`
|<<conf_queryables-query-parameters,Queryables as Query Parameters>> |`\http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/queryables-query-parameters`
|<<conf_filter,Filter>> |`\http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter`
|<<conf_features-filter,Features Filter>> |`\http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter`
|===

APIs that implement the <<CQL2,Common Query Language (CQL2)>> standard should advertize all supported CQL2 conformance classes in the Conformance Declaration, too.

=== Roadmap

The content of this sub-clause is informative.

Because the filter parameters is not exclusively useful for features, it is anticipated that the
<<rc_queryables,Queryables>> and <<rc_filter,Filter>> requirements classes will eventually become parts of the OGC API Common suite of standards thus
leaving the <<rc_queryables_param,Queryables as Query Parameters>> and <<rc_features-filter,Features Filter>> requirements classes as part
3 of the OGC API Features specifications.

////
