[[overview]]
== Overview

This Standard specifies three types of requirements classes.

=== Requirements and recommendations for schemas

The schemas describing geospatial data specified by this Standard are logical schemas describing the data, independent of a particular format to represent the data. 

In order to use the schema for data validation, the schema first has to be converted into a schema representation suitable for validating data in the specific data format. For example, an XML Schema that is a GML application schema or a JSON Schema for GeoJSON or JSON-FG.

While the schema is a logical schema, a machine-readable representation is needed. Instead of specifying a custom schema language for geospatial data, this Standard uses JSON Schema as the schema language with:

* Extensions for additional aspects that are common in geospatial data,
* Recommendations for restricting the use of JSON Schema capabilities to simplify parsing a schema.

That is, JSON Schema is primarily used as a data description language.  Additional elements, listed in the following table, are defined in this Standard that can be used to describe additional aspects of the schema that are common in geospatial data.

[#x-ogc-elements,reftext='{table-caption} {counter:table-num}']
.List of extension elements for describing aspects common in geospatial data
[cols="25,75",options="header"]
|===
|Additional element |Description
|<<rc_profile-codelists_codelist-ref,x-ogc-codelistUri>> |A reference to a codelist.
|<<rc_feature-references_role-reference,x-ogc-collectionId>> |Target collection of foreign key references.
|<<rc-schemas_definition,x-ogc-definition>> |Reference to the semantic definition of a property.
|<<rc_schemas_definition,x-ogc-propertySeq>> |An integer representing the relative position of a property in a schema in ascending order.
|<<rc-schemas_role,x-ogc-role>> |Declares a specific role of a property.
|<<rc_schemas_unit,x-ogc-unit>> |Declares the unit of measure of a property.
|<<rc_schemas_unit,x-ogc-unitLang>> |Declares the language/register used for the unit of measure.
|<<rc_feature-references_role-reference,x-ogc-uriTemplate>> |A URI template with a template `featureId` used to reference a resources in another local or remote collection.
|===

The main reasons for using JSON Schema are:

* Web developers are often familiar with JSON Schema and JSON;
* JSON data types (string, number, boolean, array, object, null) are simple and easy to understand; and
* JSON is often used for encoding geospatial data, i.e., the schema of a property can be used to validate property values without conversion.

NOTE: A proposal exists for a new specification link:https://github.com/json-structure[JSON Structure] that could eventually be more directly applicable for the scope of this Standard and, if approved, be used in a future revision of this Standard.

=== Requirements and recommendations for schemas in OGC Web APIs

These requirements classes specify schema resources in OGC Web APIs.

In OGC Web APIs, geospatial data is shared in collections (path `/collections/{collectionId}`). The schema of items in a collection provides information about how to interact with the collection. 

Examples of interactions, where information about the schema are required, include:

* An application that wants to fetch data often needs information about the properties included in the data to process, present, or store the data properly ("returnable" properties or "Returnables").
* An application that wants to fetch data restricted to a subset of the available properties needs the list of the properties in the data (again, "returnable" properties or "Returnables").
* An application that wants to fetch a subset of the data needs information about the properties that can be used to filter the data ("queryable" properties or "Queryables").
* An application that wants to fetch data in a specific order needs information about the properties that can be used to sort the data ("sortable" properties or "Sortables").
* An application that wants to create or update data needs information about the required or acceptable properties of the data ("receivable" properties or "Receivables").

This Standard specifies the following schema resources to support these interactions.

* Returnables and Receivables at path: `/collections/{collectionId}/schema`
* Queryables at path `/collections/{collectionId}/queryables`
* Sortables at path `/collections/{collectionId}/sortables`

=== Requirements and recommendations for profiles

<<rfc6906,RFC 6906 The 'profile' Link Relation Type>> defines the concept of a profile to support such use cases.

Profiles are a general mechanism that allows to support variations in the resource representation without the need for a proliferation of a new media type for each variant. A profile does not to alter the semantics of the resource representation itself, but allows clients to learn about additional semantics that are associated with the resource representation, in addition to those defined by the media type.

To request one or more profiles, a query parameter "profile" can be used. The server determines the applicable profile(s) for the selected media type.

In total, four profiles are specified for schemas and three profiles are specified for feature data.
