:req-class: profile-references
[#rc_{req-class}]
== Requirements Class "Profiles for references"

The Requirements Class "Profiles for references" specifies three profiles for representing references to other resources.

NOTE: As with <<rc_references>>, this requirements class can probably be generalized to cover also other types of references, but this requires a better understanding about the types of references that have to be supported.

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |Web resources
|Dependency |<<rc_returnables-and-receivables>>
|Dependency |<<rc_profile-parameter>>
|Indirect Dependency |<<rc_references>>
|===

:req: ref-profiles
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the Returnables and Receivables schema of a collection includes a property with role „reference“, the GET operation at `/collections/{collectionId}/items` and `/collections/{collectionId}/items/{resourceId}` SHALL provide the query parameter profile.
|===

:req: rel-as-key
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In the profile "rel-as-key" (`\http://www.opengis.net/def/profile/OGC/0/rel-as-key`) a reference in the response SHALL be represented by:

- The `resourceId` of the referenced resource (a string or integer, depending on the type of the identifier property in the referenced collection), if the property with role "reference" has the keyword "x-ogc-collectionId" with a string value (a fixed collection).
|===

NOTE: What should be provided, if "x-ogc-collectionId" is an array (that is, the referenced resources/features may be in different collections)? A string that combines the `collectionId` and `resourceId`? An object with `collectionId` and `resourceId` properties?

[[example_14_1]]
.Encoding of a road accident feature in GeoJSON and profile "rel-as-key"
====
The examples in this Clause use the <<example_9_1,example road accident feature schema>>.

[source,JSON]
----
{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      7.2789399,
      50.7772485
    ]
  },
  "properties": {
    "timeOfAccident": "2019-02-05T07:00:00Z",
    "roadSegment": "5209062A5209047O",
    "distanceFromStart": 851.0
  },
  "links": [
    {
      "href": "http://www.opengis.net/def/profile/ogc/0/rel-as-key",
      "rel": "profile",
      "title": "Profile used in the response"
    }
  ]
}
----
====

:req: rel-as-uri
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In the profile "rel-as-uri" (`\http://www.opengis.net/def/profile/OGC/0/rel-as-uri`) a reference in the response SHALL be represented by an HTTP(S) URI.
|===

[[example_14_2]]
.Encoding of the same road accident feature for the profile "rel-as-uri"
====
[source,JSON]
----
{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      7.2789399,
      50.7772485
    ]
  },
  "properties": {
    "timeOfAccident": "2019-02-05T07:00:00Z",
    "roadSegment": "https://example.com/apis/roads/collections/roadsegments/items/5209062A5209047O",
    "distanceFromStart": 851.0
  },
  "links": [
    {
      "href": "http://www.opengis.net/def/profile/ogc/0/rel-as-uri",
      "rel": "profile",
      "title": "Profile used in the response"
    }
  ]
}
----
====

:req: rel-as-link
[#{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In the profile "rel-as-link" (`\http://www.opengis.net/def/profile/OGC/0/rel-as-link`) a reference in the response SHALL be represented by an object with the property "href" (the URI of the referenced resource) and, optionally, a property "title" (a human readable label, e.g. for a clickable link).
|===

How the object is represented in a media type will depend on the media type. For example, in HTML it could be `<a href="{href}">{title}</a>`, in XML it could be an XLink, in JSON it could be an object with the properties. 

[[example_14_3]]
.Encoding of a road accident feature in GeoJSON and profile "rel-as-link"
====
The feature includes a "roadSegment" property that is a reference to the road segment on which the accident occurred.

[source,JSON]
----
{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      7.2789399,
      50.7772485
    ]
  },
  "properties": {
    "timeOfAccident": "2019-02-05T07:00:00Z",
    "roadSegment": {
        "href": "https://example.com/apis/roads/collections/roadsegments/items/5209062A5209047O",
        "title": "Road L333, Segment 5209062A5209047O, Hennef"
    },
    "distanceFromStart": 851.0
  },
  "links": [
    {
      "href": "http://www.opengis.net/def/profile/ogc/0/rel-as-link",
      "rel": "profile",
      "title": "Profile used in the response"
    }
  ]
}
----
====

Servers will typically not support the profile "rel-as-link" for media types that do not have an adequate representation for such an object. Examples include CSV or FlatGeobuf.

"rel-as-link" will typically be the most useful representation, if a human user interacts with the resource. This is because of the possibility to include a descriptive label of the referenced resource. Of course, this only applies if the server can provide a meaningful title for each link, in which case this information can help the user to understand the referenced resource.

:rec: default
[#{req-class}_{rec}]
[width="90%",cols="2,7a"]
|===
^|*Recommendation {counter:rec-num}* |/rec/{req-class}/{rec}
^|A |The default value of the query parameter "profile" SHOULD include the profile "rel-as-link", if the server can provide meaningful link titles.
|===
