:req-class: profile-references
[#rc_{req-class}]
== Requirements Class "Profiles for references"

The Requirements Class "Profiles for references" specifies three profiles for representing references to other resources.

The requirements stated in this Standard cover only simple cases. More complex cases, such as references to geospatial data in different collections, are not covered. 

[cols="2,7",width="90%"]
|===
^|*Requirements Class* |http://www.opengis.net/spec/{standard}/{m_n}/req/{req-class} 
|Target type |Collection of data
|Indirect Dependency |<<rc_returnables-and-receivables>>
|Indirect Dependency |<<rc_profile-parameter>>
|Indirect Dependency |<<rc_references>>
|===

:req: ref-profiles
[#req_{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |If the Returnables and Receivables schema of a collection includes a property with role „reference“, the GET operation on resources providing representations of the data SHALL provide the query parameter profile.
|===

For features, the query parameter "profile" will be applicable to the GET operation on the paths `/collections/{collectionId}/items` and `/collections/{collectionId}/items/{resourceId}`.

:req: rel-as-key
[#req_{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In the profile "rel-as-key" (`\http://www.opengis.net/def/profile/OGC/0/rel-as-key`) a reference in the response SHALL be represented by the `resourceId` of the referenced resource (a string or integer, depending on the type of the identifier property in the referenced collection), if the property with role "reference" has the keyword "x-ogc-collectionId".
|===

[[example_14_1]]
.Encoding of a road accident feature in GeoJSON and profile "rel-as-key"
====
The examples in this Clause use the <<example_9_1,example road accident feature schema>>.

[source,JSON]
----
{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      7.2789399,
      50.7772485
    ]
  },
  "properties": {
    "timeOfAccident": "2019-02-05T07:00:00Z",
    "roadSegment": "5209062A5209047O",
    "distanceFromStart": 851.0
  },
  "links": [
    {
      "href": "http://www.opengis.net/def/profile/ogc/0/rel-as-key",
      "rel": "profile",
      "title": "Profile used in the response"
    }
  ]
}
----
====

:req: rel-as-uri
[#req_{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In the profile "rel-as-uri" (`\http://www.opengis.net/def/profile/OGC/0/rel-as-uri`) a reference in the response SHALL be represented by an HTTP(S) URI.
|===

[[example_14_2]]
.Encoding of the same road accident feature for the profile "rel-as-uri"
====
[source,JSON]
----
{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      7.2789399,
      50.7772485
    ]
  },
  "properties": {
    "timeOfAccident": "2019-02-05T07:00:00Z",
    "roadSegment": "https://example.com/apis/roads/collections/roadsegments/items/5209062A5209047O",
    "distanceFromStart": 851.0
  },
  "links": [
    {
      "href": "http://www.opengis.net/def/profile/ogc/0/rel-as-uri",
      "rel": "profile",
      "title": "Profile used in the response"
    }
  ]
}
----
====

:req: rel-as-link
[#req_{req-class}_{req}]
[width="90%",cols="2,7a"]
|===
^|*Requirement {counter:req-num}* |/req/{req-class}/{req}
^|A |In the profile "rel-as-link" (`\http://www.opengis.net/def/profile/OGC/0/rel-as-link`) a reference in the response SHALL be represented by an object with the property "href" (the URI of the referenced resource) and, optionally, a property "title" (a human readable label, e.g. for a clickable link).
|===

How the object is represented in a media type will depend on the media type. For example, in HTML it could be `<a href="{href}">{title}</a>`, in XML it could be an XLink, in JSON it could be an object with the properties. 

[[example_14_3]]
.Encoding of a road accident feature in GeoJSON and profile "rel-as-link"
====
The feature includes a "roadSegment" property that is a reference to the road segment on which the accident occurred.

[source,JSON]
----
{
  "type": "Feature",
  "id": 1,
  "geometry": {
    "type": "Point",
    "coordinates": [
      7.2789399,
      50.7772485
    ]
  },
  "properties": {
    "timeOfAccident": "2019-02-05T07:00:00Z",
    "roadSegment": {
        "href": "https://example.com/apis/roads/collections/roadsegments/items/5209062A5209047O",
        "title": "Road L333, Segment 5209062A5209047O, Hennef"
    },
    "distanceFromStart": 851.0
  },
  "links": [
    {
      "href": "http://www.opengis.net/def/profile/ogc/0/rel-as-link",
      "rel": "profile",
      "title": "Profile used in the response"
    }
  ]
}
----
====

Servers will typically not support the profile "rel-as-link" for media types that do not have an adequate representation for such an object. Examples include CSV or FlatGeobuf.

"rel-as-link" will typically be the most useful representation, if a human user interacts with the resource. This is because of the possibility to include a descriptive label of the referenced resource. Of course, this only applies if the server can provide a meaningful title for each link, in which case this information can help the user to understand the referenced resource.

:rec: default
[#rec_{req-class}_{rec}]
[width="90%",cols="2,7a"]
|===
^|*Recommendation {counter:rec-num}* |/rec/{req-class}/{rec}
^|A |The default value of the query parameter "profile" SHOULD include the profile "rel-as-link", if the server can provide meaningful link titles.
|===
