== Conformance

This standard defines the following requirements classes, 
grouped by their standardization target:

* Web API
** <<rc_filter,Filter>>
** <<rc_features-filter,Features Filter>>
* Filter expressions
** <<rc_simple-cql,Simple CQL>>
** <<rc_enhanced-spatial-operators,Enhanced Spatial Operators>>
** <<rc_enhanced-temporal-operators,Enhanced Temporal Operators>>
** <<rc_functions,Functions>>
** <<rc_arithmetic,Arithmetic expressions>>
** <<rc_arrays,Arrays>>
* Representations of a filter expression
** <<rc_cql-text,CQL Text encoding>>
** <<rc_cql-json,CQL JSON encoding>>

The <<rc_filter,Filter>> requirements class defines a set of HTTP query
parameters that may be used to specify complex filter expressions on
HTTP requests.  The specific set of parameters defined in this requirements
class is:

* `filter` - The filter expression.
* `filter-lang` - The language used in the filter expression.
* `filter-crs` - The coordinate reference system used in the filter expression.

This requirements class also defines the Queryables resource (at paths
`/queryables` and `/collections/{collectionId}/queryables`) that can be
used to determine the list of property names and types that may be used
to construct filter expressions.

The <<rc_features-filter,Features Filter>> requirements class defines the
binding between the <<rc_filter,Filter>> requirements class and the
<<OAFeat-1,OGC API - Features - Part 1: Core>> standard.

The <<rc_simple-cql,Simple CQL>> requirements class defines the minimal subset
of the Common Query Language (CQL) that all implementations must support
("Simple CQL"). Simple CQL is intended to be a minimal useful set of
predicates that support enhanced fine-grained read-access to collections of
resources.  In this case, "enhanced" means filtering capabilities beyond those
supported by the core OGC API Common standard (i.e., `bbox`, `datetime`
and optionally collection-specific properties).

NOTE: OGC API - Common is still in draft form and is not an official OGC standard.

The specific set of operators defined in this requirements class is:

* Logical operators:
** and
** or
** not
* Comparison operators:
** equal to
** less than
** less than or equal to
** greater than
** greater than or equal to
** like
** is null
** between
** in
* Spatial operators:
** intersects
* Temporal operators:
** anyinteracts

NOTE: The `anyinteracts` temporal operator is defined in this document by requirement <<req_simple-cql_temporal-predicate,/req/simple-cql/temporal-predicate>>.

An encoding of CQL may be used as the value of the filter parameters defined
in the <<rc_filter,Filter>> requirements class.

The <<rc_enhanced-spatial-operators,Enhanced Spatial Operators>> requirements
class specifies requirements for servers that support spatial operators in
addition to the `intersects` operator that is defined in the
<<simple-cql_spatial-predicates,Simple CQL>> requirements class. The list of
additional spatial operators that must be supported is:

* equals
* disjoint
* touches
* within
* overlaps
* crosses
* contains

The <<rc_enhanced-temporal-operators,Enhanced Temporal Operators>> requirements
class specifies requirements for servers that support temporal operators in
addition to the `anyinteracts` operator defined in the
<<simple-cql_temporal-predicates,Simple CQL>> requirements class. The list of
additional temporal operators that must be supported is:

* after
* before
* begins
* begunby
* tcontains
* during
* endedby
* ends
* tequals
* meets
* metby
* toverlaps
* overlappedby
* intersects

The <<rc_functions,Functions>> requirements class specifies requirements for
supporting function calls (e.g. min, max, etc.) in a CQL expression. Function
calls are the primary means of extending the language. This requirements class
also defined a Functions resource (at path `/functions`) that may be used to
discover the list of available functions.

The <<rc_arithmetic,Arithmetic operators>> requirements class specifies
requirements for supporting the standard set of arithmetic operators,
latexmath:[+, -, *, /] in a CQL expression.

The <<rc_arrays,Arrays>> requirements class specifies
requirements for comparison operators for sets of values. 
The operators that must be supported are:

* aequals 
* acontains
* containedby
* aoverlaps

The <<rc_cql-text,CQL Text encoding>> requirements class defines
a text encoding for CQL. Such an encoding is suitable for use with HTTP query
parameters such as the `filter` parameter defined by the <<rc_filter,Filter>>
requirements class.

The <<rc_cql-json,CQL JSON encoding>> requirements class defines
a JSON encoding for CQL. Such as encoding is suitable for use with as the
body of an HTTP POST request.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_filter,Filter>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter
|<<ats_features-filter,Features Filter>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter
|<<ats_simple-cql,Simple CQL>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/simple-cql
|<<ats_enhanced-spatial-operators,Enhanced Spatial Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/enhanced-spatial-operators
|<<ats_enhanced-temporal-operators,Enhanced Temporal Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/enhanced-temporal-operators
|<<ats_functions,Functions>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/functions
|<<ats_arithmetic,Arithmetic>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/arithmetic
|<<ats_arrays,Arrays>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/arrays
|<<ats_cql-text,CQL Text encoding>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/cql-text
|<<ats_cql-json,CQL JSON encoding>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/cql-json 
|===

=== Roadmap

The content of this sub-clause is informative.

Because CQL is not exclusively useful for features, it is anticipated that the
following requirements classes:

* <<rc_filter,Filter>>
* <<rc_simple-cql,Simple CQL>>
* <<rc_enhanced-spatial-operators,Enhanced Spatial Operators>>
* <<rc_enhanced-temporal-operators,Enhanced Temporal Operators>>
* <<rc_functions,Functions>>
* <<rc_arithmetic,Arithmetic expressions>>
* <<rc_arrays,Arrays>>
* <<rc_cql-text,CQL Text encoding>>
* <<rc_cql-json,CQL JSON encoding>>

will eventually become parts of the OGC API Common suite of standards thus
leaving the <<rc_features-filter,Features Filter>> requirements class as part
3 of the OGC API Features specifications.




