[[cql-core]]
== Requirements Class "Simple CQL"

[[simple-cql-overview]]
=== Overview

include::requirements/requirements_class_simple-cql.adoc[]

This clause defines the core of a query language called `Common Query Language`
(CQL) that may be used to construct filter expressions.  Subsequent clauses
define several optional encodings of CQL as well additional filtering 
capabilities.

[[simple-cql_filter-expression]]
=== CQL filter expression

A CQL filter expression is an expression that defines a logically connected
set of predicates that are evaluated for each item of a collection.  A CQL 
filter expression produces a Boolean value of `TRUE` is the collection item
satisfies all the requirements of the expression; otherwise the CQL filter 
expression evaluates to `FALSE'.

A CQL filter expression can be constructed by logically connecting zero or more
of the following classes of predicates:

* comparison predicates
* spatial predicates
* temporal predicates

include::requirements/simple-cql/REQ_cqlfilter.adoc[]

[[simple-cql_literals]]
=== Literal values

A literal value is any part of an CQL filter expression that is be used
exactly as it is specified in the expression.  Literal values include
character string, numeric, boolean, geometric or temporal values.

include::requirements/simple-cql/REQ_literals.adoc[]

[[simple-cql_property]]
=== Property reference

Properties in an object being evaluated in the CQL filter expression can be
referenced by their name.

include::requirements/simple-cql/REQ_property.adoc[]

[[simple-cql_comparison-predicates]]
=== Comparison predicates

A comparison predicate evaluates two scalar expressions to determine if the
expressions satisfy the specified comparison operator.  If the requirements
of the operator are satisfied, then the prediate evaluates to the Boolean
value `TRUE`; otherwise the predicate evaluates to the Boolean value `FALSE`;

include::requirements/simple-cql/REQ_comparison-predicates.adoc[]

The like predicate tests whether the value of a scalar expression matches
the specified pattern.  If the value matches the pattern then the predicate
evaluates to the Boolean value `TRUE`; otherwise the like predicate evaluates
to the Boolean value `FALSE`. 

The between predicate tests whether the value of a scalar expression lies within
the specified range.  The BETWEEN operator is inclusive.  If the value lies
within the specified range then the predicate evaluates to the Boolean value
`TRUE`; otherwise the between predicate evalues to the Boolean value `FALSE`.

A list predicate tests, for equality, the value of a scalar expression against
a list of literal values of the same type.  If the value of the named property
is equal to one or more of the values in the list of literals, the list
predicate evaluates to the Boolean value `TRUE`; otherwise the list predicate
evaluates to the Boolean value `FALSE`.

include::requirements/simple-cql/REQ_in-predicate-items.adoc[]

The null predicate tests whether the value of a scalar expression is null.  If
the value of the scalar expression is null, the null predicate evaluates to the
Boolean value `TRUE`; otherwise the null predicate evaluates to the Boolean
value `FALSE`.

[[simple-cql_spatial]]
=== Spatial predicates

A spatial predicate evaluates two geometry-valued expressions to determine if
the expressions satsify the requirements of the specified spatial operator.  
If the requirements of the operator are satisfied, then the predicate evaluates
to the Boolean value `TRUE`; otherwise the predicate evaluates to the Boolean 
value `FALSE`.

include::requirements/simple-cql/REQ_spatial-predicates.adoc[]

=== CRS considerations

include::requirements/simple-cql/REQ_crs_crs84.adoc[]

include::requirements/simple-cql/REQ_crs-other.adoc[]

[[simple-cql_temporal]]
=== Temporal predicates

A temporal predicate evaluates two time-valued expressions to determine if
the expressions satsify the requirements of the specified temporal operator.  
If the requirements of the operator are satisfied, then the predicate evaluates
to the Boolean value `TRUE`; otherwise the predicate evaluates to the Boolean
value `FALSE`;

include::requirements/simple-cql/REQ_temporal-predicates.adoc[]

=== Simple CQL Encodings

This standard defines a <<simple-cql-text,text>> encoding and a 
<<simple-cql-json,JSON>> encoding of CQL and makes the following 
recommendations:

include::recommendations/simple-cql/REC_simple-cql-text.adoc[]

include::recommendations/simple-cql/REC_simple-cql-json.adoc[]
