[[cql-core]]
== Requirements Class "Simple CQL"

[[simple-cql-overview]]
=== Overview

include::requirements/requirements_class_simple-cql.adoc[]

This clause defines the core of a query language called `Common Query Language`
(CQL) that may be used to construct filter expressions. This core is called Simple CQL.

Subsequent clauses define additional filtering capabilities as well as several
encodings of CQL.

[[simple-cql_filter-expression]]
=== CQL filter expression

A CQL filter expression is an expression that defines a logically connected
set of predicates that are evaluated for each item of a collection.

A predicate is an expression that evaluates to the Boolean values of `TRUE`
or `FALSE` or that evaluates to the value `NULL` when dealing with unknown
values.

If a predicate evaluates to `TRUE` for an item, the item qualifies for
further processing such as presentation in the result set, being passed on
to the next predicate in the filter for further evaluation, and so forth.

If the predicate evaluates to `FALSE` or `NULL` for an item, the item is not
available for further processing.

A collection item that satisfies ALL the requirements of a CQL filter expression
evaluates to a Boolean value of `TRUE`; otherwise the CQL filter expression
evaluates to `FALSE`.

include::requirements/simple-cql/REQ_cqlfilter.adoc[]

A Simple CQL filter expression can be constructed by logically connecting one
or more of the following classes of predicates:

* comparison predicates
* spatial predicates
* temporal predicates

Support for the parts of CQL that are not part of Simple CQL is added in additional
requirements classes in <<cql-enhancements>>:

* The rule `arrayPredicate` is added by requirements class <<rc_arrays,Arrays>>;
* The rule `function` is added by requirements class <<rc_functions,Functions>>;
* The rule `arithmeticExpression` is added by requirements class <<rc_arithmetic,Arithmetic Expressions>>;
* The additional values in rule `spatialOperator` are added by requirements class <<rc_spatial-operators,Spatial Operators>>;
* The additional values in rule `temporalOperator` are added by requirements class <<rc_temporal-operators,Temporal Operators>>.

Examples of Simple CQL filter expressions are included in the subsequent sub-clauses.

[[simple-cql_literals]]
=== Literal values

A literal value is any part of an CQL filter expression that is used
exactly as it is specified in the expression. Literal values include:

* character strings (rule `characterLiteral`),
* numbers including integers and floating point values (rule `numericLiteral`),
* booleans (rule `booleanLiteral`),
* spatial geometries like points, line strings or polygons (rule `spatialLiteral`) and
* temporal geometries like instants or intervals (rule `temporalLiteral`).

[[example_8_1]]
.Literal examples
====

* character string
----
'This is a literal string.'
----
* number
----
-100
3.14159
----
* boolean
----
true
false
----
* spatial geometry (WKT)
----
POLYGON((43.5845 -79.5442, 43.6079 -79.4893, 43.5677 -79.4632, 43.6129 -79.3925, 43.6223 -79.3238, 43.6576 -79.3163, 43.7945 -79.1178, 43.8144 -79.1542, 43.8555 -79.1714, 43.7509 -79.6390, 43.5845 -79.5442))
----
* spatial geometry (JSON)
[source,JSON]
----
{
   "type": "Polygon",
   "coordinates": [
       [
          [43.5845,-79.5442],
          [43.6079,-79.4893],
          [43.5677,-79.4632],
          [43.6129,-79.3925],
          [43.6223,-79.3238],
          [43.6576,-79.3163],
          [43.7945,-79.1178],
          [43.8144,-79.1542],
          [43.8555,-79.1714],
          [43.7509,-79.6390],
          [43.5845,-79.5442]
      ]
   ]
}
----
* temporal geometry (instants, text)
----
DATE('1969-07-20')
TIMESTAMP('1969-07-20T20:17:40Z')
----
* temporal geometry (instants, JSON)
[source,JSON]
----
{ "date": "1969-07-20" }
{ "timestamp": "1969-07-20T20:17:40Z" }
----
* temporal geometry (intervals, text)
----
INTERVAL('1969-07-16', '1969-07-24')
INTERVAL('1969-07-16T05:32:00Z', '1969-07-24T16:50:35Z')
INTERVAL('2019-09-09', '..')
----
* temporal geometry (intervals, JSON)
[source,JSON]
----
{ "interval": [ "1969-07-16", "1969-07-24" ] }
{ "interval": [ "1969-07-16T05:32:00Z", "1969-07-24T16:50:35Z" ] }
{ "interval": [ "2019-09-09", ".." ] }
----
====

For spatial and temporal geometries existing representations are used:

* Spatial geometry:
** Text: an https://portal.ogc.org/files/?artifact_id=25355[OGC Well-Known Text (WKT)] literal
** JSON: a https://datatracker.ietf.org/doc/html/rfc7946#section-3.1[GeoJSON geometry] object
* Temporal instant:
** Text: a `DATE` or `TIMESTAMP` function with a https://datatracker.ietf.org/doc/html/rfc3339#section-5.6[RFC 3339 literal string]
** JSON: an object with a `date` or `timestamp` member with a https://datatracker.ietf.org/doc/html/rfc3339#section-5.6[RFC 3339 literal string value]
* Temporal interval:
** Text: an `INTERVAL` function with two temporal instants as parameters
** JSON: an object with an `interval` member with an array of https://datatracker.ietf.org/doc/html/rfc3339#section-5.6[RFC 3339 literal string] values (or ".." for an open end)

All temporal literals are in UTC ("Z").

[[simple-cql_property]]
=== Property references

Properties in an object being evaluated in the CQL filter expression can be
referenced by their name (rule `propertyName`).

include::requirements/simple-cql/REQ_property.adoc[]

For example, a property name used in a scalar expression (rule `scalarExpression`)
has to be a queryable of type `string`, `number`, `integer` or `boolean`.

[[example_8_2]]
.Property reference in a scalar expression
====
In this example, the property `windSpeed` is used in a function that returns a number.
----
avg(windSpeed)
----

[source,JSON]
----
{ "function": { "name": "avg", "arguments": [ { "property": "windSpeed" } ] } }
----
====

[[simple-cql_comparison-predicates]]
=== Comparison predicates

include::requirements/simple-cql/REQ_binary-comparison-predicate.adoc[]

include::recommendations/simple-sql/PER_time-instant-comparisons.adoc[]

[[example_8_3]]
.Binary comparison predicates
====
----
city='Toronto'
----

[source,JSON]
----
{ "=": [ { "property": "city" }, "Toronto" ] }
----

----
avg(windSpeed) < 4
----

[source,JSON]
----
{
  "<": [
    { "function": { "name": "avg", "arguments": [ { "property": "windSpeed" } ] } },
    4
  ]
}
----

----
balance-150.0 > 0
----

[source,JSON]
----
{
  ">": [
    { "-": [ { "property": "balance" }, 150.0 ] },
    0
  ]
}
----

----
updated >= date('1970-01-01')
----

[source,JSON]
----
{
  "gte": [ { "property": "updated" }, { "date": "1970-01-01" } ]
}
----
====

include::requirements/simple-cql/REQ_like-predicate.adoc[]

[[example_8_4]]
.Example of a LIKE predicate
====
----
name LIKE 'Smith%' 
----

[source,JSON]
----
{"like": [ { "property": "name" }, "Smith%" ] }
----
====

include::requirements/simple-cql/REQ_between-predicate.adoc[]

[[example_8_5]]
.Examples of a BETWEEN predicate
====
----
depth BETWEEN 100.0 and 150.0
----

[source,JSON]
----
{
  "between": {
     "value": { "property": "depth" },
     "lower": 100.0,
     "upper": 150.0
  }
}
----
====

include::requirements/simple-cql/REQ_in-predicate.adoc[]

[[example_8_6]]
.Examples of a IN predicate
====
----
cityName IN ('Toronto','Frankfurt','Tokyo','New York')
----

[source,JSON]
----
{
  "in": {
     "value": { "property": "cityName" },
     "list": [ "Toronto", "Frankfurt", "Tokyo", "New York" ]
  }
}
----

----
category NOT IN (1,2,3,4)
----

[source,JSON]
----
{
  "not": {
    "in": {
       "value": { "property": "category" },
       "list": [ 1, 2, 3, 4 ]
    }
  }
}
----
====

include::requirements/simple-cql/REQ_null-predicate.adoc[]

[[example_8_7]]
.Examples of a NULL predicate
====
----
geometry IS NOT NULL
----

[source,JSON]
----
{ "not": { "isNull" : { "property": "geometry" } } }
----
====

=== CQL Encodings

This OGC API - Features - Part 3 standard defines a <<simple-cql-text,text>>
encoding and a <<simple-cql-json,JSON>> encoding of CQL that covers Simple CQL
and all enhanced capabilities specified in the next clause.
