== Conformance

This standard defines the following requirements classes, 
grouped by their standardization target:

* Web API
** <<rc_filter,Filter>>
** <<rc_features-filter,Features Filter>>
* Filter expressions
** <<rc_basic-cql2,Basic CQL2>>
** <<rc_advanced-comparison-operators,Advanced Comparison Operators>>
** <<rc_basic-spatial-operators,Basic Spatial Operators>>
** <<rc_spatial-operators,Spatial Operators>>
** <<rc_temporal-operators,Temporal Operators>>
** <<rc_array-operators,Array Operators>>
** <<rc_property-property,Property-Property Comparisons>>
** <<rc_functions,Custom Functions>>
** <<rc_arithmetic,Arithmetic Expressions>>
* Representations of a filter expression
** <<rc_cql2-text,CQL2 Text encoding>>
** <<rc_cql2-json,CQL2 JSON encoding>>

The <<rc_filter,Filter>> requirements class defines a set of HTTP query
parameters that may be used to specify complex filter expressions on
HTTP requests.  The specific set of parameters defined in this requirements
class is:

* `filter` - The filter expression.
* `filter-lang` - The language used in the filter expression.
* `filter-crs` - The coordinate reference system used in the filter expression, if Part 2 is supported.

This requirements class also defines the Queryables resource (at paths
`/queryables` and `/collections/{collectionId}/queryables`) that can be
used to determine the list of property names and types that may be used
to construct filter expressions.

The <<rc_features-filter,Features Filter>> requirements class defines the
binding between the <<rc_filter,Filter>> requirements class and the
<<OAFeat-1,OGC API - Features - Part 1: Core>> standard.

The <<rc_basic-cql2,Basic CQL2>> requirements class defines the minimal subset
of the Common Query Language (CQL2) that all implementations must support
("Basic CQL2"). Basic CQL2 is intended to be a minimal useful set of
predicates that support enhanced fine-grained read-access to collections of
resources.  In this case, "enhanced" means filtering capabilities beyond those
supported by the OGC API Common standard (i.e., `bbox`, `datetime`
and optionally collection-specific properties).

NOTE: OGC API Common is still in draft form and is not an official OGC standard.

The specific set of operators defined in this requirements class is:

* Logical operators:
** and
** or
** not
* Comparison operators:
** equal to
** not equal to
** less than
** less than or equal to
** greater than
** greater than or equal to
** is null

Basic CQL2 only requires support for property-literal comparisons. That means that servers only has to support property references as expressions on the left hand side of an operator, and only literal values as expressions on the right hand side.

An encoding of CQL2 may be used as the value of the filter parameters defined
in the <<rc_filter,Filter>> requirements class.

The <<rc_advanced-comparison-operators,Advanced Comparison Operators>> requirements class specifies additional comparison operators:

* like
* between
* in

In addition, requirements to support the following pre-defined string functions:

* upper
* lower

The <<rc_basic-spatial-operators,Basic Spatial Operators>> requirements class specifies minimal requirements for servers that support spatial operators. Only the following spatial operator must be supported:

* s_intersects

The <<rc_spatial-operators,Spatial Operators>> requirements class specifies requirements for servers that support a richer set of spatial operators.  The list of additional spatial operators that must be supported is:

* s_contains
* s_crosses
* s_disjoint
* s_equals
* s_overlaps
* s_touches
* s_within

The <<rc_temporal-operators,Temporal Operators>> requirements
class specifies requirements for servers that support temporal operators. 
The list of temporal operators that must be supported is:

* t_after
* t_before
* t_contains
* t_disjoint
* t_during
* t_equals
* t_finishedby
* t_finishes
* t_intersects
* t_meets
* t_metby
* t_overlappedby
* t_overlaps
* t_startedby
* t_starts

The <<rc_array-operators,Array Operators>> requirements class specifies
requirements for comparison operators for sets of values. 
The operators that must be supported are:

* a_containedby
* a_contains
* a_equals 
* a_overlaps

The <<rc_property-property,Property-Property Comparisons>> requirements class drops the permission to restrict expressions on the left hand side to properties and to restrict expressions on the right hand side to literal values. This supports property-property, but also literal-literal or literal-property comparisons.

The <<rc_functions,Custom Functions>> requirements class specifies requirements for
supporting custom function calls (e.g. min, max, etc.) in a CQL2 expression. Function
calls are the primary means of extending the language. This requirements class
also defined a Functions resource (at path `/functions`) that may be used to
discover the list of available functions.

The <<rc_arithmetic,Arithmetic Expressions>> requirements class specifies
requirements for supporting the standard set of arithmetic operators,
latexmath:[+, -, *, /] in a CQL2 expression.

The <<rc_cql2-text,CQL2 Text encoding>> requirements class defines
a text encoding for CQL2. Such an encoding is suitable for use with HTTP query
parameters such as the `filter` parameter defined by the <<rc_filter,Filter>>
requirements class.

The <<rc_cql2-json,CQL2 JSON encoding>> requirements class defines
a JSON encoding for CQL2. Such as encoding is suitable for use as the
body of an HTTP POST request.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_filter,Filter>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/filter
|<<ats_features-filter,Features Filter>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/features-filter
|<<ats_basic-cql2,Basic CQL2>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/basic-cql
|<<ats_advanced-comparison-operators,Advanced Comparison Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/advanced-comparison-operators
|<<ats_basic-spatial-operators,Basic Spatial Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/basic-spatial-operators
|<<ats_spatial-operators,Spatial Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/spatial-operators
|<<ats_temporal-operators,Temporal Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/temporal-operators
|<<ats_array-operators,Array Operators>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/array-operators
|<<ats_property-property,Property-Property Comparisons>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/property-property
|<<ats_functions,Custom Functions>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/functions
|<<ats_arithmetic,Arithmetic Expressions>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/arithmetic
|<<ats_cql2-text,CQL2 Text encoding>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/cql2-text
|<<ats_cql2-json,CQL2 JSON encoding>> |http://www.opengis.net/spec/ogcapi-features-3/1.0/conf/cql2-json 
|===

=== Roadmap

The content of this sub-clause is informative.

Because CQL2 is not exclusively useful for features, it is anticipated that the
following requirements classes:

* <<rc_filter,Filter>>
* <<rc_basic-cql2,Basic CQL2>>
* <<rc_advanced-comparison-operators,Advanced Comparison Operators>>
* <<rc_property-property,Property-Property Comparisons>>
* <<rc_basic-spatial-operators,Basic Spatial Operators>>
* <<rc_spatial-operators,Spatial Operators>>
* <<rc_temporal-operators,Temporal Operators>>
* <<rc_array-operators,Arrays Operators>>
* <<rc_functions,Custom Functions>>
* <<rc_arithmetic,Arithmetic Expressions>>
* <<rc_cql2-text,CQL2 Text encoding>>
* <<rc_cql2-json,CQL2 JSON encoding>>

will eventually become parts of the OGC API Common suite of standards thus
leaving the <<rc_features-filter,Features Filter>> requirements class as part
3 of the OGC API Features specifications.




