[[cql-core]]
== Requirements Class "Simple CQL"

[[simple-cql-overview]]
=== Overview

include::requirements/requirements_class_simple-cql.adoc[]

This clause defines the core of a query language called `Common Query Language`
(CQL) that may be used to construct filter expressions. This core is called Simple CQL.

Subsequent clauses define additional filtering capabilities as well as several
encodings of CQL.

[[simple-cql_filter-expression]]
=== CQL filter expression

A CQL filter expression is an expression that defines a logically connected
set of predicates that are evaluated for each item of a collection.

A predicate is an expression that evaluates to the Boolean values of `TRUE`
or `FALSE` or that evaluates to the value `NULL` when dealing with unknown
values.

If a predicate evaluates to `TRUE` for an item, the item qualifies for
further processing such as presentation in the result set, being passed on
to the next predicate in the filter for further evaluation, and so forth.

If the predicate evaluates to `FALSE` or `NULL` for an item, the item is not
available for further processing.

A collection item that satisfies ALL the requirements of a CQL filter expression
evaluates to a Boolean value of `TRUE`; otherwise the CQL filter expression
evaluates to `FALSE`.

include::requirements/simple-cql/REQ_cqlfilter.adoc[]

A Simple CQL filter expression can be constructed by logically connecting one
or more of the following classes of predicates:

* comparison predicates
* spatial predicates
* temporal predicates

Support for the parts of CQL that are not part of Simple CQL is added in additional
requirements classes in <<cql-enhancements>>:

* The rule `arrayPredicate` is added by requirements class <<rc_arrays,Arrays>>;
* The rule `function` is added by requirements class <<rc_functions,Functions>>;
* The rule `arithmeticExpression` is added by requirements class <<rc_arithmetic,Arithmetic Expressions>>;
* The additional values in rule `spatialOperator` are added by requirements class <<rc_enhanced-spatial-operators,Enhanced Spatial Operators>>;
* The additional values in rule `temporalOperator` are added by requirements class <<rc_enhanced-temporal-operators,Enhanced Temporal Operators>>.

Examples of Simple CQL filter expressions are included in the subsequent sub-clauses.

[[simple-cql_literals]]
=== Literal values

A literal value is any part of an CQL filter expression that is used
exactly as it is specified in the expression. Literal values include:

* character strings (rule `characterLiteral`),
* numbers including integers and floating point values (rule `numericLiteral`),
* booleans (rule `booleanLiteral`),
* spatial geometries like points, line strings or polygons (rule `spatialLiteral`) and
* temporal geometries like instants or intervals (rule `temporalLiteral`).

[[example_8_1]]
.Literal examples
====

* character string
----
'This is a literal string.'
----
* number
----
-100
3.14159
----
* boolean
----
true
false
t
f
----
* spatial geometry (WKT)
----
POLYGON((43.5845 -79.5442, 43.6079 -79.4893, 43.5677 -79.4632, 43.6129 -79.3925, 43.6223 -79.3238, 43.6576 -79.3163, 43.7945 -79.1178, 43.8144 -79.1542, 43.8555 -79.1714, 43.7509 -79.6390, 43.5845 -79.5442))
----
* spatial geometry (JSON)
[source,JSON]
----
{
   "type": "Polygon",
   "coordinates": [
       [
          [43.5845,-79.5442],
          [43.6079,-79.4893],
          [43.5677,-79.4632],
          [43.6129,-79.3925],
          [43.6223,-79.3238],
          [43.6576,-79.3163],
          [43.7945,-79.1178],
          [43.8144,-79.1542],
          [43.8555,-79.1714],
          [43.7509,-79.6390],
          [43.5845,-79.5442]
      ]
   ]
}
----
* temporal geometry (instants, text)
----
1969-07-20
1969-07-20T20:17:40Z
----
* temporal geometry (instants, JSON)
[source,JSON]
----
"1969-07-20"
"1969-07-20T20:17:40Z"
----
* temporal geometry (intervals, text)
----
1969-07-16/1969-07-24
1969-07-16T05:32:00Z/1969-07-24T16:50:35Z
2019-09-09/..
----
* temporal geometry (intervals, JSON)
[source,JSON]
----
[ "1969-07-16", "1969-07-24" ]
[ "1969-07-16T05:32:00Z", "1969-07-24T16:50:35Z" ]
[ "2019-09-09", ".." ]
----
====

NOTE: The current BNF rule for temporal literals supports timestamps in any time zone. Should this be restricted to UTC ("Z"), at least in Simple CQL? See https://github.com/opengeospatial/ogcapi-features/issues/483[issue 483].

[[simple-cql_property]]
=== Property references

Properties in an object being evaluated in the CQL filter expression can be
referenced by their name (rule `propertyName`).

include::requirements/simple-cql/REQ_property.adoc[]

For example, a property name used in a scalar expression (rule `scalarExpression`)
has to be a queryable of type `string`, `number`, `integer` or `boolean`.

[[example_8_2]]
.Property reference in a scalar expression
====
In this example, the property `windSpeed` is used in a function that returns a number.
----
avg(windSpeed)
----

[source,JSON]
----
{ "function": { "name": "avg", "arguments": [ { "property": "windSpeed" } ] } }
----
====

[[simple-cql_comparison-predicates]]
=== Comparison predicates

include::requirements/simple-cql/REQ_binary-comparison-predicate.adoc[]

[[example_8_3]]
.Binary comparison predicates
====
----
city='Toronto'
----

[source,JSON]
----
{ "eq": [ { "property": "city" }, "Toronto" ] }
----

----
avg(windSpeed) < 4
----

[source,JSON]
----
{
  "lt": [
    { "function": { "name": "avg", "arguments": [ { "property": "windSpeed" } ] } },
    4
  ]
}
----

----
balance-150.0 > 0
----

[source,JSON]
----
{
  "gt": [
    { "-": [ { "property": "balance" }, 150.0 ] },
    0
  ]
}
----
====

include::requirements/simple-cql/REQ_like-predicate.adoc[]

[[example_8_4]]
.Example of a LIKE predicate
====
----
name LIKE 'Smith.' SINGLECHAR '.' NOCASE true
----

[source,JSON]
----
{
  "like": [
    { "property": "name" },
    "Smith."
  ],
  "singleChar": ".",
  "nocase": true
}
----
====

include::requirements/simple-cql/REQ_between-predicate.adoc[]

[[example_8_5]]
.Examples of a BETWEEN predicate
====
----
depth BETWEEN 100.0 and 150.0
----

[source,JSON]
----
{
  "between": {
     "value": { "property": "depth" },
     "lower": 100.0,
     "upper": 150.0
  }
}
----
====

include::requirements/simple-cql/REQ_in-predicate.adoc[]

[[example_8_6]]
.Examples of a IN predicate
====
----
cityName IN ('Toronto','Frankfurt','Tokyo','New York') NOCASE false
----

[source,JSON]
----
{
  "in": {
     "value": { "property": "cityName" },
     "list": [ "Toronto", "Frankfurt", "Tokyo", "New York" ],
     "nocase": false
  }
}
----

----
category NOT IN (1,2,3,4)
----

[source,JSON]
----
{
  "not": {
    "in": {
       "value": { "property": "category" },
       "list": [ 1, 2, 3, 4 ]
    }
  }
}
----
====

include::requirements/simple-cql/REQ_null-predicate.adoc[]

[[example_8_7]]
.Examples of a NULL predicate
====
----
geometry IS NOT NULL
----

[source,JSON]
----
{ "not": { "isNull" : { "property": "geometry" } } }
----
====

[[simple-cql_spatial]]
=== Spatial predicates

A _spatial predicate_ evaluates two geometry-valued expressions to determine
if the expressions satisfy the requirements of the specified spatial operator.

In this conformance class, the only required spatial operator is _intersects_.
Additional spatial operators are specified in the <<enhanced-spatial-operators,
Enhanced Spatial Operators>> requirements class.

include::requirements/simple-cql/REQ_spatial-predicates.adoc[]

NOTE: The spatial predicates currently use a different pattern than the
comparison and temporal predicates and are written like function calls.
This difference is inherited from previous versions of CQL. It is an open
issue, whether this version of CQL should change the spatial predicates to
be consistent with the other predicates or to keep the legacy because of
existing CQL implementations. Comments are welcome in the
https://github.com/opengeospatial/ogcapi-features/issues/493[GitHub issue]
on this topic.

CQL uses Well-Known Text (WKT) to encode geometry literals. Since WKT does not
provide a capability to specify the CRS of a geometry literal, the server has
to determine the CRS of the geometry literals in a filter expression through
another mechanism. In this standard, the `filter-crs` query parameter
is used to pass the CRS information to the server.

[[example_8_8]]
.Example spatial predicate
====
----
INTERSECTS(geometry,POLYGON((36.319836 32.288087,36.320041 32.288032,36.320210 32.288402,36.320008 32.288458,36.319836 32.288087)))
----

[source,JSON]
----
{ "intersects": [
   { "property": "geometry" },
   {
      "type": "Polygon",
      "coordinates": [
         [
            [36.319836, 32.288087],
            [36.320041, 32.288032],
            [36.320210, 32.288402],
            [36.320008, 32.288458],
            [36.319836, 32.288087]
         ]
      ]
   }
] }
----
====

[[example_8_9]]
.Example for the filter-crs query parameter
====
----
...filter-lang=cql-text&
   filter-crs=http://www.opengis.net/def/crs/EPSG/0/32635&
   filter=INTERSECTS(geometry,POLYGON((379213.87 3610774.16,379233.84 3610769.70,379246.15 3610812.39,379226.49 3610816.88,379213.87 3610774.16)))...
----
====

[[simple-cql_temporal]]
=== Temporal predicates

A temporal predicate evaluates two time-valued expressions to determine if the expressions satisfy the requirements of the specified temporal operator.

In this conformance class, the only required temporal operator is
_anyinteracts_. The _anyinteracts_ operator is not defined in any of the cited
references.  Rather, it is defined in this standard as an analogous temporal operator to the _intersects_ spatial operator.

Additional temporal operators are specified in the <<enhanced-temporal-operators,Enhanced Temporal Operators>> requirements class.

include::requirements/simple-cql/REQ_temporal-predicates.adoc[]

All temporal literals are in the Gregorian Calendar.

NOTE: This is a deliberate restriction to keep implementations of CQL simple, avoiding requirements to transformation time instants to other temporal coordinate reference systems, but still cover a large number of use cases. This is consistent with the use of RFC 3339 as a key standard for expressing date and time on the internet, including in the OGC API standards.

[[example_8_10]]
.Examples temporal predicate
====
----
event_date ANYINTERACTS 1969-07-16T05:32:00Z/1969-07-24T16:50:35Z
----

[source,JSON]
----
{
   "anyinteracts": [
      { "property": "event_date" },
      [ "1969-07-16T05:32:00Z","1969-07-24T16:50:35Z" ]
   ]
}
----
====

=== CQL Encodings

This OGC API - Features - Part 3 standard defines a <<simple-cql-text,text>>
encoding and a <<simple-cql-json,JSON>> encoding of CQL that covers Simple CQL
and all enhanced capabilities specified in the next clause.
