[[cql-encodings]]
== Requirements classes for encodings

=== Overview

This clause specifies requirements for a text encoding and a JSON encoding of CQL.

[[cql-text]]
=== Requirements Class "CQL Text"

include::requirements/requirements_class_cql-text.adoc[]

This requirements class defines a well known text encoding of CQL. Such an
encoding would be suitable for use with the a GET query parameter such as the
<<rc_filter,`filter`>> parameter.

// include::requirements/cql-text/REQ_nocase.adoc[]
The "CQL Text" encoding is defined by the BNF grammar defined in <<cql-bnf>>.

Keywords in the BNF grammar are case-insensitive. <<BNF,Augmented BNF for Syntax Specifications>> states:

> ABNF strings are case insensitive and the character set for these strings is US-ASCII.

The list of CQL keywords includes:

* "ACONTAINS"
* "AEQUALS"
* "AFTER"
* "AND"
* "ANYINTERACTS"
* "AOVERLAPS"
* "B"
* "BEFORE"
* "BEGINS"
* "BEGUNBY"
* "BETWEEN"
* "CONTAINED BY"
* "CONTAINS"
* "CROSSES"
* "DISJOINT"
* "DURING"
* "E"
* "ENDEDBY"
* "ENDS"
* "ENVELOPE"
* "EQUALS"
* "F"
* "FALSE"
* "GEOMETRYCOLLECTION"
* "IN"
* "INTERSECTS"
* "LIKE"
* "LINESTRING"
* "MEETS"
* "METBY"
* "MULTILINESTRING"
* "MULTIPOINT"
* "MULTIPOLYGON"
* "NOCASE"
* "NOT"
* "NULL";
* "OR"
* "OVERLAPPEDBY"
* "OVERLAPS"
* "POINT"
* "POLYGON"
* "T"
* "TCONTAINS"
* "TEQUALS"
* "TOUCHES"
* "TOVERLAPS"
* "TRUE"
* "WITHIN"
* "X"
* "Z"

include::requirements/cql-text/REQ_filter-lang.adoc[]

include::requirements/cql-text/REQ_simple-cql.adoc[]

include::requirements/cql-text/REQ_enhanced-spatial-operators.adoc[]

include::requirements/cql-text/REQ_enhanced-temporal-operators.adoc[]

include::requirements/cql-text/REQ_functions.adoc[]

The list of supported functions can be discovered via the Functions resource (i.e. path `/functions`).

include::requirements/cql-text/REQ_arithmetic.adoc[]

include::requirements/cql-text/REQ_arrays.adoc[]

[[cql-json]]
=== Requirements Class "CQL JSON"

include::requirements/requirements_class_cql-json.adoc[]

This requirements class defines a JSON encoding of CQL. Such an encoding
would be suitable as the body of an HTTP POST request.

NOTE: Attention is drawn to the fact that there exists an alternative JSON encoding for CQL based on the use of arrays that can be found here: https://github.com/tschaub/ogcapi-features/tree/json-array-expression/extensions/cql/jfe. The SWG will review both encodings and decide which one to adopt, feedback from implementations is welcome.

include::requirements/cql-json/REQ_filter-lang.adoc[]

include::requirements/cql-json/REQ_simple-cql.adoc[]

include::requirements/cql-json/REQ_enhanced-spatial-operators.adoc[]

include::requirements/cql-json/REQ_enhanced-temporal-operators.adoc[]

include::requirements/cql-json/REQ_functions.adoc[]

The list of supported functions can be discovered via the Functions resource (i.e. path `/functions`).

include::requirements/cql-json/REQ_arithmetic.adoc[]

include::requirements/cql-json/REQ_arrays.adoc[]

[[cql-xml]]
=== XML encoding

This specification does not specifically define an XML-encoding for CQL.
However, it is recognized that XML is still in common use and so
implementors are directed to review the http://docs.opengeospatial.org/is/09-026r2/09-026r2.html[OGC Filter Encoding 2.0] standard which defines a XML-encoding for filter expressions that closely matches most of the functionality of CQL.
