== Requirements Class "Filter"

[[filter-overview]]
=== Overview

include::requirements/requirements_class_filter.adoc[]

<<OAFeat-1,OGC API - Features - Part 1: Core>> (and the draft http://docs.opengeospatial.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data] standard) define two filtering parameters on the resource at path `/collections/{collectionId}/items`: `bbox` and `datetime`. <<OAFeat-1,OGC API - Features - Part 1: Core>> also adds support for simple equality predicates logically joined using the `AND` operator. These capabilities offer simple resource filtering for HTTP requests.

The Filter requirements class defines additional query parameters that allow more
complex filtering expressions to be specified when querying server resources.

Specifically, this clause defines the parameters, `filter`, `filter-lang` and
`filter-crs`.

The Filter requirements class also defines resources for discovering the list of
resource properties (and their types) that may be used to construct filter
expressions.

[[filter-queryables]]
=== Queryables

This standard does not assume that the content schema of a
resource being queried is available for inspection. Therefore, a means needs
to exist to interrogate an <<endpoint-def,endpoint>> to determine the names and types of the
properties that may be used to construct a filter expression
("queryables").

In addition, a <<publisher-def,publisher>> may want to support <<queryable-def,queryables>> that are not
directly represented as resource properties in the content schema of the
resource. Or the <<publisher-def,publisher>> may want to restrict filtering on certain
properties. For example, because the backend datastore has not been configured
to allow high-performance queries on those properties.

include::requirements/filter/REQ_get-queryables-op.adoc[]

include::requirements/filter/REQ_get-queryables-response.adoc[]

include::requirements/filter/REQ_expression-construction.adoc[]

The response is returned as a JSON Schema document that describes a single JSON object where each property is a queryable.

NOTE: The queryables schema does not specify a schema of any object that can be retrieved from the API. JSON Schema is used for the queryables to have a consistent approach for describing schema information and JSON Schema is/will be used in other parts of OGC API Features to describe schemas for GeoJSON feature content including in OpenAPI documents.

NOTE: The OGC Features API Standards Working Group has a schema harmonization task that could lead to a future OGC API standard that will deprecate the approach for the queryables resource specified in this document.

To support clients, providing additional detail about the meaning of the
property and the possible values is recommended:

include::recommendations/filter/REC_queryables-schema.adoc[]

[[example_1]]
.Queryables example
====
[source,JSON]
----
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://demo.ldproxy.net/zoomstack/collections/roads_national/queryables",
  "type": "object",
  "title": "National Roads",
  "description": "Lines representing the road network. A road is defined as a metalled way for vehicles.",
  "properties": {
    "geom": {
      "title": "Geometry",
      "description": "The geometry of the road.",
      "$ref" : "https://geojson.org/schema/LineString.json"
    },
    "name": {
      "title": "Road Name",
      "description": "The common, human readable, name of the road.",
      "type": "string",
      "title": "Name"
    },
    "number": {
      "title": "Road Identifier",
      "description": "A numeric identifier for the road.",
      "type": "string",
      "title": "Number"
    },
    "type": {
      "title": "Road Type",
      "description": "The road type for class.",
      "type": "string",
      "title": "Type",
      "enum": [ "Primary", "Motorway" ]
    }
  }
}
----
====

[[filter-param]]
=== Parameter filter

The <<rc_filter,Filter>> requirements class defines a general parameter, `filter`, whose
value is a filter expression to be applied when retrieving resources. This
is necessary to determine which resources should be included in a result set.

include::requirements/filter/REQ_filter-param.adoc[]

[[filter-lang-param]]
=== Parameter filter-lang

Any predicate language that can be suitably expressed as the value of an
HTTP query parameter may be specified as the value of the `filter` parameter.
In order to specify that specific language that is being used, this clause
defines the `filter-lang` parameter.

include::requirements/filter/REQ_filter-lang-param.adoc[]

The enumerated value `cql-text` is used to indicate that the value of the
<<filter-param,`filter`>> parameter is the <<simple-cql-text,text encoding of CQL>>.

The enumerated value `cql-json` is used to indicate that the value of the
<<filter-param,`filter`>> parameter is the <<simple-cql-JSON,JSON encoding of CQL>>.

Servers that support other filtering languages can extend this list of values
as necessary although the meanings of any additional values are not described
in this standard.

[[filter-filter-crs]]
=== Parameter filter-crs

For reasons discussed in the http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#SDWBP[W3C/OGC Spatial Data on the Web Best Practices document], 
<<OAFeat-1,OGC API - Features - Part 1: Core>> uses WGS 84 longitude and latitude (`http://www.opengis.net/def/crs/OGC/1.3/CRS84`) for 2-D coordinates and WGS 84 longitude, latitude and ellipsoidal height in meters (`http://www.opengis.net/def/crs/OGC/0/CRS84h`) for 3-D coordinates as the default coordinate reference systems. <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>> extends the capabilities of Part 1 to allow other coordinate reference systems to be used.

For servers that implement <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, the `filter-crs` parameter defined in this clause allows clients to assert which CRS is being used to encode geometric values in a filter expression.  The `filter-crs` parameter has no use if the server does not implement <<OAFeat-2,Part 2>>.

include::requirements/filter/REQ_filter-crs-wgs84.adoc[]

include::requirements/filter/REQ_filter-crs.param.adoc[]

NOTE: Discovery of the list of supported coordinate reference systems for use with the `filter-crs` parameter is fully described in <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>.  Briefly, the list of supported CRSs can be found in the global list of CRS identifiers (path: `/crs`) and/or the list of collection-specific CRS identifiers (path: `/collections/{collectionsId}/crs`).

=== Interaction with other predicates

<<OAFeat-1,OGC API - Features - Part 1: Core>> defines the parameters `bbox`, `datetime` and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_parameters_for_filtering_on_feature_properties[parameters for filtering on feature properties].  This clause defines how the `filter` parameter and these core parameters should interact if specified in a single request.

include::requirements/filter/REQ_mixing-expressions.adoc[]

=== Filter expression languages

This standard defines a filter expression language called the 
<<cql-core,Common Query Language (CQL)>>. However, support for
this filter expression language is not mandatory and other languages 
can be used as the value of the <<filter-param,filter parameter>>, too.  

A <<cql-core,simple CQL core>> is defined along with a
number of <<cql-enhancements,enhancements>> that add additional, more advanced
capabilities to the language. Two encodings, a <<simple-cql-text,text encoding>> 
and a <<simple-cql-json,JSON>> encoding are also defined and
recommended if they are suitable for the intended use.

[[filter-response]]
=== Response

A filter expression defines a subset of items from a collection that should be presented in a query response.

include::requirements/filter/REQ_response.adoc[]
