== Requirements Class "Filter"

[[filter-overview]]
=== Overview

include::requirements/requirements_class_filter.adoc[]

The <<OACommon-1,OGC API - Common>> standard defines two filtering operators at the `/items` endpoint: bbox and datetime.  <<OAFeat-1,OGC API - Features - Part 1: Core>> also adds support, beyond <<OACommon-1,OGC API - Common>> for simple equality predicates logically joined using the AND operator.  This capabilities offer simple  resource filtering for HTTP requests.

This conformance class defines additional query parameters that allow more
complex filtering expressions to be specified when querying server resources.

Specifically, this clause defines the parameters, `filter`, `filter-lang` and
`filter-crs`.

This conformance class also defines resources for discovering the list of
resource properties (and their types) that may be used to construct filter
expressions.

[[filter-queryables]]
=== Queryables

This extension does not assume that the content schema of a
resource being queried is available for inspection and thus a means needs
to exist to interrogate an endpoint to determine the names and types of the
properties or keys that may be used to construct a filter expression
("queryables").

In addition, a publisher may want to support queryables that are not
directly represented as resource properties in the content schema of the
resource. Or the publisher may want to restrict filtering on certain
properties, e.g., because the backend datastore has not been configured
to allow performant queries on those properties.

include::requirements/filter/REQ_get-queryables-op-global.adoc[]

include::requirements/filter/REQ_get-queryables-op-local.adoc[]

include::requirements/filter/REQ_get-queryables-response.adoc[]

To support clients, it is recommended to provide additional detail
about the meaning of the property and the possible values:

include::recomendations/filter/REC_queryables-schema.adoc[]

[[example_1]]
.Queryables example
====
[source,JSON]
----
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "$id" : "https://demo.ldproxy.net/daraa/collections/CulturePnt/queryables",
  "type" : "object",
  "title" : "Cultural (Points)",
  "description" : "Cultural: Information about features on the landscape with a point geometry that have been constructed by man.",
  "properties" : {
    "F_CODE" : {
      "title" : "Feature Type",
      "type" : "string",
      "enum" : [ "AK121", "AL012", "AL030", "AL130", "BH075" ]
    },
    "ZI001_SDV" : {
      "title" : "Last Change",
      "type" : "string",
      "format" : "date-time"
    },
    "ZI037_REL" : {
      "title" : "Religious Designation",
      "type" : "integer",
      "enum" : [ -999999, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 ]
    },
    "geometry" : {
      "$ref" : "https://geojson.org/schema/Point.json"
    }
  }
}
----
====

[[filter-param]]
=== Parameter filter

This extensions defines a general parameter, `filter`, whose value is a filter
expression to be applied when retrieving resources in order to determine which
resources should be included in a result set.

include::requirements/filter/REQ_filter-param.adoc[]

[[filter-param-multiple-collections]]
=== Cross-collection queries

The only query path defined in <<OAFeat-1,OGC API - Features - Part 1: Core>>
is the `/items` endpoint which operates on a single collection.  However other,
higher level, endpoints are also being defined (e.g. /search or /tiles) that
potentially operate on multiple collections.  The simplest approach for handling
such cross-collection queries is one that is consistent with one-collection
queries.  Specifically, any specified `filter` parameter should apply to all
referenced collections.  This, of course, implies that all properties referenced
in the filter expression are valid for all referenced collections and should be
taken from  the <<filter-queryables,global queryables list>>.

include::requirements/filter/REQ_filter-param-multiple-collections.adoc[]

The following example illustrates a notional query on a `/tiles` endpoint
that uses a CQL filter and references multiple collections:

[[example_2]]
.Multi-collection filter example
====
http://www.someserver.com/ogcapi/tiles?collection=collection1,collection3&filter-lang=cql-text&filter='prop1=10 and prop2>45'&...
====

NOTE: Arrays of filter expressions that operate on each collection specified in a query (or subsets thereof) are out of scope for this extension and  would be the subject of a different part of the `OGC API - Features` suite of specifications.

[[filter-lang-param]]
=== Parameter filter-lang

Any predicate language that can be suitably expressed as the value of an
HTTP query parameter may be specified as the value of the `filter` parameter.
In order to specify that specific language that is being used, this clause
defines the `filter-lang` parameter.

include::requirements/filter/REQ_filter-lang-param.adoc[]

The enumerated value `cql-text` is used to indicate that the value of the
<<filter-param,`filter`>> parameter is the <<simple-cql-text,text encoding of CQL>>.

The enumerated value `cql-json` is used to indicate that the value of the
<<filter-param,`filter`>> parameter is the <<simple-cql-JSON,JSON encoding of CQL>>.

Servers that support other filtering languages can extend this list of values
as necessary although the meaning of any additional values are not described
in this standard.

[[filter-filter-crs]]
=== Parameter filter-crs

include::requirements/filter/REQ_filter-crs-wgs84.adoc[]

include::requirements/filter/REQ_filter-crs.param.adoc[]

=== Interaction with existing predicates

include::requirements/filter/REQ_mixing-expressions.adoc[]

=== Filter expression language

This extension does not mandate that a specific filter expression language be
used as the value of the <<filter-param,filter parameter>>.  However, this
extension defines a filter expression language called the `Common Query
Language` (CQL).  A <<cql-core,simple CQL core>> is defined along with a
number of <<cql-enhancements,enhancements>> that add additional, more advanced
capabilities to the language.  Two encodings, a <<simple-cql-text,text
encoding>> and a <<simple-cql-json,JSON>> encoding are also defined and
recommended if they are suitable for their intended use.

[[filter-response]]
=== Response

include::requirements/filter/REQ_response.adoc[]
