== Terms, Definitions and Symbols

=== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r9], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply in addition to the terms defined
in <<OAFeat-1,OGC API - Features - Part 1: Core>>.

==== filter
**predicate** encoded for transmission between systems

==== predicate
set of computational operations applied to a data instance which evaluate to true or false [Filter Encoding 2.0.2]

=== Symbols

* **&#x2229;** intersection, operation on two or more sets
* **&#x2227;** and, logical intersection
* **&#x2205;** empty set, the set having no members
* **&#x2260;** not equal
* **&#x2b04;** if and only if, logical equivalence between statements
* **&#x2286;** is a subset of
* **dim(x)** returns the maximum dimension (-1, 0, 1, or 2) of the geometric object x
* **I(x)** represents the interior of the geometric object x
* **B(x)** represents the boundary of the geometric object x
* **E(x)** represents the exterior of the geometric object x
