== Requirements Class "PATCH Update"

[[patch-update-overview]]
=== Overview

include::requirements/requirements_class_patch-update.adoc[]

A server that implements this conformance class provides the ability to use
the HTTP PATCH method to modify parts of an existing resource without the need
to transmit a complete replacement resource.

Modifying parts of a resource requires that a document describing the changes to be applied be provided by the client.  This standard does not mandate that a specific encoding for this document be supported by a server.  However, this extension provides requirements for the use of <<rfc7396 (JSON Merge Patch)>> for resource encoded using JSON (e.g. GeoJSON) and the use of <<rfc5261 (An Extensible Markup Language (XML) Patch Operations Framework Utilizing XML Path Language (XPath) Selectors)>> for resources encoded using XML (e.g. GML).

[[patch-update]]
=== Modifying and existing resource (UPDATE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for modifying part
of an existing resource by only specifying the specific parts that should be
updated.

....
   Client                                                          Server
     |                                                               |
     |   PATCH <resource end point>   HTTP/1.1                       |
     |   Content-Type: <MIME type of body>                           |
     |                                                               |
     |   ... Body contains a document describing the changes to make |
     |       to parts of the specfied resource ...                   |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             | 
     |<--------------------------------------------------------------|
....

==== Operation

include::requirements/patch-update/update/patch/REQ_patch-op.adoc[]

==== Request body

include::requirements/patch-update/update/patch/REQ_body.adoc[]

include::recommendations/patch-update/update/patch/REC_body-json-merge-patch.adoc[]

include::recommendations/patch-update/update/patch/REC_body-xml-patch.adoc[]

==== Response

include::requirements/patch-update/update/patch/REQ_response.adoc[]

==== Exceptions

See <<http_status_codes,HTTP status codes>>.
