[[features]]
== Features

=== Overview

include::requirements/requirements_class_features.adoc[]

This clause defines requirements for the case when the resource type is a
feature.

[[features-endpoint]]
=== Resources endpoint

include::requirements/features/REQ_resources-endpoint.adoc[]

[[feature-endpoint]]
=== Resource endpoint

include::requirements/features/REQ_resource-endpoint.adoc[]

[[feature-crs]]
=== Coordinate reference systems (CRS)

Unless the server supports <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, all geometries have to be submitted in the default CRS.

include::requirements/features/crs/REQ_crs84.adoc[]

If the server supports <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, the default CRS can be overridden by declaring the `Content-Crs` header in the request. Alternatively, if the feature representation supports expressing CRS information for each feature / geometry, the information can also be included in the feature representation.

include::requirements/features/crs/REQ_content-crs-header.adoc[]

include::requirements/features/crs/REQ_default-crs.adoc[]

include::requirements/features/crs/REQ_other-crs.adoc[]

This approach is consistent with the use of WGS84 longitude/latitude as the default CRS for all feature-related requests in the APIs. If both the server and the client are CRS-aware and have the capability to handle geometries in other CRSs, this requirement enables the client to negotiate to some other mutually agreeable CRS.

If the server includes the `storageCrs` property in the Collection resource, as specified in <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, then it is recommended that client express all geometry-valued feature properties presented to the server in a request body using the storage CRS. This avoids geometric errors from the conversion of coordinates on the server when storing the geometry.

include::recommendations/features/REC_storage-crs.adoc[]

[[feature-representations]]
=== Representation of features

Adding or replacing a feature requires that a representation of that feature
be provided by the client. As is the case in Part 1: Core, this standard does not
mandate that a specific feature encoding be supported by a server. 

However, this standard provides guidance for the feature encodings specified in
Part 1: Core with the exception of HTML.

[[feature-geojson]]
==== GeoJSON

include::requirements/features/REQ_representation-geojson-create.adoc[]

include::requirements/features/REQ_representation-geojson-replace.adoc[]

include::requirements/features/REQ_representation-geojson-update.adoc[]

GeoJSON normatively supports WGS84 longitude/latitude, but the 
https://tools.ietf.org/html/rfc7946#section-4["prior arrangement" provision] 
allows that other CRSs are used, if both client and server agree on the CRS. 
Clients that want to use a CRS that is not the default CRS have to state
the CRS in the POST, PUT or PATCH request using the `Content-Crs` HTTP header
to invoke the "prior arrangement" provision. 

[[feature-gml]]
==== Geography Markup Language (GML)

include::requirements/features/REQ_representation-gml-create.adoc[]

include::requirements/features/REQ_representation-gml-replace.adoc[]

include::requirements/features/REQ_representation-gml-update.adoc[]

include::requirements/features/crs/REQ_gml-srsname.adoc[]
