== Requirements Class "Simple Transactions"

[[simpletx-overview]]
=== Overview

include::requirements/requirements_class_simpletx.adoc[]

A server that implements this conformance class provides the ability to add,
replace and remove individual features from a feature collection.

The HTTP POST method is used to add new features to a collection.

The HTTP PUT method is used to replace existing feature in a collection with a
replacement feature.

Finally, the HTTP DELETE method is used to remove features from a collection.

Adding or replacing a feature requires that a representation of the feature be
provided by the client.  As is the case in the core, this standard does not
mandate that a specific feature encoding be supported by a server.  However,
in order to promote interoperability, this standard provides recommendations
for features encoded using GeoJSON or GML.

[[http_status_codes]]
==== HTTP status codes

API clients should be prepared to handle any legal HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 201 and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`201` |The server has been fulfilled the operation and a new resource has been created. 
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`500` |An internal error occurred in the server.
!===

More specific guidance is provided for each resource, where applicable.

include::recommendations/simpletx/PER_additional-status-codes.adoc[]

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[simpletx-insert]]
=== Adding a new feature to a collection (INSERT)

==== Sequence diagram

The following diagram illustrates the sequence diagram for adding a new feature
to a collection.

....
   Client                                                      Server
     |                                                           |
     |   POST /collections/{collectionId}/items  HTTP/1.1        |
     |   Content-Type: <MIME type of feature representation>     |
     |                                                           |
     |   ... Body contains representation of the feature ...     |
     |---------------------------------------------------------->|
     |                                                           |
     |   HTTP/1.1 201 Created                                    | 
     |   Location: /collections/{collectionId}/items/{featureId} | 
     |<----------------------------------------------------------|
....

==== Operation

include::requirements/simpletx/insert/REQ_post-op.adoc[]

==== Request body

===== Overview

include::requirements/simpletx/insert/REQ_body.adoc[]

include::recommendations/simpletx/insert/PER_body.adoc[]

include::requirements/simpletx/insert/REQ_content-type.adoc[]

===== GeoJSON body

include::recommendations/simpletx/insert/REC_body-geojson.adoc[]

===== GML body

include::recommendations/simpletx/insert/REC_body-gmlsf0.adoc[]

include::recommendations/simpletx/insert/REC_body-gmlsf2.adoc[]

==== Response

include::requirements/simpletx/insert/REQ_response-fid.adoc[]

include::requirements/simpletx/insert/REQ_response.adoc[]

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

[[simpletx-update-put]]
=== Replacing an existing feature (UPDATE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for replacing an existing
feature in a collection with a new feature.  This could be a completely new
feature or a new version of the existing feature; version control is not 
discussed in this standard.

....
   Client                                                          Server
     |                                                               |
     |   PUT /collections/{collectionId}/items/{featureId}  HTTP/1.1 |
     |   Content-Type: <MIME type of replacement feature>            |
     |                                                               |
     |   ... Body contains representation of replacement feature ... |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 200 OK                                             | 
     |<--------------------------------------------------------------|
....

==== Operation

include::requirements/simpletx/update/put/REQ_put-op.adoc[]

==== Request body

==== Overview 

include::requirements/simpletx/update/put/REQ_body.adoc[]

include::recommendations/simpletx/update/put/PER_body.adoc[]

include::requirements/simpletx/update/put/REQ_content-type.adoc[]

===== GeoJSON body

include::recommendations/simpletx/update/put/REC_body-geojson.adoc[]

===== GML encoding

include::recommendations/simpletx/update/put/REC_body-gmlsf0.adoc[]

include::recommendations/simpletx/update/put/REC_body-gmlsf2.adoc[]

==== Response

include::requirements/simpletx/update/put/REQ_response.adoc[]

==== Exceptions

The assignment of feature identifiers is the pervue of the server and as a
result, clients cannot simply use the HTTP PUT operation to create new feature
instances.  Instead, the creation of new feature instances should be preformed
using the HTTP POST operation as described in <<simpletx-insert,Adding a new feature to a collection>>.

include::requirements/simpletx/update/put/REQ_fid-exception.adoc[]

See also <<http_status_codes,HTTP status codes>>.

[[simpletx-delete]]
=== Removing a feature from a collection (DELETE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for removing a feature 
from a collection.

....
   Client                                                             Server 
     |                                                                  | 
     |   DELETE /collections/{collectionId}/items/{featureId}  HTTP/1.1 | 
     +----------------------------------------------------------------->| 
     |                                                                  | 
     |   HTTP/1.1 200 OK                                                | 
     +<-----------------------------------------------------------------|
....

==== Operation

include::requirements/simpletx/delete/REQ_delete-op.adoc[]

==== Response

include::requirements/simpletx/delete/REQ_response.adoc[]

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

[[simpletx-crs]]
=== Coordinate reference systems

include::requirements/simpletx/crs/REQ_crs84.adoc[]

include::requirements/simpletx/crs/REQ_storage-crs.adoc[]

GML has full CRS support and no further requirements are imposed by this
standard.

GeoJSON normatively supports WGS84 (lon,lat) but the "prior arrangement"
provision allows other coordinate reference systems to be used.

include::requirements/simpletx/crs/REQ_geojson.adoc[]

The use of HTML as a feature encoding format is not specified by this standard.
