== Scope

This document specifies an extension that defines the behaviour of a server
that supports searching for resources from one or more collections.  This
part supports queries that cannot be expressed, or cannot be conveniently
expressed, using the filtering mechanisms available in Parts 1 or 3.

Examples of the types of queries that can be expressed using Part 5 are:

* queries with a long expression text that cannot be conveniently specified as URL parameters
* bundled queries that, in a single request, fetch resources from two or more collectons
* queries that include predicates that join two or more collections
* stored queries possibly referencing multiple resource collections
* stored queries with parameters

Specifically, this document defines:

* an endpoint, `/collections/{collectionId}/search` that can be used to execute ad-hoc queries on a single collection or discover the stored queries available for this collection
* an endpoint, `/search` that can used to execute ad-hoc queries on multiple collections or discover the available multi-collection stored queries,
* an endpoint `/collections/{collectionId}/search/{queryId}` that can used to execute, create, modify or delete stored queries for this collection,
* an endpoint, `/search/{queryId}` that can be used to execute, create, modify or delete multi-collection stored queries,
* support for parameterized stored queries,
* a query expression language, based on CQL,
* support for standing or periodically executed stored queries

The following table crosswalks each of the resource endpoints discussed in this
standard with the HTTP methods GET, POST, PUT and DELETE.  Each intersecting cell
in the table either contains a reference to the section in this standard where
that combination from resource and method is discussed or the phrase
`NOT DEFINED` which is used to indicate that this specification does not
describe any behaviour for that combination of resource endpoint and HTTP 
method.

[#endpoint_method_matrix,reftext='{table-caption} {counter:table-num}']
.Supported HTTP methods by resource
[cols="40%,10%,30%,20%",options="header"]
|===
|Resource endpoint |HTTP METHOD |Description |Reference
1.4+|/collections/{collectionId}/search |GET |Get the list of stored queries for this collection. |<<clause-stored-query-discovery,Discovering stored queries>>
1+|POST |Execute an ad-hoc search on this collection. |<<clause-search-adhoc-execute,Executing ad-hoc queries>>
1+|PUT  |NOT DEFINED |
1+|DELETE |NOT DEFINED |

1.4+|/collections/{collectionId}/search/{queryId} |GET |Execute this stored query. |<<clause-stored-query-execute,Executing stored queries>>
1+|POST |Execute this stored query with an application/x-www-form-urlencoded body. |<<clause-stored-query-execute,Executing stored queries>>
1+|PUT  |Create or replace a stored query for this collection with this identifier. |<<clause-stored-query-create,Creating stored queries>>, <<clause-stored-query-update,Updating stored queries>>
1+|DELETE |Delete this stored query. |<<clause-stored-query-delete,Deleting stored queries>>

1.4+|/collections/{collectionId}/search/{queryId}/parameters |GET |Get the list of parameters for this stored query. |<<clause-parameterized-stored-query,Retirieving the list of stored query parameters>>
1+|POST |Define the parameters for a stored query.  |<<clause-parameterized-stored-query-parameter-define,Defining query parameter>>
1+|PUT  |Update a stored query parameter. |<<clause-parameterized-stored-query-parameter-update,Updating a query parameter>> 
1+|DELETE |Delete a stored query parameter. |<<clause-parameterized-stored-query-parameter-delete,Delete a query parameter>>

1.4+|/search |GET |Get the list of multi-collection stored queries. |<<clause-multi-collection-stored-query-discovery,Discovering multi-collection stored queries>>
1+|POST |Execute an ad-hoc search that references multiple collections. |<<clause-multi-collection-search-adhoc-execute,Executing ad-hoc multi-collection queries>>
1+|PUT  |NOT DEFINED |
1+|DELETE |NOT DEFINED |

1.4+|/search/{queryId} |GET |Execute this multi-collection stored query. |<<clause-multi-collection-stored-query-execute,Executing multi-collection stored queries>>
1+|POST |Execute this multi-collection stored query with an application/x-www-form-urlencoded body. |<<clause-multi-collection-stored-query-execute,Executing multi-collection stored queries>>
1+|PUT  |Create or replace a multi-collection stored query. |<<clause-multi-collection-stored-query-create,Creating multi-collection stored queries>>, <<clause-multi-collection-stored-query-update,Updating multi-collection stored queries>>
1+|DELETE |Delete this stored query. |<<clause-multi-collection-stored-query-delete,Deleting multi-collection stored queries>>

1.4+|/search/{queryId}/parameters |GET |Get the list of parameters for this parametertized multi-collection stored query. |<<clause-parameterized-multi-collection-stored-query-discovery,Retrieving the list of multi-collection-stored-query-parameters>>
1+|POST |Define the parameters for a multi-collection stored query.  |<<clause-parameterized-multi-collection-stored-query-parameter-define,Defining query parameter>>
1+|PUT  |Update a multi-collection stored query parameter. |<<clause-parameterized-multi-collection-stored-query-parameter-update,Updating a query parameter>> 
1+|DELETE |Delete a multi-collection stored query parameter. |<<clause-parameterized-multi-collection-stored-query-parameter-delete,Delete a query parameter>>
|===
