=== Conformance Class "Features"

:conf-class: features
[[conf_features]]
[cols="1,4a",width="90%"]
|===
2+|*Conformance Class*
2+|http://www.opengis.net/spec/ogcapi-features-4/1.0/conf/{conf-class}
|Target type |Web API
|Requirements class |<<rc_features,Requirements Class "Features">>
|Dependency |<<conf_create-replace-delete,Conformance Class "Create/Replace/Delete">>
|Dependency |<<OAFeat-1,OGC API - Features - Part 1: Core>>, Conformance Class "Core" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core`)
|Conditional Dependency |<<OAFeat-1,OGC API - Features - Part 1: Core>>, Conformance Class "GeoJSON" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson`)
|Conditional Dependency |<<OAFeat-1,OGC API - Features - Part 1: Core>>, Conformance Class "Geography Markup Language (GML), Simple Features Profile, Level 0" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0`)
|Conditional Dependency |<<OAFeat-1,OGC API - Features - Part 1: Core>>, Conformance Class "Geography Markup Language (GML), Simple Features Profile, Level 2" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2`)
|Conditional Dependency |<<conf_update,Conformance Class "Update">>
|Conditional Dependency |<<rfc7396,RFC 7396 (JSON Merge Patch)>>
|Conditional Dependency |<<rfc6906,RFC 6906 (The 'profile' Link Relation Type)>>
|Conditional Dependency |<<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, Conformance Class "Coordinate Reference Systems by Reference" (`http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs`)
|Conditional Dependency |<<OAFeat-5,OGC API - Features - Part 5 / OGC API - Common - Part 3: Schemas>>, Conformance Class "Returnables and Receivables" (`http://www.opengis.net/spec/ogcapi-common-3/1.0/conf/returnables-and-receivables`)
|Conditional Dependency |<<JSON-FG,OGC Features and Geometries JSON - Part 1: Core>>, Conformance Class "JSON-FG in Web APIs" (`http://www.opengis.net/spec/json-fg-1/1.0/conf/api`)
|===

For this conformance class, the mutable resources (test parameter) are features. The tests use the <<test-dataset,test dataset>>, published by the Web API under test as a feature collection `{collectionId}`.

Most tests in this conformance class are conditional, mirroring the conditions of the requirements they test and the conditional dependencies of the requirements class.

:conf-test: endpoints
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_resources-endpoint,/req/features/resources-endpoint>>, <<req_resource_endpoint,/req/features/resource-endpoint>>
|Condition: | none, the test is executed for every Web API under test
|Test purpose: | Mutable features are the features of the feature collections of the API
|Test method: |
Given:

* the landing page URI `{landingPageUri}` of the Web API under test;
* the `collections` array in the response to a GET request to `{landingPageUri}/collections`, restricted to the collections with no `itemType` member or an `itemType` member with the value "feature";

When:

* the identifier `{collectionId}` of each such collection and the identifier `{featureId}` of each feature in a GET response from `{landingPageUri}/collections/{collectionId}/items` are determined;

Then:

* assert that each mutable feature collection (test parameter) has the resources endpoint `{landingPageUri}/collections/{collectionId}/items` for one of the collections;
* assert that each mutable feature (test parameter) has the resource endpoint `{landingPageUri}/collections/{collectionId}/items/{featureId}` for one of the features.
|===

:conf-test: put-create
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_collection_endpoint,/req/features/collection-endpoint>>
|Condition: | At least one mutable feature collection supports creating new features using the PUT method (test parameter).
|Test purpose: | Support for creating features using PUT is declared in the collection
|Test method: |
Given:

* a feature collection `{collectionId}` that supports creating new features using the PUT method;
* a valid representation of a new feature and its media type (test parameter);

When:

* GET requests are submitted to `{landingPageUri}/collections` and `{landingPageUri}/collections/{collectionId}`;
* a PUT request with the feature in the request body and its media type in the `Content-Type` header is submitted to a resource endpoint `{landingPageUri}/collections/{collectionId}/items/{featureId}` with the identifier `{featureId}` of a non-existing feature;

Then:

* assert that both representations of the collection include a property `supportsNonAutogeneratedResourceIds` with the value `true`;
* assert that the response to the PUT request has the HTTP status code `201` — or `202`, if the operation has been queued for processing, in which case the remaining assertion is skipped;
* assert that a GET request to the resource endpoint returns the HTTP status code `200` and the feature has the identifier `{featureId}`.
|===

:conf-test: crs84
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_crs-crs84,/req/features/crs-crs84>>
|Condition: |
* The conformance declaration does not include the Conformance Class "Coordinate Reference Systems by Reference" (`http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs`).
* A mutable feature collection supports the CREATE operation with GeoJSON.
|Test purpose: | Geometries are interpreted as WGS 84, if CRS support is not implemented
|Test method: |
Given:

* a feature collection `{collectionId}` that supports the CREATE operation with GeoJSON;
* a valid GeoJSON representation of a new feature (for example, `create-building.json` from the <<test-dataset,test dataset>>);

When:

* a first POST request with the feature in the request body is submitted to the resources endpoint;
* a second POST request with the feature in the request body and a `Content-Crs` header with a value other than `\http://www.opengis.net/def/crs/OGC/1.3/CRS84` is submitted to the resources endpoint;

Then:

* assert that the first request is processed successfully and a GET request to the URI in the `Location` header returns the feature with an unchanged geometry (the coordinates have been interpreted as WGS 84 longitude/latitude);
* assert that the response to the second request is an error (a `4xx` status code).
|===

:conf-test: crs
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_content-crs-header,/req/features/content-crs-header>>, <<req_features_default-crs,/req/features/default-crs>>, <<req_features_crs-other-crs,/req/features/crs-other-crs>>
|Condition: |
* The conformance declaration includes the Conformance Class "Coordinate Reference Systems by Reference" (`http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs`).
* A mutable feature collection supports the CREATE operation with GeoJSON and supports a coordinate reference system other than the default CRS (the `crs` array of the collection).
|Test purpose: | Geometries are interpreted in the declared coordinate reference system
|Test method: |
Given:

* a feature collection `{collectionId}` that supports the CREATE operation with GeoJSON and a coordinate reference system `{crs}` other than the default CRS;
* a valid GeoJSON representation of a new feature with coordinates in WGS 84 longitude/latitude and the same representation with the coordinates converted to `{crs}`;

When:

* a first POST request with the feature with WGS 84 coordinates in the request body and without a `Content-Crs` header is submitted to the resources endpoint;
* a second POST request with the feature with coordinates in `{crs}` in the request body and a `Content-Crs` header with the value `{crs}` is submitted to the resources endpoint;
* a third POST request with the feature in the request body and a `Content-Crs` header with a CRS identifier that is not supported for the collection is submitted to the resources endpoint;

Then:

* assert that the first and second requests are processed successfully;
* assert that GET requests to the URIs in the `Location` headers of the first and second responses, with the `crs` query parameter set to the same CRS, return features with geometries that are identical within the coordinate conversion accuracy (the coordinates of both features represent the same location);
* assert that the response to the third request is an error (a `4xx` status code).
|===

:conf-test: gml-srsname
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_gml-srsname,/req/features/gml-srsname>>
|Condition: |
* The conformance declaration includes the Conformance Class "Coordinate Reference Systems by Reference" (`http://www.opengis.net/spec/ogcapi-features-2/1.0/conf/crs`).
* The conformance declaration includes one of the GML Conformance Classes (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0` or `http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2`).
* A mutable feature collection supports the CREATE operation with GML and supports a coordinate reference system other than the default CRS.
|Test purpose: | The srsName attribute in GML request bodies is honored
|Test method: |
Given:

* a feature collection `{collectionId}` that supports the CREATE operation with GML and a coordinate reference system `{crs}` other than the default CRS;
* a valid GML representation of a new feature where each geometry element includes a `srsName` attribute with the value `{crs}` and coordinates in `{crs}` (for the test dataset: `create-building.gml`);

When:

* a POST request with the feature in the request body and a GML media type in the `Content-Type` header is submitted to the resources endpoint;

Then:

* assert that the request is processed successfully;
* assert that a GET request to the URI in the `Location` header, with the `crs` query parameter set to `{crs}`, returns a feature with a geometry that is identical within the coordinate conversion accuracy (the `srsName` attribute has been honored).
|===

:conf-test: schema
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_schema,/req/features/schema>>
|Condition: |
* The conformance declaration includes the Conformance Class "Returnables and Receivables" (`http://www.opengis.net/spec/ogcapi-common-3/1.0/conf/returnables-and-receivables`).
* A mutable feature collection supports the CREATE operation with GeoJSON.
|Test purpose: | Mutation requests are processed according to the published schema
|Test method: |
Given:

* a feature collection `{collectionId}` that supports the CREATE operation with GeoJSON;
* the schema of the collection from a GET request to `{landingPageUri}/collections/{collectionId}/schema`;
* a GeoJSON representation of a new feature where each property meets the schema constraints of the corresponding receivable property (for the test dataset: `create-building.json`);

When:

* a first POST request with the feature in the request body is submitted to the resources endpoint;
* a second POST request with the feature extended by an additional property that is not specified in the schema is submitted to the resources endpoint;
* if the schema specifies a property with a statement `"readOnly": true`, a third POST request with the feature extended by that property is submitted to the resources endpoint (for the test dataset: the property `updated`);

Then:

* assert that the response content of the schema request is a JSON Schema;
* assert that the first request is processed successfully;
* assert that the response to the second request has a `4xx` status code, if the schema includes a statement `"additionalProperties": false` — otherwise that the request is not rejected because of the additional property;
* assert that the response to the third request, if submitted, has a `4xx` status code.
|===

:conf-test: geojson
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_geojson-create-replace,/req/features/geojson-create-replace>>
|Condition: |
* The conformance declaration includes the Conformance Class "GeoJSON" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson`).
* The conformance declaration includes the Conformance Class "Returnables and Receivables" (`http://www.opengis.net/spec/ogcapi-common-3/1.0/conf/returnables-and-receivables`).
* A mutable feature collection supports the REPLACE operation with GeoJSON.
|Test purpose: | GeoJSON representations in mutation requests are processed correctly
|Test method: |
Given:

* a feature collection `{collectionId}` that supports the REPLACE operation with GeoJSON;
* the resource endpoint of an existing feature with the identifier `{featureId}`;
* a valid GeoJSON representation of the new feature content that includes an "id" member with a value that differs from `{featureId}` (for the test dataset: `replace-building.json` with an added "id" member);

When:

* a PUT request with the feature in the request body is submitted to the resource endpoint;

Then:

* assert that either the request is rejected with a `4xx` status code and the feature is unchanged, or the request is processed successfully and a GET request to the resource endpoint returns the new feature content with the "id" member `{featureId}` (the "id" member in the request body has been ignored);
* assert that, if the request has been processed successfully, the "geometry" member of the feature returned by the GET request represents the geometry submitted in the request body (the geometry has been mapped to the property with the role "primary-geometry").
|===

:conf-test: json-merge-patch
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_update-json-merge-patch,/req/features/update-json-merge-patch>>
|Condition: |
* The conformance declaration includes the Conformance Class <<conf_update,"Update">> (`http://www.opengis.net/spec/{standard}/{m_n}/conf/update`).
* The conformance declaration includes the Conformance Class "Returnables and Receivables" (`http://www.opengis.net/spec/ogcapi-common-3/1.0/conf/returnables-and-receivables`).
* A mutable feature collection supports the UPDATE operation with JSON Merge Patch (`application/merge-patch+json`).
* The conformance declaration includes the Conformance Class "GeoJSON" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson`) and the feature collection supports the CREATE operation with GeoJSON.
|Test purpose: | UPDATE requests with JSON Merge Patch documents are processed correctly
|Test method: |
Given:

* the resource endpoint of an existing feature in a feature collection that supports the UPDATE operation with `application/merge-patch+json`;
* a JSON Merge Patch document that changes the value of one property, adds a property, sets another property to `null` and changes the primary geometry to a new GeoJSON geometry object (for the test dataset: `update-building.json`);
* a second JSON Merge Patch document that changes the value of the property with the `x-ogc-role` "id" in the schema;

When:

* a first PATCH request with the first document in the request body and `application/merge-patch+json` in the `Content-Type` header is submitted to the resource endpoint;
* a second PATCH request with the second document in the request body and `application/merge-patch+json` in the `Content-Type` header is submitted to the resource endpoint;

Then:

* assert that the first request is processed successfully — or queued for processing (`202`), in which case the assertions about the state of the feature are skipped;
* assert that a GET request to the resource endpoint returns the feature where the changed property has the new value, the added property is present, the property with the `null` value is unset, and the primary geometry of the feature is the geometry submitted in the request body;
* assert that the second request is rejected with a `4xx` status code.
|===

:conf-test: jsonfg
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_geojson-jsonfg,/req/features/geojson-jsonfg>>
|Condition: |
* The conformance declaration includes the Conformance Class "GeoJSON" (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson`).
* The conformance declaration includes the Conformance Class "JSON-FG in Web APIs" (`http://www.opengis.net/spec/json-fg-1/1.0/conf/api`).
* A mutable feature collection supports the CREATE operation with GeoJSON.
|Test purpose: | JSON-FG extensions in GeoJSON request bodies are supported
|Test method: |
Given:

* a feature collection `{collectionId}` that supports the CREATE operation with GeoJSON;
* a valid GeoJSON representation of a new feature and a valid JSON-FG representation of a new feature with the geometry in the "place" member in a coordinate reference system other than WGS 84 (for the test dataset: `create-building.json` and `create-building-jsonfg.json`);

When:

* a first POST request with the GeoJSON feature in the request body and a `Link` header with the value `<\http://www.opengis.net/def/profile/OGC/0/rfc7946>; rel=profile` is submitted to the resources endpoint;
* a second POST request with the JSON-FG feature in the request body and a `Link` header with the value `<\http://www.opengis.net/def/profile/OGC/0/jsonfg>; rel=profile` is submitted to the resources endpoint;

Then:

* assert that both requests are processed successfully;
* assert that a GET request to the URI in the `Location` header of the second response, requesting the JSON-FG profile, returns a feature with a "place" member that represents the geometry submitted in the request body (the request body has been processed according to JSON-FG).
|===

:conf-test: gml
==== Conformance Test {counter:test-id}
[cols=">20h,<80a",width="100%"]
|===
|Test id: | /conf/{conf-class}/{conf-test}
|Requirements: | <<req_features_gml-create-replace,/req/features/gml-create-replace>>
|Condition: |
* The conformance declaration includes one of the GML Conformance Classes (`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf0` or `http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/gmlsf2`).
* A mutable feature collection supports the REPLACE operation with GML.
|Test purpose: | GML representations in mutation requests are processed correctly
|Test method: |
Given:

* the resource endpoint of an existing feature with the identifier `{featureId}` in a feature collection that supports the REPLACE operation with GML;
* a valid GML representation of the new feature content with a `@gml:id` attribute for the feature that differs from `{featureId}` (for the test dataset: `replace-building.gml` with a changed `@gml:id` value);

When:

* a PUT request with the feature in the request body and a GML media type in the `Content-Type` header is submitted to the resource endpoint;

Then:

* assert that either the request is rejected with a `4xx` status code and the feature is unchanged, or the request is processed successfully and a GET request to the resource endpoint returns the new feature content with the feature identifier `{featureId}` (the `@gml:id` attribute in the request body has been ignored).
|===
