[[features_clause]]
== Requirements Class "Features"

=== Overview

include::requirements/requirements_class_features.adoc[]

This clause defines requirements for the case when the resource type is a
feature.

[[features-endpoint]]
=== Resources endpoint

include::requirements/features/REQ_resources-endpoint.adoc[]

[[feature-endpoint]]
=== Resource endpoint

include::requirements/features/REQ_resource-endpoint.adoc[]

[[feature-crs]]
=== Coordinate reference systems (CRS)

Unless the server supports <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, all geometries have to be submitted in the default CRS.

include::requirements/features/crs/REQ_crs84.adoc[]

If the server supports <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, the default CRS can be overridden by declaring the `Content-Crs` header in the request. Alternatively, if the feature representation supports expressing CRS information for each feature / geometry, the information can also be included in the feature representation.

include::requirements/features/crs/REQ_content-crs-header.adoc[]

include::requirements/features/crs/REQ_default-crs.adoc[]

include::requirements/features/crs/REQ_other-crs.adoc[]

This approach is consistent with the use of WGS84 longitude/latitude as the default CRS for all feature-related requests in the APIs. If both the server and the client are CRS-aware and have the capability to handle geometries in other CRSs, this requirement enables the client to negotiate to some other mutually agreeable CRS.

*Example*

The following example adds a new feature to the `dc_buildings` collection.  The feature is represented as GeoJSON and the `Content-Crs` HTTP header is used to assert that the geometry coordinates are expressing using CRS http://www.opengis.net/def/crs/EPSG/0/32607 (WGS 84 / UTM zone 7N).  A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

[#create-crs-example,reftext=`Create Example with non-default CRS`]
.Create a new feature expressed using a non-default CRS.
include::../examples/json/ex05_create-crs.adoc[]

If the server includes the `storageCrs` property in the Collection resource, as specified in <<OAFeat-2,OGC API - Features - Part 2: Coordinate Reference Systems by Reference>>, then it is recommended that client express all geometry-valued feature properties presented to the server in a request body using the storage CRS. This avoids geometric errors from the conversion of coordinates on the server when storing the geometry.

include::recommendations/features/REC_storage-crs.adoc[]

NOTE: See https://github.com/opengeospatial/ogcapi-features/issues/505[Issue 505]. 
This does not provide a clear mechanism how a client can determine all the CRSs that 
are supported for a specific request and it may involve some try and error. Adding yet
more information to the Collection resource does not seem to be the right approach.
Use OPTIONS for this?

[[feature-representations]]
=== Representation of features

Adding or replacing a feature requires that a representation of that feature
be provided by the client. As is the case in Part 1: Core, this standard does not
mandate that a specific feature encoding be supported by a server. 

However, this standard provides guidance for the feature encodings specified in
Part 1: Core with the exception of HTML.

Features in a collection can be constrained to a specific schema, but this does 
not have to be the case. This standard recommends that servers that have schema
constraints expose these to clients in the Schema resource at 
`{landingPageUri}/collections/{collectionId}/schema`, so that clients are able to 
generate feature representations that are acceptable to the server. 
The feature schema can and often will depend in the operation, so a Schema
resource will publish the specific schema representations for the
CREATE, REPLACE and UPDATE operations.

include::recommendations/features/REC_schema.adoc[]

[[feature-geojson]]
==== GeoJSON

include::requirements/features/REQ_representation-geojson-create.adoc[]

*Example*

The following examples fetch the "create", "replace" and "update" schemas for the `oakland_buildings` collection.  The `type` parameter with a value of `create`, `replace` and `update` are used to indicate that the desired schema is the schema that should be followed to create, replace or update a feature instance. Pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

All schemas are based on the GeoJSON schema of a `oakland_buildings` feature. The server will reject any feature that does not validate against the schema for the requested operation. Since each schema includes a statement `"additionalProperties": false`, the server will reject any feature that has additional properties that are not specified in the schema.

The differences between the schemas are in the nature of the operation: 

- The "create" schema is the standard GeoJSON schema. It includes an `id` member and likely indicates that the server will take the value into account when assigning a feature id to the new feature, but this is the decision of the server.
- The "replace" schema is identical to the "create" schema. The server may reject feature instances that have an `id` member that is not the same as the feature identifier of the feature that is replaced.
- The "update" schema has no `id` member and no required members since in the PATCH request only the members that are changed will be included. In addition, the schema allows `null` values for properties that are not required in the create/replace schema.

[#create-schema,reftext=`"Create" Schema Example`]
."Create" Schema Example
include::../examples/json/create_schema.adoc[]

[#replace-schema,reftext=`"Replace" Schema Example`]
."Replace" Schema Example
include::../examples/json/replace_schema.adoc[]

[#update-schema,reftext=`"Update Schema Example`]
."Update" Schema Example
include::../examples/json/update_schema.adoc[]


include::requirements/features/REQ_representation-geojson-replace.adoc[]

include::requirements/features/REQ_representation-geojson-update.adoc[]

GeoJSON normatively supports WGS84 longitude/latitude, but the 
https://www.rfc-editor.org/rfc/rfc7946.html#section-4["prior arrangement" provision] 
allows that other CRSs are used, if both client and server agree on the CRS. 
Clients that want to use a CRS that is not the default CRS have to state
the CRS in the POST, PUT or PATCH request using the `Content-Crs` HTTP header
to invoke the "prior arrangement" provision. 

[[feature-gml]]
==== Geography Markup Language (GML)

include::requirements/features/REQ_representation-gml-create.adoc[]

include::requirements/features/REQ_representation-gml-replace.adoc[]

include::requirements/features/REQ_representation-gml-update.adoc[]

This standard does not specify the PATCH syntax / semantics that has to be applied for GML feature updates. Two options are:

- use of the http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#283[Update action from OGC Web Feature Service 2.0]; 
- use of <<rfc5261,RFC 5261 (An Extensible Markup Language (XML) Patch Operations Framework Utilizing XML Path Language (XPath) Selectors)>>.

include::requirements/features/crs/REQ_gml-srsname.adoc[]
