[[return-resource-representation-in-response_clause]]
== Requirements Class "Return Resource Representation in Response"

[[return-resource-representation-in-response-overview]]
=== Overview

include::requirements/requirements_class_return-resource-representation-in-response.adoc[]

A server that implements this requirements class provides the ability to return
a representation of a newly created or modified resource in the response body of a <<create,create>>, <<replace,replace>> or <<update,update>> operation.


[[return-resource-representation-in-response-header]]
=== Prefer header

==== Definition

include::requirements/return-resource-representation-in-response/REQ_header.adoc[]

==== Response

include::requirements/return-resource-representation-in-response/REQ_response.adoc[]

include::requirements/return-resource-representation-in-response/REQ_representation.adoc[]

include::recommendations/return-resource-representation-in-response/REC_media-type.adoc[]

A client cannot in general determine from the response content alone whether the server has applied the `return` preference. The response therefore declares the preference that was applied:

include::requirements/return-resource-representation-in-response/REQ_preference-applied.adoc[]

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

==== Example

The following example illustrates the use of the `Prefer`
HTTP header to request that a representation of the newly created resource be 
returned in the response body of the <<create,create operation>>.

....
   Client                                                          Server
     |                                                               |
     |   POST <resources endpoint>   HTTP/1.1                        |
     |   Content-Type: <media type of resource representation>       |
     |   Prefer: return=representation                               |
     |   Accept: <media type of returned resource representation>    |
     |                                                               |
     |   ... Body contains representation of the resource ...        |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 201 Created                                        | 
     |   Location: <resource endpoint>                               |    
     |                                                               |
     |   ... Response body containing representation of created       |
     |       resource ...                                            |
     |<--------------------------------------------------------------|
....
