[[update_clause]]
== Requirements Class "Update"

[[update-overview]]
=== Overview

include::requirements/requirements_class_update.adoc[]

A server that implements this requirements class provides the ability to use
the HTTP PATCH method to modify parts of an existing resource without the need
to transmit a complete replacement resource.

In this Standard, the term "update" refers to a partial update of a resource, that is, modifying parts of the resource, in contrast to the complete update of a resource with the <<replace,Replace>> operation.

Modifying parts of a resource requires that a document describing the changes to be applied be provided by the client.  This Standard does not mandate that a specific encoding for this document be supported by a server. The client declares the media type of the document in the request body in the `Content-Type` header (see <<mediatypes,Media Types>>).

include::recommendations/update/PER_content-type-lenient.adoc[]

include::requirements/update/REQ_methods.adoc[]

include::requirements/update/REQ_accept-patch.adoc[]

[[update]]
=== Modifying an existing resource (UPDATE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for modifying part
of an existing resource by only specifying the specific parts that should be
updated.

....
   Client                                                          Server
     |                                                               |
     |   PATCH <resource endpoint>   HTTP/1.1                        |
     |   Content-Type: <media type of body>                          |
     |                                                               |
     |   ... Body contains a document describing the changes to make |
     |       to parts of the specified resource ...                  |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 204 OK                                             | 
     |<--------------------------------------------------------------|
....

==== Operation

include::requirements/update/REQ_patch-op.adoc[]

==== Request body

include::requirements/update/REQ_body.adoc[]

Details how a PATCH request body must be processed by a server depends on the resource representation and must be specified for each resource type and its representations.

include::requirements/update/REQ_content-type.adoc[]

==== Response

include::requirements/update/REQ_response.adoc[]

The status code depends on the server. If the server has updated the resource, the
response is either `200`, if the response includes additional content such as the
updated representation of the resource, or `204`, if the response has no additional content. 

include::recommendations/update/PER_async.adoc[]

If the server does not execute the update request immediately, but accepts it for processing at a later time, the response has the HTTP status code `202`. In this case, the processing can succeed or fail, without further notification to the client. See <<async_processing,Asynchronous processing>>.

include::requirements/update/REQ_rid.adoc[]

NOTE: Whether ignoring the identifier or rejecting the request is the better behaviour depends on the resource type and on the encoding of the changes. In a REPLACE operation, the request body is a representation of the resource and a resource identifier in the body is redundant, so ignoring it is unproblematic. In an UPDATE operation, however, the request body describes the changes that the server should make: a document that states a different resource identifier requests a change of the identifier, and a client that receives a successful response would assume that the change has been made. For features, the request is therefore rejected, see Requirement <<req_features_update-json-merge-patch,/req/features/update-json-merge-patch>>.

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

==== Example

The following example updates two properties (`geom`, the geometry, and `apnid`) and adds a new property named `primary_material` to the feature created by the <<replace-example>>.  

The example uses a <<rfc7396,JSON Merge Patch>> document to describe the changes to be made. The replacement geometry is specified using the default CRS of http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS 84 longitude/latitude). The server responds to the operation by presenting the updated feature, formatted as GeoJSON, in the response body.

[#update-example,reftext=`Update Example`]
.Update a Portion of an Existing Feature Example
include::../examples/json/ex03_update.adoc[]

=== Adding and removing resources properties

In addition to modifying the value of existing resource properties, modifying
a resource can also include adding and removing properties from the structure
of a resource.  For servers that are "schema-less" such mutations do not
present a problem.  However, for servers that include schema constraints, such
mutations may result in exception conditions.  In order to mitigate this 
possibility, the following recommendation is made:

include::recommendations/update/REC_schema.adoc[]

If a server publishes a schema, update requests presented to the server should
endeavor to honor the published schema.
