[[create-replace-delete_clause]]
== Requirements Class "Create/Replace/Delete"

[[create-replace-delete-overview]]
=== Overview

include::requirements/requirements_class_create-replace-delete.adoc[]

A server that implements this requirements class provides the ability to add,
replace and remove individual resources from a collection.

The HTTP POST method is used to add a new resource instance to a collection.

The HTTP PUT method is used to replace an existing resource in a collection
with a replacement resource.

Finally, the HTTP DELETE method is used to remove a resource from a collection.

Adding or replacing a resource requires that a representation of that resource
be provided by the client.  This standard does not mandate that a specific
specific resource encoding be supported by a server.

NOTE: The use of the HTTP PATCH method is not defined in this requirements class.  The <<rc_update,Update>> requirements class defines the use of the HTTP PATCH method.

NOTE: In order to promote interoperability, each standard that extends this standard should make recommendations concerning the representation of resources.  See <<features,Features>> for a discussion of feature representations.

[[http_status_codes]]
==== HTTP status codes

API clients should be prepared to handle any registered HTTP or HTTPS status code.

The *Status Codes* listed in <<status_codes>> are of particular relevance to implementors of this standard. Status codes 200, 201, 202, 204 and 404 are called out in API requirements. Therefore, support for some of these status codes is mandatory for all compliant implementations. The remainder of the status codes in <<status_codes>> are not mandatory, but are important for the implementation of a well functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#status_codes,reftext='{table-caption} {counter:table-num}']
.Typical HTTP status codes[[table_2]]
[cols="15,85",options="header"]
!===
|Status code |Description
|`200` |A successful request.
|`201` |The server has been fulfilled the operation and a new resource has been created. 
|`202` |The request has been accepted for processing, but the processing has not been completed. The request might or might not eventually be acted upon, as it might be disallowed when processing actually takes place.
|`204` |A successful request with no additional content to send in the response.
|`400` |The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
|`401` |The request requires user authentication. The response includes a `WWW-Authenticate` header field containing a challenge applicable to the requested resource.
|`403` |The server understood the request, but is refusing to fulfill it. While status code `401` indicates missing or bad authentication, status code `403` indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
|`404` |The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
|`405` |The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
|`406` |Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.
|`412` |The status code indicates that one or more conditions given in the request header fields evaluated to false when tested by the server.
|`413` |The server is refusing to process the request because the request content is larger than the server is willing or able to process.
|`415` |The server is refusing to service the request because the content is in a format not supported by this method on the target resource.
|`422` |The server understands the content type of the request content and the syntax of the request content is correct, but was unable to process the contained instructions. For example, the submitted resource does not meet a semantic constraint, e.g. a mandatory property is missing.
|`500` |An internal error occurred in the server.
!===

NOTE: Status code `422` is not yet an official HTTP status code, but is expected to be added by the https://www.ietf.org/archive/id/draft-ietf-httpbis-semantics-19.html#name-422-unprocessable-content[draft IETF RFC "HTTP Semantics"].

More specific guidance is provided for each resource, where applicable.

include::recommendations/create-replace-delete/PER_additional-status-codes.adoc[]

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

[[cross_origin]]
==== Cross-origin requests

See <<OAFeat-1,OGC API - Features - Part 1: Core>>, section link:http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#cross_origin[Support for cross-origin requests], about the importance of supporting cross-origin requests, typically via link:https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)].

[[create]]
=== Adding a new resource to a collection (CREATE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for adding a new resource
to a collection.

....
   Client                                                          Server
     |                                                               |
     |   POST <resources endpoint>   HTTP/1.1                        |
     |   Content-Type: <media type of resource representation>       |
     |                                                               |
     |   ... Body contains representation of the resource ...        |
     |-------------------------------------------------------------->|
     |                                                               |
     |   HTTP/1.1 201 Created                                        | 
     |   Location: <resource endpoint>                               |    
     |<--------------------------------------------------------------|
....

==== Operation

include::requirements/create-replace-delete/create/REQ_post-op.adoc[]

==== Request body

===== Overview

include::requirements/create-replace-delete/create/REQ_body.adoc[]

include::recommendations/create-replace-delete/create/PER_body.adoc[]

include::requirements/create-replace-delete/create/REQ_content-type.adoc[]

See https://www.rfc-editor.org/rfc/rfc7231.html#section-3.1.1.5[section 3.1.1.5 of RFC 7231] for details.

==== Response

include::requirements/create-replace-delete/create/REQ_response-rid.adoc[]

include::requirements/create-replace-delete/create/REQ_response.adoc[]

If the server will process the create request later, it will return a `202`. In this
case, the resource creation can succeed or fail, without further notification to the client
about the result or the resource identifier.

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

==== Example

The following example adds a new feature to the `oakland_buildings` collection.  The feature is represented as GeoJSON using the default CRS of http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS 84 longitude/latitude).  A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

[#create-example,reftext=`Create Example`]
.Create a New Feature Example
include::../examples/json/ex01_create.adoc[]

[[replace]]
=== Replacing an existing resource (REPLACE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for replacing the content
of an existing resource in a collection. The identifier of the resource does not
change. 

NOTE: The new content replaces the old content of the resource; version control is not 
discussed in this standard.

....
   Client                                                            Server
     |                                                                 |
     |   PUT <resource end point>   HTTP/1.1                           |
     |   Content-Type: <media type of updated resource representation> |
     |                                                                 |
     |   ... Body contains representation of new resource content ...  |
     |---------------------------------------------------------------->|
     |                                                                 |
     |   HTTP/1.1 204 OK                                               | 
     |<----------------------------------------------------------------|
....

==== Operation

include::requirements/create-replace-delete/replace/REQ_put-op.adoc[]

==== Request body

==== Overview 

include::requirements/create-replace-delete/replace/REQ_body.adoc[]

include::recommendations/create-replace-delete/replace/PER_body.adoc[]

include::requirements/create-replace-delete/replace/REQ_content-type.adoc[]

See https://www.rfc-editor.org/rfc/rfc7231.html#section-3.1.1.5[section 3.1.1.5 of RFC 7231] for details.

==== Response

include::requirements/create-replace-delete/replace/REQ_response.adoc[]

The status code depends on the server. If the server has updated the resource, the
response is either `200`, if the response includes additional content, or `204`, 
if the response has no additional content. 

If the server will process the update request later, it will return a `202`. In this
case, the processing can succeed or fail, without further notification to the client.

==== Exceptions

The assignment of resource identifiers is the perview of the server and as a
result, clients cannot simply use the HTTP PUT operation to create a new resource.
Instead, the creation of new resource instances have be preformed
using the HTTP POST operation as described in <<create>>.

include::requirements/create-replace-delete/replace/REQ_rid-exception.adoc[]

See also <<http_status_codes,HTTP status codes>>.

==== Example

The following example replaces the feature created by the <<create-example>> with a new feature.  Once again, the replacement feature is represented as GeoJSON using the default CRS of http://www.opengis.net/def/crs/OGC/1.3/CRS84 (WGS 84 longitude/latitude).  A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

[#replace-example,reftext=`Replace Example`]
.Replace an Existing Feature Example
include::../examples/json/ex02_replace.adoc[]

[[delete]]
=== Removing a resource from a collection (DELETE)

==== Sequence diagram

The following diagram illustrates the sequence diagram for removing a resource 
from a collection.

....
   Client                                                          Server 
     |                                                               | 
     |   DELETE <resource endpoint>   HTTP/1.1                       | 
     +-------------------------------------------------------------->| 
     |                                                               | 
     |   HTTP/1.1 204 OK                                             | 
     +<--------------------------------------------------------------|
....

==== Operation

include::requirements/create-replace-delete/delete/REQ_delete-op.adoc[]

==== Response

include::requirements/create-replace-delete/delete/REQ_response.adoc[]

If the server will process the update request later, it will return a `202`. In this
case, the processing can succeed or fail, without further notification to the client.

Note that if no resource with the identifier exists in the collection, the server can respond 
with a success status (`200` or `204`) or with a not-found exception (`404`).

NOTE: See https://github.com/opengeospatial/ogcapi-features/issues/328[Issue 328]. 
Should it be up to the server whether it responds with a 204 or a 404, if no feature exists?

==== Exceptions

See <<http_status_codes,HTTP status codes>>.

==== Example

The following example deletes the feature created by the <<create-example>> and replaced with a new feature in the <<replace-example>>.  A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

[#delete-example,reftext=`Delete Example`]
.Delete an Existing Feature Example
include::../examples/json/ex04_delete.adoc[]
