== Requirements Class Coordinate Reference Systems by Reference

[[crs-overview]]
=== Overview

include::requirements/requirements_class_crs.adoc[]

The <<OAFeat-1,OGC API - Features - Part 1: Core>> standard defines support
for only two coordinate reference systems:

* WGS 84 longitude/latitude
* WGS 84 longitude/latitude plus ellipsoidal height

This extensions defines the behaviour of a server that supports additional
coordinate reference systems.

include::requirements/crs/REQ_crs-uri.adoc[]

[[crs-discovery]]
=== Discovery

==== CRS identifier list

include::requirements/crs/REQ_fc-md-crs-list.adoc[]

include::requirements/crs/REQ_fc-md-crs-list-defaultCrs.adoc[]

The list of supported CRS identifiers in the collection metadata may include
these defaults but this is not a requirement.

==== Storage CRS 

The storage CRS for a feature collection is the CRS identifier that may be
used to retrieve features from the server without the need to apply a CRS
transformation.

include::requirements/crs/REQ_fc-md-storageCrs.adoc

==== Global list of CRS identifiers

To prevent unnecessary duplication of lists of supported CRS identifiers in
the collections metadata, a global list of supported CRS identifiers may be
provided as part of the feature collections metadata.

This global list of CRS identifiers is not automatically inherited by each
collection offered by the service.  Rather the global list of CRS 
identifiers must be referenced in the collection metadata using a JSON
link.

include::requirements/crs/REQ_fc-md-crs-list-global.adoc[]

The following example illustrates the used of a global list of CRS identifiers.

[[example_1]]
.Collections metadata containing a global list of CRS identifiers
=================
[source,JSON]
----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/buildings.xsd",
      "rel": "describedBy", "type": "application/xml", "title": "GML application schema for Acme Corporation building data" },
    { "href": "http://download.example.org/buildings.gpkg",
      "rel": "enclosure", "type": "application/geopackage+sqlite3", "title": "Bulk download (GeoPackage)", "length": 472546 }
  ],
  "crs": [
     "http://www.opengis.net/def/crs/EPSG/0/4326",
     "http://www.opengis.net/def/crs/EPSG/0/3857",
     "http://www.opengis.net/def/crs/EPSG/0/3395",
     "http://www.opengis.net/def/crs/EPSG/0/4267",
     "http://www.opengis.net/def/crs/EPSG/0/4269",
     "http://www.opengis.net/def/crs/EPSG/0/26716",
     "http://www.opengis.net/def/crs/EPSG/0/26717",
     "http://www.opengis.net/def/crs/EPSG/0/26718",
     "http://www.opengis.net/def/crs/EPSG/0/26719",
     "http://www.opengis.net/def/crs/EPSG/0/26916",
     "http://www.opengis.net/def/crs/EPSG/0/26917",
     "http://www.opengis.net/def/crs/EPSG/0/26918",
     "http://www.opengis.net/def/crs/EPSG/0/26919",
     "http://www.opengis.net/def/crs/EPSG/0/32616",
     "http://www.opengis.net/def/crs/EPSG/0/32617",
     "http://www.opengis.net/def/crs/EPSG/0/32618",
     "http://www.opengis.net/def/crs/EPSG/0/32619",
     "http://www.opengis.net/def/crs/EPSG/0/32188"
  ],
  "collections": [
     {
       "id": "bonn_buildings",
       "title": "Bonn Buildings",
       "description": "Buildings in the city of Bonn.",
       "extent": {
         "spatial": {
           "bbox": [ [ 7.01, 50.63, 7.22, 50.78 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/bonn_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "Bonn Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ],
       "crs": [
          #/crs,
          "http://www.opengis.net/def/crs/OGC/1.3/CRS41001",
          "http://www.opengis.net/def/crs/CUBEWERX/0/42101",
          "http://www.opengis.net/def/crs/CUBEWERX/0/42103",
          "http://www.opengis.net/def/crs/CUBEWERX/0/42105",
          "http://www.opengis.net/def/crs/ESRI/0/102002",
       ]
     },
     {
       "id": "tor_buildings",
       "title": "Toronto Buildings",
       "description": "Buildings in the city of Toronto.",
       "extent": {
         "spatial": {
           "bbox": [ [ -79.62, 43.58, -79.12, 43.87 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/tor_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "Toronto Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ],
       "crs": [
          #/crs
       ]
     },
     {
       "id": "dc_buildings",
       "title": "Washington DC Buildings",
       "description": "Buildings in the city of Washington DC.",
       "extent": {
         "spatial": {
           "bbox": [ [ -77.12, 38.80, -76.89, 39.01 ] ]

         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/dc_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "DC Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ]
     }
  ]
}
----
=================

The `bonn_buildings` collection is offered in all the coordinate reference
systems specified in the global list plus five other coordinate reference
systems.
The `tor_buildings` collection is offered in the coordinate reference systems 
specified in the global list.
The `dc_buildings` collection, not having a crs property, is only offered in
the default CRS (i.e. WGS84 longitude, latitude).

==== CRS identifier format

include::requirements/crs/REQ_crs-format-model.adoc[]

Other formats may be supported as well but they are not described in this
standard.

[[crs-query]]
=== Query

==== Parameter bbox-crs

The `bbox-crs` parameter may be used to assert the CRS used for the coordinate
values of the `bbox` parameter.

include::requirements/crs/REQ_fc-bbox-crs-definition.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-valid-values.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-default-value.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-action.adoc[]

include::requirements/crs/REQ_bbox-crs-exception.adoc[]

The following fragment illustrates the use of the `bbox-crs` parmeter:

[[example_2]]
.Specifying a bounding box in one of the supported coordinate reference systems
=================
[source]
----
   ...&bbox=160.6,-155.95,-170,-25.89&bbox-crs=http://www.opengis.net/...
----
=================

==== Parameter crs

include::requirements/crs/REQ_fc-crs-definition.adoc[]

include::requirements/crs/REQ_fc-crs-valid-value.adoc[]

include::requirements/crs/REQ_fc-crs-default-value.adoc[]

include::requirements/crs/REQ_fc-crs-action.adoc[]

include::requirements/crs/REQ_fc-crs-action-exception.adoc[]

include::requirements/crs/REQ_crs-exception.adoc[]

The following fragment illustrated the use of the `crs` parameter:

[[example_3]]
.Retrieving features from a collection in one of the supported coordinate reference systems
=================
[source]
----
.../collections/buildings/items?crs=http://www.opengis.net/def/crs/epsg/0/26703&...
----
=================

==== Output format considerations

OGC API - Features - Part 1: Core defines three conformance classes related
to the output formats:

   - GML
   - GeoJSON
   - HTML

GML has full CRS support and no further requirements are imposed by this
standard.

GeoJSON normatively supports WGS84 (lon,lat) but the "prior arrangement"
provision allows other coordinate systems to be used.

include::requirements/crs/REQ_geojson.adoc[]

NOTE: Need to do more work on HTML!

HTML only supports WGS84 based on schema.org dependency; not sure if this is
an issue but schema.org annotations seem to require WGS84 (lat,lon) yet WFS
core requires lon,lat by default.

==== Coordinate system and axis order

Because of the inconsistent provision of coordinate reference system metadata
in geospatial encodings and the continued confusion caused by the axis order
of coordinates, this standard defines a mechanism for a server to clearly and
unambiguously assert the coordinate reference system and axis order being used
in a response document independent of the requested output format.

include::requirements/crs/REQ_ogc-crs-header.adoc[]

include::requirements/crs/REQ_ogc-crs-header-value.adoc[]

include::requirements/crs/REQ_ogc-crs-header-axis-order-value.adoc[]

include::requirements/crs/REQ_ogc-crs-header-axis-names.adoc[]

include::requirements/crs/REQ_ogc-crs-header-axis-order-action.adoc[]

The following example illustrates the use of the `OGC-CRS` header.

[[example_4]]
.HTTP header declaring the CRS and axis order used in the body of the response
=================
[source]
----
   OGC-CRS: http://www.opengis.net/def/crs/OGC/1.3/CRS84; axisOrder=lon,lat
----
=================
