== Requirements Class Coordinate Reference Systems by Reference

[[crs-overview]]
=== Overview

include::requirements/requirements_class_crs.adoc[]

The <<OAFeat-1,OGC API - Features - Part 1: Core>> standard defines support
for only two coordinate reference systems:

* WGS 84 longitude/latitude
* WGS 84 longitude/latitude plus ellipsoidal height

This extensions defines the behaviour of a server that supports additional
coordinate reference systems.

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/295[Open issue 295] +
This draft is specific to Features and extends the resources
'feature collection', 'features' and 'feature'. However, in general
the approach specified in this draft should also be applicable to
other resource types and feedback would be welcome how such reuse
could be improved.

include::requirements/crs/REQ_crs-uri.adoc[]

include::recommendations/crs/REC_crs-format-model.adoc[]

[[crs-discovery]]
=== Discovery

==== CRS identifier list

include::requirements/crs/REQ_fc-md-crs-list.adoc[]

The default CRS -- that is the CRS used unless something else is explicitly
requested -- is defined in <<OAFeat-1,OGC API - Features - Part 1:
Core>> as:

* http://www.opengis.net/def/crs/OGC/1.3/CRS84 (for coordinates without height)
* http://www.opengis.net/def/crs/OGC/0/CRS84h (for coordinates with height)

The list of supported CRS identifiers in the collection metadata may include
these defaults but this is not a requirement.

==== Storage CRS

The storage CRS for a spatial feature collection is the CRS identifier that
may be used to retrieve features from that collection without the need to apply
a CRS transformation.

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/264[Open issue 264] +
To align with the new version of ISO 19111 / OGC Abstract Specification Topic 2,
it should also be possible to state the
link:http://docs.opengeospatial.org/as/18-005r4/18-005r4.html#68[coordinate epoch]
of the data (if known),
if the storage CRS is a dynamic CRS. In this case, it should also be recommended
to use a specific realization, not a CRS using a datum ensemble.

include::requirements/crs/REQ_fc-md-storageCrs.adoc[]

include::requirements/crs/REQ_fc-md-storageCrs-valid-value.adoc[]

The following schema fragment extends the collection metadata to add the
`storageCRS` property.

[source,YAML]
----
type: object
required:
  - id
  - links
properties:
  id:
    description: identifier of the collection used, for example, in URIs
    type: string
    example: address
  title:
    description: human readable title of the collection
    type: string
    example: address
  description:
    description: a description of the features in the collection
    type: string
    example: An address.
  links:
    type: array
    items:
      $ref: link.yaml
    example:
      - href: http://data.example.com/buildings
        rel: item
      - href: http://example.com/concepts/buildings.html
        rel: describedby
        type: text/html
  extent:
    $ref: extent.yaml
  itemType:
    description: indicator about the type of the items in the collection (the default value is 'feature').
    type: string
    default: feature
  crs:
    description: the list of CRS identifiers supported by the service
    type: array
    items:
      type: string
    default:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
    example:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
      - http://www.opengis.net/def/crs/EPSG/0/4326
  storageCrs:
     description: the CRS identifier, from the list of supported CRS identifiers, that may be used to retrieve features from a collection without the need to apply a CRS transformation
     type: string
     format: uri
----

==== Global list of CRS identifiers

To prevent unnecessary duplication of lists of supported CRS identifiers in
the collection metadata, a global list of supported CRS identifiers may be
provided as part of the collections metadata.

This global list of CRS identifiers is not automatically inherited by each
collection offered by the service.  Rather the global list of CRS identifiers
must be explicitly referenced in the collection metadata using a
JSON Pointer (RFC 6901).

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/274[Open issue 274] +
We are looking for feedback what option would be best to encode a reference to
the global list (a JSON Pointer, a JSON Reference, or something else). What works
best for clients parsing the response?

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/315[Open issue 315] +
For large lists of supported CRS, the global CRS list could be placed in its
own resource.

include::requirements/crs/REQ_fc-md-crs-list-global.adoc[]

The following schema fragment extends the collections metadata to add the `crs`
property which contains the global list of CRS identifiers.

[source,YAML]
----
type: object
required:
  - links
  - collections
properties:
  links:
    type: array
    items:
      $ref: link.yaml
  crs:
    description: a list of CRS identifiers that are supported for more that one feature collection offered by the service
    type: array
    items:
      type: string
      format: uri
  collections:
    type: array
    items:
      $ref: collection.yaml
----

The following example illustrates the used of a global list of CRS identifiers.

[[example_1]]
.Collections metadata containing a global list of CRS identifiers
=================
[source,JSON]
----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/buildings.xsd",
      "rel": "describedby", "type": "application/xml", "title": "GML application schema for Acme Corporation building data" },
    { "href": "http://download.example.org/buildings.gpkg",
      "rel": "enclosure", "type": "application/geopackage+sqlite3", "title": "Bulk download (GeoPackage)", "length": 472546 }
  ],
  "crs": [
     "http://www.opengis.net/def/crs/EPSG/0/4326",
     "http://www.opengis.net/def/crs/EPSG/0/3857",
     "http://www.opengis.net/def/crs/EPSG/0/3395",
     "http://www.opengis.net/def/crs/EPSG/0/4267",
     "http://www.opengis.net/def/crs/EPSG/0/4269",
     "http://www.opengis.net/def/crs/EPSG/0/26716",
     "http://www.opengis.net/def/crs/EPSG/0/26717",
     "http://www.opengis.net/def/crs/EPSG/0/26718",
     "http://www.opengis.net/def/crs/EPSG/0/26719",
     "http://www.opengis.net/def/crs/EPSG/0/26916",
     "http://www.opengis.net/def/crs/EPSG/0/26917",
     "http://www.opengis.net/def/crs/EPSG/0/26918",
     "http://www.opengis.net/def/crs/EPSG/0/26919",
     "http://www.opengis.net/def/crs/EPSG/0/32616",
     "http://www.opengis.net/def/crs/EPSG/0/32617",
     "http://www.opengis.net/def/crs/EPSG/0/32618",
     "http://www.opengis.net/def/crs/EPSG/0/32619",
     "http://www.opengis.net/def/crs/EPSG/0/32188"
  ],
  "collections": [
     {
       "id": "bonn_buildings",
       "title": "Bonn Buildings",
       "description": "Buildings in the city of Bonn.",
       "extent": {
         "spatial": {
           "bbox": [ [ 7.01, 50.63, 7.22, 50.78 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/bonn_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "Bonn Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ],
       "crs": [
          "#/crs",
          "http://www.opengis.net/def/crs/OGC/1.3/CRS41001",
          "http://www.opengis.net/def/crs/OGC/0/2246",
          "http://www.opengis.net/def/crs/OGC/0/3130",
          "http://www.opengis.net/def/crs/OGC/0/3634",
          "http://www.opengis.net/def/crs/OGC/0/6702",
       ]
     },
     {
       "id": "tor_buildings",
       "title": "Toronto Buildings",
       "description": "Buildings in the city of Toronto.",
       "extent": {
         "spatial": {
           "bbox": [ [ -79.62, 43.58, -79.12, 43.87 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/tor_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "Toronto Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ],
       "crs": [
          "#/crs"
       ]
     },
     {
       "id": "dc_buildings",
       "title": "Washington DC Buildings",
       "description": "Buildings in the city of Washington DC.",
       "extent": {
         "spatial": {
           "bbox": [ [ -77.12, 38.80, -76.89, 39.01 ] ]

         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/dc_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "DC Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ]
     }
  ]
}
----
=================

The `bonn_buildings` collection is offered in all the coordinate reference
systems specified in the global list plus five other coordinate reference
systems.
The `tor_buildings` collection is offered in the coordinate reference systems
specified in the global list.
The `dc_buildings` collection, not having a crs property, is only offered in
the default CRS (i.e. WGS84 longitude, latitude).

[[crs-query]]
=== Query

==== Parameter bbox-crs

The `bbox-crs` parameter may be used to assert the CRS used for the coordinate
values of the `bbox` parameter.

include::requirements/crs/REQ_fc-bbox-crs-definition.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-valid-values.adoc[]

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/294[Open issue 294] +
The wording of the requirement may be unclear.

include::requirements/crs/REQ_fc-bbox-crs-default-value.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-action.adoc[]

include::requirements/crs/REQ_bbox-crs-exception.adoc[]

The following fragment illustrates the use of the `bbox-crs` parameter:

[[example_2]]
.Specifying a bounding box in one of the supported coordinate reference systems
=================
[source]
----
   ...&bbox=160.6,-155.95,-170,-25.89&bbox-crs=http://www.opengis.net/...
----
=================

==== Parameter crs

include::requirements/crs/REQ_fc-crs-definition.adoc[]

include::requirements/crs/REQ_fc-crs-valid-value.adoc[]

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/294[Open issue 294] +
The wording of the requirement may be unclear.

include::requirements/crs/REQ_fc-crs-default-value.adoc[]

include::requirements/crs/REQ_fc-crs-action.adoc[]

include::requirements/crs/REQ_fc-crs-action-exception.adoc[]

include::requirements/crs/REQ_crs-exception.adoc[]

The following fragment illustrated the use of the `crs` parameter:

[[example_3]]
.Retrieving features from a collection in one of the supported coordinate reference systems
=================
[source]
----
.../collections/buildings/items?crs=http://www.opengis.net/def/crs/epsg/0/26703&...
----
=================

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/153[Open issue 153] +
There is ongoing work to add negotiation of the CRS to the content negotiation
process. However, this is still draft and not widely supported. For this reason,
such a capability is considered right now only for a future revision.

==== Output format considerations

OGC API - Features - Part 1: Core defines three conformance classes related
to the output formats:

- GML/XML
- GeoJSON/JSON
- HTML

===== Collections and Collection resources

This document specifies extensions to the Collections resource (the global list of
coordinate reference systems) and the Collection resource (the storage CRS including
the associated coordinate epoch).

How these extensions are reflected in each
encoding is not fully specified by this standard, except for JSON-based or
YAML-based encodings where the extensions are fully specified by the OpenAPI
schema components.

For HTML, the requirement http://www.opengis.net/spec/ogcapi-features-1/1.0/req/html/content
applies and the additional information has to included in the body of the
HTML document.

For XML, the content model of the `core:Collections` element needs to be
extended with additional elements.

NOTE: What do we do? Should we update the schema with Part 1 version 1.0.1
to allow arbitrary additional elements at the end of the complex types
`core:CollectionsType` and `core:CollectionType`. Then we could specify
here the additional elements. Or do we leave this open?

===== Features and Feature resources

GML has full CRS support and no further conventions are imposed by this
standard.

HTML does not have any provisions for spatial geometries and coordinate
reference systems. However, note that schema.org that is embedded in
HTML only supports WGS84 in the axis order latitude/longitude, so any
coordinates in schema.org markup will have to be in that coordinate reference
system, independent of the requested coordinate reference system.

GeoJSON normatively supports WGS84 (without height: http://www.opengis.net/def/crs/OGC/1.3/CRS84[CRS84]; with height: http://www.opengis.net/def/crs/OGC/0/CRS84h[CRS84h]), but the "prior arrangement" provision allows other coordinate
systems to be used.

include::requirements/crs/REQ_geojson.adoc[]

An explicit request be a client with a query parameter
`crs` establishes a prior arrangement. It is the responsibility of the
client that submits the request to handle the coordinates in the response
correctly. In particular, clients should not make the GeoJSON document available
to others unless they are aware of the prior arrangement.

This standard does not specify any standardized approach to encoding
coordinate reference system information in a GeoJSON document.

The first paragraph of section 4 in GeoJSON also states:

> An OPTIONAL third-position element SHALL
be the height in meters above or below the WGS 84 reference
ellipsoid. In the absence of elevation values, applications
sensitive to height or depth SHOULD interpret positions as being at
local ground or sea level.

If the requested coordinate reference system includes the vertical axis,
the third-position element has to be interpreted according to that coordinate
reference system, not as if it would be relative to the WGS 84 reference
ellipsoid.

==== Coordinate system and axis order

Because of the inconsistent provision of coordinate reference system metadata
in geospatial encodings and the continued confusion caused by the axis order
of coordinates, this standard defines a mechanism for a server to clearly and
unambiguously assert the coordinate reference system and axis order being used
in a response document independent of the requested output format.

include::requirements/crs/REQ_ogc-crs-header.adoc[]

include::requirements/crs/REQ_ogc-crs-header-value.adoc[]

include::requirements/crs/REQ_ogc-crs-header-axis-order-value.adoc[]

include::requirements/crs/REQ_ogc-crs-header-axis-names.adoc[]

include::requirements/crs/REQ_ogc-crs-header-axis-order-action.adoc[]

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/153[Open issue 153] +
The draft content negotiation by CRS specifies a `Content-Crs` header that
could be used instead of a custom `OGC-CRS` header. The `Content-Crs` header
just states the CRS, but has no option to state the axis order. +
It is a related general question, if a capability to state the axis order
would be helpful or not.

The following example illustrates the use of the `OGC-CRS` header.

[[example_4]]
.HTTP header declaring the CRS and axis order used in the body of the response
=================
[source]
----
   OGC-CRS: http://www.opengis.net/def/crs/OGC/0/4326; axisOrder=lon,lat
----
=================
