== Requirements Class Coordinate Reference Systems by Reference

[[crs-overview]]
=== Overview

include::requirements/requirements_class_crs.adoc[]

The <<OAFeat-1,OGC API - Features - Part 1: Core>> standard defines support
for only two coordinate reference systems:

* WGS 84 longitude, latitude
* WGS 84 longitude, latitude, ellipsoidal height

This extensions defines the behaviour of a server that supports additional
coordinate reference systems.

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/295[Open issue 295] +
This draft is specific to Features and extends the resources
'feature collection', 'features' and 'feature'. However, in general
the approach specified in this draft should also be applicable to
other resource types and feedback would be welcome how such reuse
could be improved.

include::requirements/crs/REQ_crs-uri.adoc[]

include::recommendations/crs/REC_crs-format-model.adoc[]

For more information, see https://docs.opengeospatial.org/pol/09-048r5.html#_production_rule_for_specification_element_names[section 6.2 in OGC Name Type Specification, Part 1].

Note that while the EPSG register itself is versioned, the registered items
are not versioned and the "version" is always "0" in URIs of the authority "EPSG".

[[crs-discovery]]
=== Discovery

==== CRS identifier list

include::requirements/crs/REQ_fc-md-crs-list.adoc[]

The list has to include the default CRS -- that is the CRS used unless something else is explicitly requested -- is defined in <<OAFeat-1,OGC API - Features - Part 1: Core>> as:

* http://www.opengis.net/def/crs/OGC/1.3/CRS84 (for coordinates without height)
* http://www.opengis.net/def/crs/OGC/0/CRS84h (for coordinates with height)

==== Storage CRS

The storage CRS for a spatial feature collection is the CRS identifier that
may be used to retrieve features from that collection without the need to apply
a CRS transformation.

Note that coordinates referenced to a dynamic coordinate reference system are
ambiguous, if the coordinate epoch is unknown. It is therefore recommended
to also provide the coordinate epoch when the storage CRS is dynamic,
such as an ITRF realization or WGS 84. For more information on dynamic
coordinate reference systems and coordinate epoch, please see
link:http://docs.opengeospatial.org/as/18-005r4/18-005r4.html[OGC Abstract Specification Topic 2: Referencing by coordinates].

include::requirements/crs/REQ_fc-md-storageCrs.adoc[]

include::recommendations/crs/REC_fc-md-storageCrs-avoid-ensemble.adoc[]

include::recommendations/crs/REC_fc-md-coordinateEpoch.adoc[]

include::requirements/crs/REQ_fc-md-storageCrs-valid-value.adoc[]

The following schema fragment extends the collection metadata to add the
`storageCrs` and `storageCrsCoordinateEpoch` properties.

[source,YAML]
----
type: object
required:
  - id
  - links
properties:
  id:
    description: identifier of the collection used, for example, in URIs
    type: string
    example: address
  title:
    description: human readable title of the collection
    type: string
    example: address
  description:
    description: a description of the features in the collection
    type: string
    example: An address.
  links:
    type: array
    items:
      $ref: link.yaml
    example:
      - href: http://data.example.com/buildings
        rel: item
      - href: http://example.com/concepts/buildings.html
        rel: describedby
        type: text/html
  extent:
    $ref: extent.yaml
  itemType:
    description: indicator about the type of the items in the collection (the default value is 'feature').
    type: string
    default: feature
  crs:
    description: the list of CRS identifiers supported by the service
    type: array
    items:
      type: string
    default:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
    example:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
      - http://www.opengis.net/def/crs/EPSG/0/4326
  storageCrs:
     description: the CRS identifier, from the list of supported CRS identifiers, that may be used to retrieve features from a collection without the need to apply a CRS transformation
     type: string
     format: uri
  storageCrsCoordinateEpoch:
     description: date at which coordinates in the spatial feature collection are referenced to the dynamic coordinate reference system in `storageCrs`, expressed as a decimal year in the Gregorian calendar
     type: number
     example: '2017-03-25 in the Gregorian calendar is epoch 2017.23'
----

==== Global list of CRS identifiers

To prevent unnecessary duplication of lists of supported CRS identifiers in
the collection object, a global list of supported CRS identifiers may be
provided as part of the collections object.

This global list of CRS identifiers is not automatically inherited by each
collection offered by the service.  Rather the global list of CRS identifiers
must be explicitly referenced in the `crs` property of the collection object
using a link:https://tools.ietf.org/rfc/rfc6901.txt[JSON Pointer (RFC 6901)].

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/315[Open issue 315] +
For large lists of supported CRS, the global CRS list could be placed in its
own resource.

include::requirements/crs/REQ_fc-md-crs-list-global.adoc[]

Note that only a local JSON Pointer within the same document is supported.

The following schema fragment extends the core collections object to add the `crs`
property which contains the global list of CRS identifiers.

[source,YAML]
----
allOf:
- $ref: 'http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collections.yaml'
- type: object
  properties:
    crs:
      description: a global list of CRS identifiers that are supported by spatial feature collections offered by the service
      type: array
      items:
        type: string
        format: uri
----

The following example illustrates the used of a global list of CRS identifiers.

[[example_1]]
.Collections object containing a global list of CRS identifiers
=================
[source,JSON]
----
{
  "links": [
    { "href": "http://data.example.org/collections.json",
      "rel": "self", "type": "application/json", "title": "this document" },
    { "href": "http://data.example.org/collections.html",
      "rel": "alternate", "type": "text/html", "title": "this document as HTML" },
    { "href": "http://schemas.example.org/1.0/buildings.xsd",
      "rel": "describedby", "type": "application/xml", "title": "GML application schema for Acme Corporation building data" },
    { "href": "http://download.example.org/buildings.gpkg",
      "rel": "enclosure", "type": "application/geopackage+sqlite3", "title": "Bulk download (GeoPackage)", "length": 472546 }
  ],
  "crs": [
     "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
     "http://www.opengis.net/def/crs/EPSG/0/4326",
     "http://www.opengis.net/def/crs/EPSG/0/3857",
     "http://www.opengis.net/def/crs/EPSG/0/3395"
  ],
  "collections": [
     {
       "id": "bonn_buildings",
       "title": "Bonn Buildings",
       "description": "Buildings in the city of Bonn.",
       "extent": {
         "spatial": {
           "bbox": [ [ 7.01, 50.63, 7.22, 50.78 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/bonn_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "Bonn Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ],
       "crs": [
          "#/crs",
          "http://www.opengis.net/def/crs/EPSG/0/4258",
          "http://www.opengis.net/def/crs/EPSG/0/25831",
          "http://www.opengis.net/def/crs/EPSG/0/25832"
       ]
     },
     {
       "id": "tor_buildings",
       "title": "Toronto Buildings",
       "description": "Buildings in the city of Toronto.",
       "extent": {
         "spatial": {
           "bbox": [ [ -79.62, 43.58, -79.12, 43.87 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/tor_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "Toronto Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
       ],
       "crs": [
          "#/crs"
       ]
     },
     {
       "id": "dc_buildings",
       "title": "Washington DC Buildings",
       "description": "Buildings in the city of Washington DC.",
       "extent": {
         "spatial": {
           "bbox": [ [ -77.12, 38.80, -76.89, 39.01 ] ]
         },
         "temporal": {
           "interval": [ [ "2010-02-15T12:34:56Z", null ] ]
         }
       },
       "links": [
         { "href": "http://data.example.org/collections/dc_buildings/items",
           "rel": "items", "type": "application/geo+json",
           "title": "DC Buildings" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/",
           "rel": "license", "type": "text/html",
           "title": "CC0-1.0" },
         { "href": "https://creativecommons.org/publicdomain/zero/1.0/rdf",
           "rel": "license", "type": "application/rdf+xml",
           "title": "CC0-1.0" }
         ],
         "crs": [
           "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
       ]
     }
  ]
}
----
=================

The `bonn_buildings` collection is offered in all the coordinate reference
systems specified in the global list plus three other coordinate reference
systems.

The `tor_buildings` collection is offered in the coordinate reference systems
specified in the global list.

The `dc_buildings` collection is only offered in the default CRS (i.e. WGS84
longitude, latitude).

[[crs-query]]
=== Query

==== Parameter bbox-crs

The `bbox-crs` parameter may be used to assert the CRS used for the coordinate
values of the `bbox` parameter.

include::requirements/crs/REQ_fc-bbox-crs-definition.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-valid-values.adoc[]

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/294[Open issue 294] +
The wording of the requirement may be unclear.

include::requirements/crs/REQ_fc-bbox-crs-default-value.adoc[]

include::requirements/crs/REQ_fc-bbox-crs-action.adoc[]

include::requirements/crs/REQ_bbox-crs-exception.adoc[]

The following fragment illustrates the use of the `bbox-crs` parameter:

[[example_2]]
.Specifying a bounding box in one of the supported coordinate reference systems
=================
[source]
----
   ...&bbox=160.6,-155.95,-170,-25.89&bbox-crs=http://www.opengis.net/...
----
=================

==== Parameter crs

include::requirements/crs/REQ_fc-crs-definition.adoc[]

include::requirements/crs/REQ_fc-crs-valid-value.adoc[]

CAUTION: link:https://github.com/opengeospatial/ogcapi-features/issues/294[Open issue 294] +
The wording of the requirement may be unclear.

include::requirements/crs/REQ_fc-crs-default-value.adoc[]

include::requirements/crs/REQ_fc-crs-action.adoc[]

include::requirements/crs/REQ_fc-crs-action-exception.adoc[]

include::requirements/crs/REQ_crs-exception.adoc[]

The following fragment illustrated the use of the `crs` parameter:

[[example_3]]
.Retrieving features from a collection in one of the supported coordinate reference systems
=================
[source]
----
.../collections/buildings/items?crs=http://www.opengis.net/def/crs/epsg/0/26703&...
----
=================

==== Output format considerations

OGC API - Features - Part 1: Core defines three conformance classes related
to the output formats:

- GML
- GeoJSON
- HTML

GML has full CRS support and no further requirements are imposed by this
standard.

GeoJSON normatively supports WGS84 (lon,lat) but the "prior arrangement"
provision allows other coordinate systems to be used.

include::requirements/crs/REQ_geojson.adoc[]

NOTE: Need to do more work on HTML!

HTML only supports WGS84 based on schema.org dependency; not sure if this is
an issue but schema.org annotations seem to require WGS84 (lat,lon) yet WFS
core requires lon,lat by default.

==== Coordinate reference system information independent of the feature encoding

Because of the inconsistent provision of coordinate reference system metadata
in geospatial encodings, this standard defines a mechanism for a server to clearly and
unambiguously assert the coordinate reference system being used
in a response document independent of the requested output format.

include::requirements/crs/REQ_ogc-crs-header.adoc[]

include::requirements/crs/REQ_ogc-crs-header-value.adoc[]

NOTE: The header is consistent with the
https://github.com/opengeospatial/conneg-by-crs[draft "content negotiation by coordinate reference system" specification].

The following example illustrates the `Content-Crs` header in a response.

[[example_4]]
.HTTP header declaring the CRS and axis order used in the body of the response
=================
[source]
----
   $ curl -i "https://example.com/api/v1/collections/poi/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3395"

   HTTP/1.1 200 OK
   Date: Sun, 24 May 2020 15:30:56 GMT
   Content-Type: application/geo+json
   Content-Language: en
   Content-Crs: <http://www.opengis.net/def/crs/EPSG/0/3395>
   Link: <https://example.com/api/v1/collections/poi/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3395&f=json>; rel="self"; title="This document"; type="application/geo+json"
   Link: <https://example.com/api/v1/collections/poi/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3395&f=html>; rel="alternate"; title="This document as HTML"; type="text/html"
   Link: <https://example.com/api/v1/collections/poi>; rel="collection"; title="The collection the feature belongs to"
   Vary: Accept-Language,Accept-Encoding
   Content-Length: 1064

   ...
----
=================
