== Scope

This document specifies an extension to the <<OAFeat-1,OGC API - Features - Part 1: Core>> standard that defines the behaviour of a server that supports the ability to present geometry valued properties in a response document in one from a list of supported Coordinates Reference Systems (CRS).  This list of supported CRSs is in addition to the default values specified in <<OAFeat-1,OGC API - Features - Part 1: Core>>.

This document assumes that each supported CRS can be referenced by a unique resource identifier (i.e. a URI) such as `http://www.opengis.net/def/crs/EPSG/0/4326'.

This document specifies:

* How, for each offered feature collection, a server advertises the list of supported CRS identifiers.

* How the coordinates of geometry valued feature properties can be accessed in one of the supported CRSs.

* How features can be accessed from the server using a bounding box specified in one of the supported CRSs.

* How a server can declare the coordinate reference system used to present feature resources.
