== Conformance

This standard defines the following requirements classes, 
grouped by their standardization target:

* Servers that evaluate filter expressions
** <<rc_basic-cql2,Basic CQL2>>
** <<rc_advanced-comparison-operators,Advanced Comparison Operators>>
** <<rc_case-insensitive-comparison,Case-insensitive Comparisons>>
** <<rc_accent-insensitive-comparison,Accent-insensitive Comparisons>>
** <<rc_basic-spatial-operators,Basic Spatial Operators>>
** <<rc_spatial-operators,Spatial Operators>>
** <<rc_temporal-operators,Temporal Operators>>
** <<rc_array-operators,Array Operators>>
** <<rc_property-property,Property-Property Comparisons>>
** <<rc_functions,Functions>>
** <<rc_arithmetic,Arithmetic Expressions>>
* Representations of a filter expression
** <<rc_cql2-text,CQL2 Text encoding>>
** <<rc_cql2-json,CQL2 JSON encoding>>

NOTE: "Server" is used in this Standard to identify any executable software that is
able to evaluate filter expressions on data.

The <<rc_basic-cql2,Basic CQL2>> requirements class defines the minimal subset
of the Common Query Language (CQL2) that all implementations must support
("Basic CQL2"). Basic CQL2 is intended to be a useful, but limited set of
predicates that support fine-grained read-access to collections of resources. 

The specific set of operators defined in this requirements class is:

* Logical operators:
** and
** or
** not
* Comparison operators:
** equal to
** not equal to
** less than
** less than or equal to
** greater than
** greater than or equal to
** is null

Basic CQL2 only requires support for property-literal comparisons. That means that servers only have to support property references as expressions on the left hand side of an operator, and only literal values as expressions on the right hand side.

An encoding of CQL2 may be used as the value of the filter parameters defined
in the "Filter" requirements class specified in <<OGCFeat-3,OGC API - Features - Part 3: Filtering>>.

The <<rc_advanced-comparison-operators,Advanced Comparison Operators>> requirements class specifies additional comparison operators:

* like
* between
* in

The <<rc_case-insensitive-comparison,Case-insensitive Comparison>> requirements class adds an operator to support case-insensitive string comparisons:

* casei

The <<rc_accent-insensitive-comparison,Accent-insensitive Comparison>> requirements class adds an operator to support accent-insensitive string comparisons:

* accenti

The <<rc_basic-spatial-operators,Basic Spatial Operators>> requirements class specifies minimal requirements for servers that support spatial operators. Only the following spatial operator must be supported:

* s_intersects

The <<rc_spatial-operators,Spatial Operators>> requirements class specifies requirements for servers that support a richer set of spatial operators.  The list of additional spatial operators that must be supported is:

* s_contains
* s_crosses
* s_disjoint
* s_equals
* s_overlaps
* s_touches
* s_within

The <<rc_temporal-operators,Temporal Operators>> requirements
class specifies requirements for servers that support temporal operators. 
The list of temporal operators that must be supported is:

* t_after
* t_before
* t_contains
* t_disjoint
* t_during
* t_equals
* t_finishedby
* t_finishes
* t_intersects
* t_meets
* t_metby
* t_overlappedby
* t_overlaps
* t_startedby
* t_starts

The <<rc_array-operators,Array Operators>> requirements class specifies
requirements for comparison operators for sets of values. 
The operators that must be supported are:

* a_containedby
* a_contains
* a_equals 
* a_overlaps

The <<rc_property-property,Property-Property Comparisons>> requirements class drops the permission to restrict expressions on the left hand side to properties and to restrict expressions on the right hand side to literal values. This supports property-property, but also literal-literal or literal-property comparisons.

The <<rc_functions,Functions>> requirements class specifies requirements for
supporting function calls (e.g. min, max, etc.) in a CQL2 expression. Function
calls are the primary means of extending the language. Implementations 
should provide a capability to discover the available functions.

The <<rc_arithmetic,Arithmetic Expressions>> requirements class specifies
requirements for supporting the standard set of arithmetic operators 
(`+`, `-`, `*`, `/`, `%`, `div`, and `^`) in a CQL2 expression.

The <<rc_cql2-text,CQL2 Text encoding>> requirements class defines
a text encoding for CQL2. Such an encoding is suitable for use with HTTP query
parameters such as the `filter` parameter defined by the "Filter" requirements class specified 
in <<OGCFeat-3,OGC API - Features - Part 3: Filtering>>.

The <<rc_cql2-json,CQL2 JSON encoding>> requirements class defines
a JSON encoding for CQL2. Such as encoding is suitable for use as the
body of an HTTP POST request.

Conformance with this standard shall be checked using all the relevant tests
specified in <<ats,Annex A>> of this document. The framework, concepts, and
methodology for testing, and the criteria to be achieved to claim conformance
are specified in the OGC Compliance Testing Policies and Procedures and the
OGC Compliance Testing web site.

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="40,60",options="header"]
|===
|Conformance class |URI
|<<ats_basic-cql2,Basic CQL2>> |http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2
|<<ats_advanced-comparison-operators,Advanced Comparison Operators>> |http://www.opengis.net/spec/cql2/1.0/conf/advanced-comparison-operators
|<<ats_case-insensitive-comparison,Case-insensitive Comparison>> |http://www.opengis.net/spec/cql2/1.0/conf/case-insensitive-comparison
|<<ats_accent-insensitive-comparison,Accent-insensitive Comparison>> |http://www.opengis.net/spec/cql2/1.0/conf/accent-insensitive-comparison
|<<ats_basic-spatial-operators,Basic Spatial Operators>> |http://www.opengis.net/spec/cql2/1.0/conf/basic-spatial-operators
|<<ats_spatial-operators,Spatial Operators>> |http://www.opengis.net/spec/cql2/1.0/conf/spatial-operators
|<<ats_temporal-operators,Temporal Operators>> |http://www.opengis.net/spec/cql2/1.0/conf/temporal-operators
|<<ats_array-operators,Array Operators>> |http://www.opengis.net/spec/cql2/1.0/conf/array-operators
|<<ats_property-property,Property-Property Comparisons>> |http://www.opengis.net/spec/cql2/1.0/conf/property-property
|<<ats_functions,Functions>> |http://www.opengis.net/spec/cql2/1.0/conf/functions
|<<ats_arithmetic,Arithmetic Expressions>> |http://www.opengis.net/spec/cql2/1.0/conf/arithmetic
|<<ats_cql2-text,CQL2 Text encoding>> |http://www.opengis.net/spec/cql2/1.0/conf/cql2-text
|<<ats_cql2-json,CQL2 JSON encoding>> |http://www.opengis.net/spec/cql2/1.0/conf/cql2-json 
|===
