== Scope

This document specifies the Common Query Language (CQL2) to express filter expressions on spatial and temporal data.

This document defines

* A text encoding for a CQL2 filter;
* A JSON encoding for a CQL2 filter.

NOTE: The CQL2 grammar contains all the necessary language elements of a general purpose expression language, including support for spatio-temporal values.
The focus of this version of the language are boolean-valued filter expressions. It is planned to potentially remove this restriction, while maintaining backward compatibility, allowing expressions that result in values of other data types, including geometries. Such expressions could be used, for example, in a styling language to specify parameter values, or to define derived properties. In this case, a particular use of CQL2 could specify the boolean-valued restriction separately, for example when used as a filter predicate expression, or as a styling rule selector. The usability of such an expression language, especially in the context of geometry types, would also greatly benefit from standardizing additional functions and/or operators e.g., to compute the geometry resulting from buffering or intersecting operations.
