== Terms, Definitions, Symbols and Abbreviated Terms

=== Terms and Definitions
This document used the terms defined in https://portal.ogc.org/public_ogc/directives/directives.php[OGC Policy Directive 49], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

[[boundary-def]]
==== boundary
set that represents the limit of an entity (ISO 19107:2019, definition 3.6)

NOTE: Boundary is most commonly used in the context of geometry, where the set is a collection of points or a collection of objects that represent those points. In other arenas, the term is used metaphorically to describe the transition between an entity and the rest of its domain of discourse.

[[collection-def]]
==== collection
a body of **resources** that belong or are used together; an aggregate, set, or group of related **resources** (http://docs.opengeospatial.org/DRAFTS/20-024.html#terms_and_definitions[OGC 20-024, OGC API - Common - Part 2: Collections]).

[[custom-function-def]]
==== custom function
**function** that is not specified in the CQL2 standard

NOTE: Custom functions require support for the <<rc_functions,Functions>> requirements class.

[[exterior-def]]
==== exterior
difference between the universe and the closure (ISO 19107:2019,definition 3.37)

NOTE: The concept of exterior is applicable to both topological and geometric complexes. 

[[filter-def]]
==== filter expression
**predicate** encoded for transmission between systems

[[function-def]]
==== function
rule that associates each element from a domain (source, or domain of the function) to a unique element in another domain (target, co-domain, or range) (ISO 19107:2003, definition 4.41)

[[interior]]
==== interior
set of all direct positions that are on a geometric object but which are not on its <<boundary-def,boundary>>

NOTE: The interior of a topological object is the continuous image of the interior of any of its geometric realizations. This is not included as a definition because it follows from a theorem of topology. Another way of saying this is that any point on a geometric object is in its interior if it can be placed inside a homeomorphic image of an open set in the Euclidean space of the object’s topological dimension.

[[standardized-function-def]]
==== standardized function
**function** specified in the CQL2 standard

[[predicate-def]]
==== predicate
set of computational operations applied to a data instance which evaluate to true or false (http://docs.opengeospatial.org/is/09-026r2/09-026r2.html[OGC Filter Encoding 2.0 Encoding Standard - With Corrigendum])

[[queryable-def]]
==== queryable
a token that represents a property of a resource that can be used in a **filter expression**

[[resource-def]]
==== resource
entity that might be identified (<<iso15836-2,Dublin Core Metadata Initiative - DCMI Metadata Terms>>)

[[case-folding-def]]
==== unicode case folding; case folding
process of making two texts which differ only in case identical for comparison purposes (https://www.w3.org/TR/charmod-norm/#definitionCaseFolding[W3C Character Model for the World Wide Web: String Matching])

NOTE: Case folding is meant for the purpose of case-insensitive string matching.

[[normalization-def]]
==== unicode normalization; normalization
process of removing alternate representations of equivalent sequences from textual data, to convert the data into a form that can be binary-compared for equivalence (https://www.unicode.org/glossary/#normalization[Glossary of Unicode Terms])

=== Symbols

* **&#x2229;** intersection, operation on two or more sets
* **&#x2227;** and, logical intersection
* **&#x2205;** empty set, the set having no members
* **&#x2260;** not equal
* **&#x2b04;** if and only if, logical equivalence between statements
* **&#x2286;** is a subset of
* **dim(x)** returns the maximum dimension (-1, 0, 1, or 2) of the geometric object x
* **I(x)** represents the interior of the geometric object x
* **B(x)** represents the boundary of the geometric object x
* **E(x)** represents the exterior of the geometric object x

=== Abbreviated terms

ABNF::
  Augmented Backus-Naur Form
API::
  Application Programming Interface
BNF::
  Backus-Naur Form 
CQL2::
  Common Query Language
CRS::
  Coordinate Reference System
DE-9IM::
  Dimensionally Extended Nine-Intersection Model
HTTP::
  Hypertext Transfer Protocol
HTTPS::
  Hypertext Transfer Protocol Secure
IANA::
  Internet Assigned Numbers Authority
JSON::
  JavaScript Object Notation
OGC::
  Open Geospatial Consortium
URI::
  Uniform Resource Identifier
WKT::
  Well-Known Text
YAML::
  YAML Ain't Markup Language
