[[cql2-core]]
== Requirements Class "Basic CQL2"

[[basic-cql2-overview]]
=== Overview

include::requirements/requirements_class_basic-cql2.adoc[]

This clause defines the core of a query language called `Common Query Language`
(CQL2) that may be used to construct filter expressions. This core is called Basic CQL2.

Subsequent clauses define additional filtering capabilities as well as several
encodings of CQL2.

[[basic-cql2_filter-expression]]
=== CQL2 filter expression

A CQL2 filter expression is an expression that defines a logically connected
set of predicates that are evaluated for each item of a collection.

A predicate is an expression that evaluates to the Boolean values of `TRUE`
or `FALSE` or that evaluates to the value `NULL` when dealing with unknown
values.

If a predicate evaluates to `TRUE` for an item, the item qualifies for
further processing such as presentation in the result set, being passed on
to the next predicate in the filter for further evaluation, and so forth.

If the predicate evaluates to `FALSE` or `NULL` for an item, the item is not
available for further processing.

A collection item that satisfies ALL the requirements of a CQL2 filter expression
evaluates to a Boolean value of `TRUE`; otherwise the CQL2 filter expression
evaluates to `FALSE`.

NOTE: The requirements in the rest of this specification only discuss predicates as evaluating to `TRUE` or `FALSE` and don't explicitly discuss predicates that evaluate to `NULL`.  For the purpose of evaluating a CQL2 filter expression, a query predicate that evaluates to `NULL` (i.e. of unknown value) is essentually the same as one that evaluates to `FALSE`.  That is, its effect is that a collection item being evaluated by the CQL2 filter expression would _not_ be passed on for further evaluation.

include::requirements/basic-cql2/REQ_cql2-filter.adoc[]

Literal values do not have to be supported on the left hand side of predicates and 
property references do not have to be supported on the right hand side of
predicates.

include::recommendations/basic-cql2/PER_cql2-filter.adoc[]

A Basic CQL2 filter expression can be constructed by logically connecting one
or more comparison predicates.

Support for the parts of CQL2 that are not part of Basic CQL2 is added in additional
requirements classes in <<cql2-enhancements>>:

* The rules `isLikePredicate`, `isBetweenPredicate` and `isInListPredicate` are added by requirements class <<rc_advanced-comparison-operators,Advanced Comparison Operators>>;
* Support for the `CASEI` operator is added by requirements class <<rc_case-insensitive-comparison,Case-insensitive Comparison>>;
* Support for the `ACCENTI` operator is added by requirements class <<rc_accent-insensitive-comparison,Accent-insensitive Comparison>>;
* The rule `spatialPredicate` is added by requirements classes <<rc_basic-spatial-operators,Basic Spatial Operators>> and <<rc_spatial-operators,Spatial Operators>>;
* The rule `temporalPredicate` is added by requirements class <<rc_temporal-operators,Temporal Operators>>.
* The rule `arrayPredicate` is added by requirements class <<rc_array-operators,Array Operators>>;
* The permission to not support the literal rules on the left hand side of predicates and the rule `propertyName` on the right hand side is removed by requirements class <<rc_property-property,Property-Property Comparisons>>;
* The rule `function` is added by requirements class <<rc_functions,Functions>>;
* The rule `arithmeticExpression` is added by requirements class <<rc_arithmetic,Arithmetic Expressions>>.

Examples of Basic CQL2 filter expressions are included in the subsequent sub-clauses.

[[basic-cql2_data-types-and-literals]]
=== Data types and literal values

This section documents the data types supported by Basic CQL2 and has examples 
of literal values for each data type. 

A literal value is any part of an CQL2 filter expression that is used
exactly as it is specified in the expression.

Other requirements classes add more data types. These are defined in the chapter
specifying the requirements class.

[[scalar-data-types]]
==== Scalar data types

The scalar data types are:

* "string": character strings (literal rule `characterLiteral`);
* "number": numbers including integers and floating point values (literal rule `numericLiteral`);
* "boolean": booleans (literal rule `booleanLiteral`);
* "timestamp": an instant with a granularity of a second or smaller (literal rule: `timestampLiteral`)
* "date": an instant with a granularity of a day (literal rule: `dateLiteral`)

For character string, numeric and boolean literals, the standard representations are used. For character string literals, embeded quotes are escaped using two consecutive single quotes (i.e. `''`).

Conceptually, an instant is a "temporal entity with zero extent or duration" [<<owl-time,Time Ontology in OWL>>]. In practice, the temporal position of an instant is described using data types where each value has some duration or granularity that is sufficient for the intended use of the data. 

CQL2 supports two commonly used granularities: a second or smaller (data type "timestamp") and days (data type "date"). Literal timestamps are always in the time zone UTC ("Z"), dates are local dates without an associated timezone. 

If timezone information is important for the intended use, then the "date" data type should not be used and the temporal information should be provided as an interval with start and end timestamps.

NOTE: While instants (timestamps and dates) are scalar data types that can be used with the basic comparison operators, intervals are more complex data types. Support for intervals is added in the requirements class <<rc_temporal-operators,Temporal Operators>> where intervals can be provided as arguments in temporal operators.

For timestamp and date values representations based on RFC 3339 are used:

* Text: a `DATE` or `TIMESTAMP` operator with a https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6[RFC 3339 `date-time` or `full-date` string]
* JSON: an object with a `date` or `timestamp` member with a https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6[RFC 3339 `date-time` or `full-date` string]

[[example_8_1_a]]
.Scalar literal examples
====

* character string
----
'This is a literal string.'
----
* character string with an escaped embeded quote 
----
'Via dell''Avvento'
----
* number
----
-100
3.14159
----
* boolean
----
true
false
----
* timestamp (Text)
----
TIMESTAMP('1969-07-20T20:17:40Z')
----
* timestamp (JSON)
[source,JSON]
----
{ "timestamp": "1969-07-20T20:17:40Z" }
----
* date (Text)
----
DATE('1969-07-20')
----
* date (JSON)
[source,JSON]
----
{ "date": "1969-07-20" }
----

====

[[type-casts]]
==== Type casts

include::recommendations/basic-cql2/PER_type-casts.adoc[]

This Standard does not prescribe how types are cast. The evaluation of filter expressions that involve type casts will, therefore, be system dependent.

For example, a system that evaluates the an expression `'5' > 4` can, for example,

* throw an error (incompatible types in a comparison operator);
* cast the number to an string (`'5' > '4'`);
* cast the string to a number (`5 > 4`).

[[basic-cql2_property]]
=== Property references

Properties in an object being evaluated in the CQL2 filter expression can be
referenced by their name (rule `propertyName`).

include::requirements/basic-cql2/REQ_property.adoc[]

For example, a property name used in a scalar expression (rule `scalarExpression`)
has to be a queryable of type `string`, `number`, `integer`, `boolean`, `date`, or `timestamp`.

[[example_8_2]]
.Property reference in a scalar expression
====
In this example, the property `windSpeed` is used in a function that receives an array of numbers and returns a number.
----
avg(windSpeed)
----

[source,JSON]
----
{ "function": { "name": "avg", "args": [ { "property": "windSpeed" } ] } }
----
====

[[basic-cql2_comparison-predicates]]
=== Standard comparison predicates

include::requirements/basic-cql2/REQ_binary-comparison-predicate.adoc[]

Instants (timestamps and dates) are scalar data types. All implementations have to support the comparison of two timestamps or two dates. How this is implemented is a decision of the server and will depend on the internal represenation. For example, the server could compare the RFC 3339 string representations of the two timestamps.

[[example_8_3]]
.Binary comparison predicates
====
----
city='Toronto'
----

[source,JSON]
----
{
  "op": "=",
  "args": [
    { "property": "city" },
    "Toronto" 
  ]
}
----

----
avg(windSpeed) < 4
----

[source,JSON]
----
{
  "op": "<",
  "args": [
    {
      "function": {
        "name": "avg",
        "args": [
          { "property": "windSpeed" }
        ]
      }
    },
    4
  ]
}
----

----
balance-150.0 > 0
----

[source,JSON]
----
{
  "op": ">",
  "args": [
    {
      "op": "-",
      "args": [
        { "property": "balance" },
        150.0
      ]
    },
    0
  ]
}
----

----
updated >= date('1970-01-01')
----

[source,JSON]
----
{
  "op": ">=",
  "args": [
    { "property": "updated" },
    { "date": "1970-01-01" }
  ]
}
----
====

include::requirements/basic-cql2/REQ_null-predicate.adoc[]

[[example_8_7]]
.Examples of a NULL predicate
====
----
geometry IS NOT NULL
----

[source,JSON]
----
{
  "op": "not",
  "args": [
    {
      "op": "isNull",
      "args": [
        { "property": "geometry" }
      ]
    }
  ]
}
----
====

=== CQL2 Encodings

This document defines a <<basic-cql2-text,text>>
encoding and a <<basic-cql2-json,JSON>> encoding of CQL2 that covers Basic CQL2
and all enhanced capabilities specified in the next clause.
