[[cql2-core]]
== Requirements Class "Basic CQL2"

[[basic-cql2-overview]]
=== Overview

include::requirements/requirements_class_basic-cql2.adoc[]

This clause defines the core of a query language called `Common Query Language`
(CQL2) that may be used to construct filter expressions. This core is called Basic CQL2.

Subsequent clauses define additional filtering capabilities as well as several
encodings of CQL2.

[[basic-cql2_filter-expression]]
=== CQL2 filter expression

A CQL2 filter expression is an expression that defines a logically connected
set of predicates that are evaluated for each item of a collection.

A predicate is an expression that evaluates to the Boolean values of `TRUE`
or `FALSE` or that evaluates to the value `NULL` when dealing with unknown
values.

If a predicate evaluates to `TRUE` for an item, the item qualifies for
further processing such as presentation in the result set, being passed on
to the next predicate in the filter for further evaluation, and so forth.

If the predicate evaluates to `FALSE` or `NULL` for an item, the item is not
available for further processing.

A collection item that satisfies ALL the requirements of a CQL2 filter expression
evaluates to a Boolean value of `TRUE`; otherwise the CQL2 filter expression
evaluates to `FALSE`.

NOTE: The requirements in the rest of this specification only discuss predicates as evaluating to `TRUE` or `FALSE` and don't explicitly discuss predicates that evaluate to `NULL`.  For the purpose of evaluating a CQL2 filter expression, a query prediate that evaluates to `NULL` (i.e. of unknown value) is essentually the same as one that evaluates to `FALSE`.  That is, its effect is that a collection item being evaluated by the CQL2 filter expression would _not_ be passed on for further evaluation.

include::requirements/basic-cql2/REQ_cql2-filter.adoc[]

Literal values do not have to be supported on the left hand side of predicates and 
property references do not have to be supported on the right hand side of
predicates.

include::recommendations/basic-cql2/PER_cql2-filter.adoc[]

A Basic CQL2 filter expression can be constructed by logically connecting one
or more comparison predicates.

Support for the parts of CQL2 that are not part of Basic CQL2 is added in additional
requirements classes in <<cql2-enhancements>>:

* The rules `isLikePredicate`, `isBetweenPredicate` and `isInListPredicate` are added by requirements class <<rc_advanced-comparison-operators,Advanced Comparison Operators>>;
* Support for the `CASEI` and `ACCENTI` operators are added by requirements class <<rc_case-insensitive-comparison,Accent and Case-insensitive Comparison>>;
* The rule `spatialPredicate` is added by requirements classes <<rc_basic-spatial-operators,Basic Spatial Operators>> and <<rc_spatial-operators,Spatial Operators>>;
* The rule `temporalPredicate` is added by requirements class <<rc_temporal-operators,Temporal Operators>>.
* The rule `arrayPredicate` is added by requirements class <<rc_array-operators,Array Operators>>;
* The permission to not support the literal rules on the left hand side of predicates and the rule `propertyName` on the right hand side are removed by requirements class <<rc_property-property,Property-Property Comparisons>>;
* The rule `function` is added by requirements class <<rc_functions,Custom Functions>>;
* The rule `arithmeticExpression` is added by requirements class <<rc_arithmetic,Arithmetic Expressions>>.

Examples of Basic CQL2 filter expressions are included in the subsequent sub-clauses.

[[basic-cql2_literals]]
=== Literal values

A literal value is any part of an CQL2 filter expression that is used
exactly as it is specified in the expression. Literal values include:

* character strings (rule `characterLiteral`),
* numbers including integers and floating point values (rule `numericLiteral`),
* booleans (rule `booleanLiteral`),
* spatial geometries like points, line strings or polygons (rule `spatialLiteral`) and
* temporal geometries like instants or intervals (rule `temporalLiteral`).

[[example_8_1_a]]
.Simple literal examples
====

* character string
----
'This is a literal string.'
----
* character string with an escaped embeded quote 
----
'Via dell''Avvento'
----
* number
----
-100
3.14159
----
* boolean
----
true
false
----

====

For character literals, embeded quotes are escaped using double quotes (i.e. `''`).

[[example_8_1_b]]
.Spatial literal examples
====

* spatial geometry (WKT)
----
POLYGON((43.5845 -79.5442, 43.6079 -79.4893, 43.5677 -79.4632, 43.6129 -79.3925, 43.6223 -79.3238, 43.6576 -79.3163, 43.7945 -79.1178, 43.8144 -79.1542, 43.8555 -79.1714, 43.7509 -79.6390, 43.5845 -79.5442))
----
* spatial geometry (GeoJSON)
[source,JSON]
----
{
   "type": "Polygon",
   "coordinates": [
       [
          [43.5845,-79.5442],
          [43.6079,-79.4893],
          [43.5677,-79.4632],
          [43.6129,-79.3925],
          [43.6223,-79.3238],
          [43.6576,-79.3163],
          [43.7945,-79.1178],
          [43.8144,-79.1542],
          [43.8555,-79.1714],
          [43.7509,-79.6390],
          [43.5845,-79.5442]
      ]
   ]
}
----

====

For spatial geometries existing representations are used:

* Text: an https://portal.ogc.org/files/?artifact_id=25355[OGC Well-Known Text (WKT)] literal
* JSON: a https://www.rfc-editor.org/rfc/rfc7946.html#section-3.1[GeoJSON geometry] object

[[example_8_1_c]]
.Temporal literal examples
====

* temporal geometry (instants, text)
----
DATE('1969-07-20')
TIMESTAMP('1969-07-20T20:17:40Z')
----
* temporal geometry (instants, JSON)
[source,JSON]
----
{ "date": "1969-07-20" }
{ "timestamp": "1969-07-20T20:17:40Z" }
----
* temporal geometry (intervals, text)
----
INTERVAL('1969-07-16', '1969-07-24')
INTERVAL('1969-07-16T05:32:00Z', '1969-07-24T16:50:35Z')
INTERVAL('2019-09-09', '..')
----
* temporal geometry (intervals, JSON)
[source,JSON]
----
{ "interval": [ "1969-07-16", "1969-07-24" ] }
{ "interval": [ "1969-07-16T05:32:00Z", "1969-07-24T16:50:35Z" ] }
{ "interval": [ "2019-09-09", ".." ] }
----
====

For temporal values existing representations are used:

* Temporal instant:
** Text: a `DATE` or `TIMESTAMP` function with a https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6[RFC 3339 literal string]
** JSON: an object with a `date` or `timestamp` member with a https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6[RFC 3339 literal string value]
* Temporal interval:
** Text: an `INTERVAL` function with two temporal instants as parameters
** JSON: an object with an `interval` member with an array of https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6[RFC 3339 literal string] values (or ".." for an open end)

All temporal literals are in UTC ("Z").

[[basic-cql2_property]]
=== Property references

Properties in an object being evaluated in the CQL2 filter expression can be
referenced by their name (rule `propertyName`).

include::requirements/basic-cql2/REQ_property.adoc[]

For example, a property name used in a scalar expression (rule `scalarExpression`)
has to be a queryable of type `string`, `number`, `integer` or `boolean`.

[[example_8_2]]
.Property reference in a scalar expression
====
In this example, the property `windSpeed` is used in a function that returns a number.
----
avg(windSpeed)
----

[source,JSON]
----
{ "function": { "name": "avg", "arg": [ { "property": "windSpeed" } ] } }
----
====

[[basic-cql2_comparison-predicates]]
=== Standard comparison predicates

include::requirements/basic-cql2/REQ_binary-comparison-predicate.adoc[]

include::recommendations/basic-cql2/PER_time-instant-comparisons.adoc[]

[[example_8_3]]
.Binary comparison predicates
====
----
city='Toronto'
----

[source,JSON]
----
{
  "op": "=",
  "args": [
    { "property": "city" },
    "Toronto" ]
}
----

----
avg(windSpeed) < 4
----

[source,JSON]
----
{
  "op": "<",
  "args": [
    {
      "function": {
        "name": "avg",
        "args": [
          { "property": "windSpeed" }
        ]
      }
    },
    4
  ]
}
----

----
balance-150.0 > 0
----

[source,JSON]
----
{
  "op": ">",
  "args": [
    {
      "op": "-",
      "args": [
        { "property": "balance" },
        150.0
      ]
    },
    0
  ]
}
----

----
updated >= date('1970-01-01')
----

[source,JSON]
----
{
  "op": ">=",
  "args": [
    { "property": "updated" },
    { "date": "1970-01-01" }
  ]
}
----
====

include::requirements/basic-cql2/REQ_null-predicate.adoc[]

[[example_8_7]]
.Examples of a NULL predicate
====
----
geometry IS NOT NULL
----

[source,JSON]
----
{
  "op": "not",
  "args": [
    {
      "op": "isNull",
      "args": [
        { "property": "geometry" }
      ]
    }
  ]
}
----
====

=== CQL2 Encodings

This document defines a <<basic-cql2-text,text>>
encoding and a <<basic-cql2-json,JSON>> encoding of CQL2 that covers Basic CQL2
and all enhanced capabilities specified in the next clause.
