== References
This User Guide does not contain any normative content. The following documents are fundamental to the understanding of the WFS 3.0 Standards. A working knowledge of their content is recommended for any implementer of the WFS 3.0 Standards. For undated references, the latest edition of the document is the best resource.

* [[OpenAPI]] Open API Initiative: OpenAPI Specification 3.0.1,
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md
* [[rfc2616]] IETF: HTTP/1.1, RFC 2616, http://tools.ietf.org/rfc/rfc2616.txt
* [[rfc5988]] IETF: Web Linking, RFC 5988, http://tools.ietf.org/rfc/rfc5988.txt
* [[GMLSF]] van den Brink, L., Portele, C., Vretanos, P.: OGC 10-100r3,
Geography Markup Language (GML) Simple Features Profile, http://portal.opengeospatial.org/files/?artifact_id=42729
* [[GeoJSON]] Butler H, Daly M, Doyle A, Gillies S, Hagen S, Schaub T:
IETF RFC 7946, The GeoJSON Format, https://tools.ietf.org/rfc/rfc7946.txt
* [[schema.org]] Schema.org: http://schema.org/docs/schemas.html
* [[wfscookbook]] Cox S, Garnett J, Holmes C, Kralidis T, McLeod B, Parsons E, Vowles G: OGC's Web Feature Service (WFS) Cookbook, https://portal.opengeospatial.org/files/?artifact_id=4265&version=1
