== Section 10: Information Assurance

[[security]]
=== Security

[width="90%",cols="2,6a"]
|===
|*Requirement {counter:req-id}* |/req/oas30/security +

For cases, where the operations of the server are access-controlled, the security scheme(s) SHALL be documented in the OpenAPI definition.
|===

OpenAPI uses two constructs to describe security controls; Security Schemes, and Security Requirements.  

A Security Scheme object describes a specific security control. These objects reside in the OAS document root with the Components Object. Currently the specification supports the following link:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#security-scheme-object[security schemes]:

* HTTP authentication,
* an API key (either as a header or as a query parameter),
* OAuth2's common flows (implicit, password, application and access code) as defined in RFC6749, and
* OpenID Connect Discovery.

Security Requirements objects are used to identify the Security Schemes which apply to a portion of the API.  They can be specified at two levels: 

* Root: These Security Requirements apply to the whole document unless over-ridden.
* Operations: Security Requirements that apply to a single operation.  These requirements override any requirements specified at the root level.  

Rules for Applicability:

. When more than one Security Requirement is provided, only one has to be satisfied.

. A Security Requirement may map to more than one Security Scheme. In that case, all of the Schemes must be satisfied.

. An empty Security Requirement object is valid.  This indicates that there are no security controls.

Issues:

The following issues have been taken to the OpenAPI Technical Steering Committee for resolution.

. There is no way to directly associate a Security Requriement with a Server Object. This can lead to problems. Consider the case where an operation contains two Server Objects. These two servers each implement a different form of access control. There are Security Requirement objects for each form of access control. How does the client know which control goes with which server?  The answer at this time is that they don't.

. The scope of a Security Requirement is ambiguous in regards to resources. If the result of an operation is a document which contains links to other documents, does the Security Requirement apply to the links as well? Under the current version of OpenAPI we cannot tell for sure.

Our recomended way forward is to be aware of security constraints when designing your API.

. If two servers have different access controls, then put them on different paths.

. Organize your resources so that if a user has access to one resource, then they can access all linked resources as well.

. Use the appropriate HTTP status codes and messages. If the client does not have access, let them know what is missing.
```

